### ISSUE TITLE
Notification click does not navigate DIRECTLY to dialog screen

### ISSUE THREAD

**Issue by blackkara** [ConnectyCube/connectycube-flutter-samples#100]
**Specify the sample to which the issue belongs (use [x]):**
[X] Chat sample
[ ] P2P Call sample
[ ] Conference Call sample

**Platform (use [x])**
[X] Android
[ ] iOS

**Device info**
Manufacture: Xiaomi
Model: Mi 6
OS version: Android Pie

**Describe the bug:**
Page route doesn't work smoothly when app opened via notification click.

**Steps to Reproduce:**
1. Open the app then login successfully 
2. Go to background
3. Send a message from other device
4. Then see notification, and tap it. 
5. Then app comes to foreground. BUT the previously last screen appears first, then navigates to ChatDialogScreen

**Actual result:**
1. App -> SelectDialogScreen --> Then push app to background(Click HOME button) --> Receive notification ( Send a message from another device to this device)
2. Click notifcation --> App --> SelectDialogScreen(this screen should not appear) --> ChatDialogScreen

**Expected behavior:**
1. App -> SelectDialogScreen --> Then push app to background(Click HOME button) --> Receive notification ( Send a message from another device to this device)
2. Click notification --> App -->  ChatDialogScreen

**Comment by TatankaConCube** [comment]
@blackkara please fill all fields from the template for tickets. It will help us to faster localize the problem. From your description not understandable which platform it reproduces and which data you receive in the push notification.

**Comment by blackkara** [comment]
I also upload a video, As it seen at 10.sec,  ChatDialogScreen comes after SelectDialogScreen
[https://www.youtube.com/watch?v=l3tfZsW5GSw](https://www.youtube.com/watch?v=l3tfZsW5GSw)

**Comment by TatankaConCube** [comment]
It is expected behavior for our sample app. You can realize any required logic in your app.
