### ISSUE TITLE
Can you make peer to peer call example this is not working for me in latest version of flutter.

### ISSUE THREAD

**Issue by maheshbhattaraai** [ConnectyCube/connectycube-flutter-samples#103]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by TatankaConCube** [comment]
@maheshbhattaraai please share here the output for command `flutter doctor`

**Comment by maheshbhattaraai** [comment]
Its working now. But we call from the website(one user) to mobile app(another user) call can not be initiated .
