### ISSUE TITLE
How to accept call when _currentCall null

### ISSUE THREAD

**Issue by beheobong** [ConnectyCube/connectycube-flutter-samples#104]
**Specify the sample to which the issue belongs (use [x]):**
[ ] Chat sample
[ x] P2P Call sample
[ ] Conference Call sample

**Platform (use [x])**
[x ] Android
[ x] iOS

**Device info**
Manufacture: 
Model: 
OS version:

**Describe the bug:**
path file: connectycube-flutter-samples/p2p_call_sample/lib/src/managers/call_manager.dart
![Capture3](https://user-images.githubusercontent.com/53457593/126150059-0f24d7c3-244c-460f-95bc-f44ef92dc20a.JPG)
  
How to accept call when _currentCall null

**Comment by TatankaConCube** [comment]
@beheobong, not understandable what do you mean, how can you accept the call if you don't have it? Please add more details about your issue, what is the actual result and what is expected behavior.

**Comment by beheobong** [comment]
When i click in notification button accept it => it run to function acceptCall and _currentCall it is null. And my conversation not working. Please help resolve it? Thanks

**Comment by beheobong** [comment]
ok. I fixed by set new function onReceiveNewSession when event onSessionClosed
 ```dart
 _callClient = P2PClient.instance;

    _callClient.init();

    _callClient.onReceiveNewSession = onReceiveNewSession;

    _callClient.onSessionClosed = (callSession) {
      logger.i('CallManagerononSessionClosed');
      if (_currentCall != null &&
          _currentCall.sessionId == callSession.sessionId) {
        logger.e('CallManagerononSessionClosed reset _currentCall');
        _currentCall = null;
        _callClient.onReceiveNewSession = null;
        _callClient.onReceiveNewSession = onReceiveNewSession;
        CallKitManager.instance.reportEndCallWithUUID(callSession.sessionId);
        if (logger != null) {
          logger.i('set_currentCall null');
        }
      }
    };
```

**Comment by TatankaConCube** [comment]
No, your flow is wrong, it should be easier, like:
- receive a notification;
- accept the call from notification;
- open the app and save state for the call (accepted);
- login to the chat and add `onReceiveNewSession` listener;
- when receive a new call compare it with the saved state and if it was accepted from notification do accept for the received coll session;

This flow was realized in our P2P Calls sample.
If you need to connect to the call immediately after accepting it from notification, use the conference calls feature for it. In this case, the caller started publishing the call immediately after starting the call and any opponent can join it at any time.

**Comment by beheobong** [comment]
I don't user notification call when app open. When my app open i show ui wating to accept call. So I understand my app not working. So how to resolve show ui wating to accept call when my app open?

**Comment by TatankaConCube** [comment]
in this case, the flow will be like this:
- after starting the app make login to the chat;
- add `onReceiveNewSession` listener;
- after receiving a new call show the Incoming call screen for user
- after accepting the call from the Incoming call screen navigate the user to the Conversation screen and accept the call there.

**Comment by beheobong** [comment]
Yes, I do that. But when new other call comming I can't accept it and I log it show _currentCall = null. Please test it and help me? thanks

**Comment by TatankaConCube** [comment]
Looks like you don't set a current call correctly. Check your code. In `onReceiveNewSession` you receive a call ready for using (accept, reject).

**Comment by beheobong** [comment]
I ready set it. but i receive only first call when the same user. and second call it not receive  because _currentCall = null;

**Comment by TatankaConCube** [comment]
check the actual logic in our sample and use it in your app as an example, when you make any modifications in the main logic, you should search issues in your code
