### ISSUE TITLE
Notificaiton of a call comming when logout

### ISSUE THREAD

**Issue by beheobong** [ConnectyCube/connectycube-flutter-samples#105]
**Specify the sample to which the issue belongs (use [x]):**
[ ] Chat sample
[ x] P2P Call sample
[ ] Conference Call sample

**Platform (use [x])**
[x ] Android
[ x] iOS

**Device info**
Manufacture: 
Model: 
OS version:

**Describe the bug:**

When I run demo login and call, then I logout. I will receive notification call in my device. Please check and fix it ? thanks

**Comment by beheobong** [comment]
![Capture](https://user-images.githubusercontent.com/53457593/133871990-db546d5c-5cf2-497f-ac57-7019d29011fc.PNG)
Hello I log subscription.device.clientIdentificationSequence always null.
```sh
I/flutter (13900): cubeSubscription [{notification_channel: gcm, push_token: null, device: {udid: 625e24b5bc053f6d, platform: android}}]
I/flutter (13900): subscription.device.clientIdentificationSequence null
```
Maybe change check it:

```dart
 if (subscription.device.udid == deviceId) {
          sharedPrefs.saveSubscriptionId(subscription.id);
        }
```
To get subscriptionId and remove it when logout ?

**Comment by TatankaConCube** [comment]
Yes, temporary you can use your solution before we fix it in our SDK and sample.
