### ISSUE TITLE
[Background IOS]create event call when app is background not working 

### ISSUE THREAD

**Issue by beheobong** [ConnectyCube/connectycube-flutter-samples#106]
**Specify the sample to which the issue belongs (use [x]):**
[ ] Chat sample
[x ] P2P Call sample
[ ] Conference Call sample

**Platform (use [x])**
[ ] Android
[x ] iOS

**Device info**
Manufacture: 
Model: 
OS version:

**Describe the bug:**
p2p_call_sample\lib\src\managers\call_manager.dart line 181
```dart
CreateEventParams _getCallEventParameters(P2PSession currentCall) {
    // String callerName = users
    //     .where((cubeUser) => cubeUser.id == currentCall.callerId)
    //     .first
    //     .fullName;

    CreateEventParams params = CreateEventParams();
    params.parameters = {
      'message':
          "Incoming ${currentCall.callType == CallType.VIDEO_CALL ? "Video" : "Audio"} call",
      PARAM_CALL_TYPE: currentCall.callType,
      PARAM_SESSION_ID: currentCall.sessionId,
      PARAM_CALLER_ID: currentCall.callerId,
      PARAM_CALLER_NAME: Const.appName,
      PARAM_CALL_OPPONENTS: currentCall.opponentsIds.join(','),
      PARAM_IOS_VOIP: 1,
    };

    params.notificationType = NotificationType.PUSH;
    // TODO for sample we use DEVELOPMENT environment
    params.environment = CubeEnvironment.DEVELOPMENT;
    // params.environment = CubeEnvironment.PRODUCTION;
    // params.environment = Const.isDebugCC ? CubeEnvironment.DEVELOPMENT : CubeEnvironment.PRODUCTION;
    // bool isProduction = bool.fromEnvironment('dart.vm.product');
    // params.environment =
    //     isProduction ? CubeEnvironment.PRODUCTION : CubeEnvironment.DEVELOPMENT;
    params.usersIds = currentCall.opponentsIds.toList();

    return params;
  ```
When I change  params.environment = CubeEnvironment.DEVELOPMENT to  params.environment = CubeEnvironment.PRODUCTION and build enterprise it not working. And keep params.environment = CubeEnvironment.DEVELOPMENT then notification callkit sometime it is working and sometime it is not working.

**Comment by TatankaConCube** [comment]
Looks like you have a similar issue https://github.com/ConnectyCube/connectycube-flutter-samples/issues/91#issuecomment-852260800 please check it.

**Comment by beheobong** [comment]
Ok I see. But I don't understand why in create event params in class CallManager ` params.environment = CubeEnvironment.DEVELOPMENT;` And I try to change  params.environment = CubeEnvironment.PRODUCTION; . It not working in ios? And Can you explain it for me? thanks

**Comment by TatankaConCube** [comment]
Because when you make a subscription from iOS from release build, the system returns the separated token, and your device will receive only messages notifications sent to PRODUCTION environment. If you subscribe to DEVELOPMENT environment from the release build you will not receive any push notifications to iOS. For Android doesn't matter the build type for getting the token.

**Comment by beheobong** [comment]
You are misunderstanding what I mean. I mean the environment that generates the notification event, not the event that receives the notification. Please review the above comment? thanks

**Comment by TatankaConCube** [comment]
You should use the same environment for subscriptions and for events. If you subscribed to the `PRODUCTION` environment you should create events for `PRODUCTION` environments.

**Comment by beheobong** [comment]
I just done it. But it not working when I use create event `PRODUCTION `?  Are you test it?

**Comment by TatankaConCube** [comment]
Did you add the correct certificate to the Admin panel? Was it for release builds?

**Comment by beheobong** [comment]
yes. i do it. I release enterprise it working in create event `DEVELOPMENT` and not working create event `PRODUCTION`.  

> Ok I see. But I don't understand why in create event params in class CallManager ` params.environment = CubeEnvironment.DEVELOPMENT;` And I try to change params.environment = CubeEnvironment.PRODUCTION; . It not working in ios? And Can you explain it for me? thanks
And 




> **Specify the sample to which the issue belongs (use [x]):**
> [ ] Chat sample
> [x ] P2P Call sample
> [ ] Conference Call sample
> 
> **Platform (use [x])**
> [ ] Android
> [x ] iOS
> 
> **Device info**
> Manufacture:
> Model:
> OS version:
> 
> **Describe the bug:**
> p2p_call_sample\lib\src\managers\call_manager.dart line 181
> 
> ```dart
> CreateEventParams _getCallEventParameters(P2PSession currentCall) {
>     // String callerName = users
>     //     .where((cubeUser) => cubeUser.id == currentCall.callerId)
>     //     .first
>     //     .fullName;
> 
>     CreateEventParams params = CreateEventParams();
>     params.parameters = {
>       'message':
>           "Incoming ${currentCall.callType == CallType.VIDEO_CALL ? "Video" : "Audio"} call",
>       PARAM_CALL_TYPE: currentCall.callType,
>       PARAM_SESSION_ID: currentCall.sessionId,
>       PARAM_CALLER_ID: currentCall.callerId,
>       PARAM_CALLER_NAME: Const.appName,
>       PARAM_CALL_OPPONENTS: currentCall.opponentsIds.join(','),
>       PARAM_IOS_VOIP: 1,
>     };
> 
>     params.notificationType = NotificationType.PUSH;
>     // TODO for sample we use DEVELOPMENT environment
>     params.environment = CubeEnvironment.DEVELOPMENT;
>     // params.environment = CubeEnvironment.PRODUCTION;
>     // params.environment = Const.isDebugCC ? CubeEnvironment.DEVELOPMENT : CubeEnvironment.PRODUCTION;
>     // bool isProduction = bool.fromEnvironment('dart.vm.product');
>     // params.environment =
>     //     isProduction ? CubeEnvironment.PRODUCTION : CubeEnvironment.DEVELOPMENT;
>     params.usersIds = currentCall.opponentsIds.toList();
> 
>     return params;
> ```
> 
> When I change params.environment = CubeEnvironment.DEVELOPMENT to params.environment = CubeEnvironment.PRODUCTION and build enterprise it not working. And keep params.environment = CubeEnvironment.DEVELOPMENT then notification callkit sometime it is working and sometime it is not working.

**Comment by tranminhlan** [comment]
@beheobong You can help with some questions. 
1. I must create certificate for Voice IP or Push notification 
please, view the attached file 

thanks 
![Screen Shot 2021-08-19 at 23 57 57](https://user-images.githubusercontent.com/5136189/130111448-224370c1-7316-4339-a5f7-7e6153306729.png)

**Comment by beheobong** [comment]
Ok. I resole it. thanks support
