### ISSUE TITLE
notify by connectycube's own sdk for P2P call

### ISSUE THREAD

**Issue by beheobong** [ConnectyCube/connectycube-flutter-samples#107]
**Is your feature request related to a problem? Please describe.**
P2P call when 2 devices are connected to the internet
Incoming call notifications I see depend on 3rd party like firebase, ios callkit . And when it depends, some calls are delayed

**Describe the solution you'd like**
I want the notification to both notify from the 3rd party and notify by connectycube's own sdk.

**Describe alternatives you've considered**
From the sdk create an event that listens and displays the incoming call interface

**Comment by TatankaConCube** [comment]
A lot of our customers have different logic in their apps. They decide which tools use for their apps. We provide maximum universal solutions for all users with saving the compatibility between all supported platforms.
