### ISSUE TITLE
Error on p2p call.

### ISSUE THREAD

**Issue by maheshbhattaraai** [ConnectyCube/connectycube-flutter-samples#110]
**Specify the sample to which the issue belongs (use [x]):**
[ ] Chat sample
[ x] P2P Call sample
[ ] Conference Call sample

**Platform (use [x])**
[x ] Android
[ ] iOS

Can not get a push notification while video call with same code in the example in new project.
`{"errors":{"base":["Users with ids $id do not have push notification subscriptions"]}}`
gives in console

**Comment by maheshbhattaraai** [comment]
Notification is fired from the connectycube app but the app didn't get it
[https://ibb.co/mSnDmLm](URL)

**Comment by thananat-dev** [comment]
I encountered the same problem 
Notification is fired from the connectycube but app not receive , 

when i try use postman call fcm app receive notification

**Comment by zhukeev** [comment]
Chat notifications don't work too, but through firebase console it works.

**Comment by TatankaConCube** [comment]
@maheshbhattaraai @zhukeev  please check the same now

**Comment by maheshbhattaraai** [comment]
@TatankaConCube  what we can check I did not understand. Please can you elaborate?

**Comment by TatankaConCube** [comment]
Today server-side team did some fixes on the push server and now push notifications should work.

**Comment by maheshbhattaraai** [comment]
@TatankaConCube  its works before around 16,17 days I had tested well. Anyway thanks for responding quickly.

**Comment by maheshbhattaraai** [comment]
We can go in production through connectycube.

**Comment by maheshbhattaraai** [comment]
@TatankaConCube  push notification didn't work yet.

**Comment by TatankaConCube** [comment]
hm..., checked on my side and it works

**Comment by maheshbhattaraai** [comment]
@TatankaConCube  only in this package com.connectycube.flutter.p2p_call_sample fires notification not fired in our package name.

**Comment by TatankaConCube** [comment]
in this case, check did you correctly added the app to the Firebase console. Did you use the right google-services.json. Did you add the correct API token in the Connectycube admin panel?

**Comment by maheshbhattaraai** [comment]
Yes, I have done everything you mentioned above. In Push_Notification_Manager.dart I had changed com.connectycube.flutter.p2p_call_sample to my package name . I need to change anything inside the android folder.

**Comment by maheshbhattaraai** [comment]
@TatankaConCube  This issue will be fixed or not?

**Comment by maheshbhattaraai** [comment]
It's working now.
