### ISSUE TITLE
Cannot run in ios

### ISSUE THREAD

**Issue by nambui2000k** [ConnectyCube/connectycube-flutter-samples#112]
Help me, I run in ios then have error, Can you help me fix it?
<img width="1440" alt="Screen Shot 2021-08-02 at 16 17 23" src="https://user-images.githubusercontent.com/49670327/127837097-066f4e62-62c6-47f6-a08c-c8d32680cbbc.png">

**Comment by TatankaConCube** [comment]
The issue is not related to the Connectycube app or SDK. Try to clean your project and regenerate the pods.

**Comment by azamatig** [comment]
see this [https://github.com/peerwaya/flutter_call_kit/issues/22](https://github.com/peerwaya/flutter_call_kit/issues/22)
hope it helps

**Comment by nambui2000k** [comment]
thanks you. e run it ok.
