### ISSUE TITLE
Can we make user presence in connectycube for online offline.

### ISSUE THREAD

**Issue by maheshbhattaraai** [ConnectyCube/connectycube-flutter-samples#119]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by TatankaConCube** [comment]
In our Flutter SDK, we have not implemented the 'Roster' feature yet. At this moment you can use the [Last activity](https://developers.connectycube.com/flutter/messaging?id=get-last-activity) feature for checking user status. This request returns `0` if the user is online now.

**Comment by maheshbhattaraai** [comment]
Thank You.
