### ISSUE TITLE
Difficulty in finding application crash issue after using connectycube in flutter application.

### ISSUE THREAD

**Issue by Dhiraj23082000** [ConnectyCube/connectycube-flutter-samples#12]
HI, Im using connectycube in my application for video calling services.When i build my app in debug mode,it is working properly without any issue .But when i open my app after final apk building it is crashing and all this occuring after using connectycube sdk in my app.

**Comment by Dhiraj23082000** [comment]
@TatankaConCube  can you help me out?
This is very major issue for me as my whole app depends on this.

**Comment by Dhiraj23082000** [comment]
@TatankaConCube

**Comment by TatankaConCube** [comment]
We are investigating your issue, and we will answer you after our internal checks.

**Comment by TatankaConCube** [comment]
Looks like you have a problem with obfuscation of some classes from WebRTC lib. Try add in your `build.gradle` file of module level next lines in release bid config:
```gradle
buildTypes {
        release {
            //your code here

            minifyEnabled true
            useProguard true

            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
}
```

Then create file **path/to/project/connectycube-flutter-samples/p2p_call_sample/android/app/proguard-rules.pro** with next content
```
## Flutter wrapper
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
-dontwarn io.flutter.embedding.**
	
## Flutter WebRTC
-keep class com.cloudwebrtc.webrtc.** { *; }
-keep class org.webrtc.** { *; }
```
And build your release again.

**Comment by Dhiraj23082000** [comment]
thanks!Now my app is working
