### ISSUE TITLE
Notification call handle

### ISSUE THREAD

**Issue by beheobong** [ConnectyCube/connectycube-flutter-samples#120]
```sh
For background calls we use Connectycube Push notifications feature and some helpful plugins:

For iOS we use:

flutter_voip_push_notification;
flutter_call_kit (from the GitHub repository);
For Android we use:

firebase_messaging
connectycube_flutter_call_kit
```
I found 2 lib:
- https://pub.dev/packages/callkeep
- https://pub.dev/packages/flutter_callkeep
they support both Android and IOS. And you try to use them?

**Comment by TatankaConCube** [comment]
When we developed our samples we investigated some available plugins and selected these. But you can use any other plugins in your project.

**Comment by beheobong** [comment]
ok. i will check it. thanks you so much
