### ISSUE TITLE
[IOS] Error can't build project 

### ISSUE THREAD

**Issue by tranminhlan** [ConnectyCube/connectycube-flutter-samples#123]
Hi @TatankaConCube 
 I build and work good for android . But ion IOS 

Undefined symbols for architecture armv7:
  "_AVAudioSessionInterruptionTypeKey", referenced from:
      -[FlutterCallKitPlugin provider:didActivateAudioSession:] in FlutterCallKitPlugin.o
  "_AVAudioSessionInterruptionOptionKey", referenced from:
      -[FlutterCallKitPlugin provider:didActivateAudioSession:] in FlutterCallKitPlugin.o
  "_AVAudioSessionInterruptionNotification", referenced from:
      -[FlutterCallKitPlugin provider:didActivateAudioSession:] in FlutterCallKitPlugin.o
  "_AVAudioSessionCategoryPlayAndRecord", referenced from:
      -[FlutterCallKitPlugin configureAudioSession] in FlutterCallKitPlugin.o
  "_AVAudioSessionModeVoiceChat", referenced from:
      -[FlutterCallKitPlugin configureAudioSession] in FlutterCallKitPlugin.o
  "_OBJC_CLASS_$_AVAudioSession", referenced from:
      objc-class-ref in FlutterCallKitPlugin.o
ld: symbol(s) not found for architecture armv7

Please, help me this issue.

**Comment by TatankaConCube** [comment]
it is the same issue with https://github.com/ConnectyCube/connectycube-flutter-samples/issues/112, try to use this version of FlutterCallKitPlugin 
```yaml
flutter_call_kit:
    git:
      url: git://github.com/raj457036/flutter_call_kit.git
      ref: master
```

**Comment by tranminhlan** [comment]
@TatankaConCube  I have fixed issue. Thanks
