### ISSUE TITLE
How can android device show incoming call when screen is off.

### ISSUE THREAD

**Issue by indwrld** [ConnectyCube/connectycube-flutter-samples#125]
**Specify the sample to which the issue belongs (use [x]):**
[ ] Chat sample
[x] P2P Call sample
[ ] Conference Call sample

**Platform (use [x])**
[x] Android
[ ] iOS

**Device info**
Manufacture: Samsung
Model: Galaxy 10
OS version: android 10

**Describe the bug:**

When screen is off and incoming call is received
it shows black off screen with sound.
And I press power button then shows incoming call screen.

In ios, it works well. It shows incoming call screen when screen is off..

Here's manifest file. -----------------------------------------

 application
        android:name="io.flutter.app.FlutterApplication"
        android:icon="@mipmap/ic_launcher"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:label="test_title">
        
        activity
            android:name=".MainActivity"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:showWhenLocked="true"
            android:showOnLockScreen="true"
            android:turnScreenOn="true"
            android:windowSoftInputMode="adjustResize">

And MainActivity.kt ------------------------

package com.test.title

import android.os.Bundle
import android.os.PersistableBundle
import io.flutter.embedding.android.FlutterActivity

import androidx.annotation.NonNull
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugin.common.MethodChannel
import android.content.Context
import android.content.ContextWrapper
import android.content.Intent
import android.content.IntentFilter
import android.os.Build.VERSION
import android.os.Build.VERSION_CODES
import android.app.NotificationManager;
import android.app.NotificationChannel;
import android.net.Uri;
import android.media.AudioAttributes;
import android.content.ContentResolver;

class MainActivity: FlutterActivity() {
    private val CHANNEL = "test.com/test_channel" 

    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)
        MethodChannel(flutterEngine.dartExecutor.binaryMessenger, CHANNEL).setMethodCallHandler {
            // Note: this method is invoked on the main thread.
            call, result ->

            if (call.method == "createNotificationChannel"){
                val argData = call.arguments as java.util.HashMap<String, String>
                val completed = createNotificationChannel(argData)
                if (completed == true){
                    result.success(completed)
                }
                else{
                    result.error("Error Code", "Error Message", null)
                }
            } else {
                result.notImplemented()
            }
        }

    }

    private fun createNotificationChannel(mapData: HashMap<String,String>): Boolean {
        val completed: Boolean
        if (VERSION.SDK_INT >= VERSION_CODES.O) {
            // Create the NotificationChannel
            val id = mapData["id"]
            val name = mapData["name"]
            val descriptionText = mapData["description"]
            val sound = "your_sweet_sound"
            val importance = NotificationManager.IMPORTANCE_HIGH
            val mChannel = NotificationChannel(id, name, importance)
            mChannel.description = descriptionText

            // Register the channel with the system; you can't change the importance
            // or other notification behaviors after this
            val notificationManager = getSystemService(NOTIFICATION_SERVICE) as NotificationManager
            notificationManager.createNotificationChannel(mChannel)
            completed = true
        }
        else{
            completed = false
        }
        return completed
    }
}

**Expected behavior:**

In android.
If incoming call is received when device screen  is off.
I wanna device shows incoming call screen immediately without pressing power button.

**Comment by TatankaConCube** [comment]
In our sample, it has already been implemented via the Push notifications feature and Callkit plugin for Android.

**Comment by indwrld** [comment]
It was saved before completing editing a few minutes ago.  I completed editing now.

**Comment by TatankaConCube** [comment]
I do not completely understand what do you need. In your example, you just create the notification channel without displaying any notifications and screens. In our example already realized this functionality. If our solution does not suit you realize it in any way that you want.

**Comment by indwrld** [comment]
I download sample and build with editing some.
it works well.

Just one thing.. 
In android device
when device screen is off and call is received, device is still off(black screen) and sounds ringtone.
So I press device button then device screen is turned on and show incoming call screen.

I want device is turned on when call is received (when screen is off)

**Comment by TatankaConCube** [comment]
Which device do you use for reproducing it? Which version of android?

**Comment by indwrld** [comment]
My device is samsung galaxy s10 and android 10.
