### ISSUE TITLE
Update flutter_webrtc version to 0.6.5

### ISSUE THREAD

**Issue by raj457036** [ConnectyCube/connectycube-flutter-samples#128]
**Is your feature request related to a problem? Please describe.**
The current version of connectyCube uses flutter_webrtc 0.6.2 but the latest one is 0.6.5. Some of new features included in version 0.6.5 is very crucial for our work. 

**Describe the solution you'd like**
Can you guys please upgrade the version to 0.6.5.

**Describe alternatives you've considered**
Since the source is close I don’t think there is any alternate way to achieve this.

**Comment by TatankaConCube** [comment]
@raj457036 we plan to do this in the near few days. Could you please say which features do you need from this version (just for information)? BTW today was released version 0.6.6, we will use it in the next release)))

**Comment by TatankaConCube** [comment]
@raj457036 today we have released a new version with updated dependencies, use it.
