### ISSUE TITLE
Dialog is deleted but exception anyway raised: FormatException: Unexpected end of input (at character 1) 

### ISSUE THREAD

**Issue by GRyabkin** [ConnectyCube/connectycube-flutter-samples#130]
**Specify the sample to which the issue belongs (use [x]):**
[x] Chat sample
[ ] P2P Call sample
[ ] Conference Call sample

**Platform (use [x])**
[x] Android
[ ] iOS

**Device info**
Manufacture: Google
Model: Pixel3
OS version: Android 11

**Describe the bug:**
Function deleteDialogs(dialogIds) always throws format exception 
"Delete Dialog: FormatException: Unexpected end of input (at character 1)"

Dialog is deleted but exception anyway raised

**Steps to Reproduce:**
1.  Use delete dialog function

**Logs:**
```
lI/flutter ( 3959): CB-SDK: : =========================================================
I/flutter ( 3959): === REQUEST ==== 6c770be8-5cf9-4322-9ad8-5cbf9f0c1cb4 ===
I/flutter ( 3959): REQUEST
I/flutter ( 3959):   DELETE https://api.connectycube.com/chat/Dialog/6133844f0f1d5e00326cb268 
I/flutter ( 3959): HEADERS
I/flutter ( 3959):   {Content-type: application/json, ConnectyCube-REST-API-Version: 0.1.1, CB-SDK: Flutter 2.0.2, CB-Token: 78BF2631900FAF880E4EE28EF4C1AE7BD6FF}
I/flutter ( 3959): BODY
I/flutter ( 3959):   
I/flutter ( 3959): 
I/flutter ( 3959): CB-SDK: : *********************************************************
I/flutter ( 3959): *** RESPONSE *** 200 *** 6c770be8-5cf9-4322-9ad8-5cbf9f0c1cb4 ***
I/flutter ( 3959): HEADERS
I/flutter ( 3959):   {cb-token-expirationdate: 2021-09-04 16:38:13 UTC, connection: keep-alive, date: Sat, 04 Sep 2021 14:38:13 GMT, strict-transport-security: max-age=15768000; includeSubDomains, content-length: 0, server: nginx/1.16.1}
I/flutter ( 3959): BODY
I/flutter ( 3959):   
I/flutter ( 3959): 
```

**Actual result:**

**Expected behavior:**
Exception is thrown only on real error, this one looks like internal unhandled exception. Also there's a model `DeleteItemsResult` which has arrays of `successful` `notFound` and `wrongPermission` lists of dialogs.
I am waiting (DeleteItemsResult? result) to check that dialogs were deleted but receive an exception

Also you throw Exception NotFound 404, even so `DeleteItemsResult` has list named `notFound`

**Comment by TatankaConCube** [comment]
the better chousing here will be to delete a single dialog via `deleteDialog` and multiple dialogs via `deleteDialogs`

**Comment by GRyabkin** [comment]
> the better chousing here will be to delete a single dialog via `deleteDialog` and multiple dialogs via `deleteDialogs`

well there's possibility that a user may have more than one dialog therefore I use `deleteDialogs`, do you propose to use those functions conditionally by checking length of dialogs array?

**Comment by TatankaConCube** [comment]
at this moment yes, I discussed with the server-side team and they promised to universalize the response, but before it, use my workaround
