### ISSUE TITLE
when screen lock, app killed How to accept call a long time

### ISSUE THREAD

**Issue by beheobong** [ConnectyCube/connectycube-flutter-samples#132]
**Specify the sample to which the issue belongs (use [x]):**
[ ] Chat sample
[ x] P2P Call sample
[ ] Conference Call sample

**Platform (use [x])**
[ x] Android
[x ] iOS

**Device info**
Manufacture: 
Model: 
OS version:

**Describe the bug:**
 when screen lock, app killed How to accept call now not waiting

**Steps to Reproduce:**
1. Login in connectycube
2. killed app, turn off screen
3. await 2h
4. Notification comming in my phone => accept call
5. Open app a long time to authen connectycube and open conversation screen

**Logs:**
```
log here
```
or
[Gist log](https://gist.github.com/)

**Actual result:**

**Expected behavior:**
Accept call => can talk and join conversation now

**Additional info**

**Comment by TatankaConCube** [comment]
You can't to do this using p2p feature. Use the Conference calls feature if you need to join to the call immediately.
