### ISSUE TITLE
No need to restart the app, you can receive calls right away

### ISSUE THREAD

**Issue by beheobong** [ConnectyCube/connectycube-flutter-samples#134]
**Specify the sample to which the issue belongs (use [x]):**
[ ] Chat sample
[ ] P2P Call sample
[x ] Conference Call sample

**Platform (use [x])**
[ x] Android
[x ] iOS

**Device info**
Manufacture: 
Model: 
OS version:

**Describe the bug:**
No need to restart the app, you can receive calls right away

**Steps to Reproduce:**
1. Login app success
2. kill app
3. notification comming call
4. accept call. await app restart and not recevice cal
5. => No need to restart the app, you can receive calls right away

**Comment by TatankaConCube** [comment]
What do you mean about `await app restart`? Just start after the killing? In the Conference calls sample we don't realize all features from P2P calls to avoid duplications of code, instead we just demonstrate how this feature work and customers can add all required functionality in their apps.

**Comment by beheobong** [comment]
yes. await app restart. how to go to conversation now when call comming?

**Comment by TatankaConCube** [comment]
For the Conference calls feature you can join the call immediately and send the 'accept' package after establishing a chat connection in the background invisible for a user.
