### ISSUE TITLE
 Conference Call sample not working in release

### ISSUE THREAD

**Issue by beheobong** [ConnectyCube/connectycube-flutter-samples#135]
**Specify the sample to which the issue belongs (use [x]):**
[ ] Chat sample
[ ] P2P Call sample
[x ] Conference Call sample

**Platform (use [x])**
[ x] Android
[x ] iOS

**Device info**
Manufacture: 
Model: 
OS version:

**Describe the bug:**
 Conference Call sample not working in release ? Any config ?

**Comment by TatankaConCube** [comment]
Do you have the same issue for both platforms? IOS and Android? For Android try to add obfuscation rules to the project in the same way as in our [P2P sample](https://github.com/ConnectyCube/connectycube-flutter-samples/blob/master/p2p_call_sample/android/app/proguard-rules.pro). For iOS try to apply the solution from https://github.com/ConnectyCube/connectycube-flutter-samples/issues/91

**Comment by TatankaConCube** [comment]
@beheobong have you try our solutions? Any luck here?
