### ISSUE TITLE
No Incoming call sceen when app is in background and foregorund.

### ISSUE THREAD

**Issue by TouseefAQ** [ConnectyCube/connectycube-flutter-samples#137]
**Specify the sample to which the issue belongs (use [x]):**
[ ] Chat sample
[ x] P2P Call sample
[ ] Conference Call sample

**Platform (use [x])**
[x ] Android
[ ] iOS

**Device info**
Manufacture: xiaomi
Model: Redmi 5 A prime , Redmi 5plus
OS version: 5A prime: 7.1 , Redmi 5plus: 8.1

**Describe the bug:**
I receive call notification when app is in background and foerground but not incoming call screen. And when i tap on notification it opens login screens then login the user and then to users screen no incomming call screen.

**Expected behavior:**
First of Aall on receiving call , Incoming call screen should open. Similarly even if i tap on notifcation it should open incoming call screen directly irrespect of first login the user.

**Comment by TatankaConCube** [comment]
Our sample just shows, how to use our SDK and you can change its behavior according to your needs. You can start the conversation screen with a progress bar before your user login in the background.
About the Incoming call screen - we realized the logic similar to common Phone apps if the device is unlocked you will see the notification with buttons and if the device is locked you will see the Incoming screen in full-screen mode.

**Comment by TouseefAQ** [comment]
Okay , Thank you clearing it out. But their is weird notification in system tray "A hands-free call in progress.Audio will still... "  even if i hang up the call , notifications remains and doesn't allow us to manage system audios except earpiece until i killed the app.
