### ISSUE TITLE
How to integrated WebRTC and SIP ?

### ISSUE THREAD

**Issue by beheobong** [ConnectyCube/connectycube-flutter-samples#138]
How to integrated WebRTC and SIP ? And sdk allow it?

**Comment by TatankaConCube** [comment]
What SIP features do you mean? What solutions do you use for it?  For which part of your product do you plan to use the WebRTC and for which SIP? WebRTC covers all needs related to audio/video calls.

**Comment by TatankaConCube** [comment]
Looks like the question is no longer actual, closing.
