### ISSUE TITLE
How to refesh session and relogin when Open connection error: AuthenticationFailure 

### ISSUE THREAD

**Issue by beheobong** [ConnectyCube/connectycube-flutter-samples#139]
How to refesh session and relogin when Open connection error: AuthenticationFailure

**Comment by TatankaConCube** [comment]
Which session do you mean? REST or Chat? Please describe your problem in more detail, what you do, what is the actual result, and what is the expected result?

**Comment by beheobong** [comment]
session  of chat. i make the same example but keep app about some time i can create it with user save

**Comment by TatankaConCube** [comment]
Could you provide the full log from starting the app till getting this issue without any filtering and cutting?

**Comment by TatankaConCube** [comment]
Looks like the question is no longer actual, closing.
