### ISSUE TITLE
Push notifications: add support of Notification message format

### ISSUE THREAD

**Issue by GRyabkin** [ConnectyCube/connectycube-flutter-samples#143]
**Specify the sample to which the issue belongs (use [x]):**
[x] Chat sample
[ ] P2P Call sample
[ ] Conference Call sample

**Platform (use [x])**
[x] Android
[x] iOS

**Device info**
Manufacture: Apple, Google
Model: 12, Pixel3a
OS version: 14.7, 11

**Describe the bug:**
I have integrated FirebaseMessaging for handling permissions and events as described in your documentation. I added handlers for handling pushes in background state (not terminated or foreground). They works pretty well if I send push notifications from FCM console.

Those handlers otherwise don't work if I send pushes using ConnectyCube dashboard or if I create event using curl command something like this:
```
curl -X POST \
-H "Content-Type: application/json" \
-H "CB-Token:  <TOKEN>" \
-d '{"event": {"notification_type": "push", "environment": "development", "user": { "ids": "4746624"}, "message": "eyJtZXNzYWdlIjoidXNyMiBjb250YWN0ZWQgeW91IHJlZ2FyZGluZyB5b3VyIGRhdmVyIEhESkRKMjgyOTI5MzgiLCJkaWFsb2dfaWQiOiI2MTQ2NTc3ZDNkZTYwYTAwMzMyM2UwMDYiLCJkYXZlcl9pZCI6ODQ5fQ=="}}' \
https://api.connectycube.com/events
```
where TOKEN is a session token. 

1. I see in logs that pushes are received but can't be handled by firebase messaging to show on screen. And this problem can be solved by adding `flutter_local_pushnotifications` which is redundant because FirebaseMessaging can do this without extra code.

2. Even if come to terms with (1) then there's another problem arise: firebase messaging handlers are not fired up. In your sample app which also doesn't work [you have the comment "to check when fix" ](https://github.com/ConnectyCube/connectycube-flutter-samples/blob/master/chat_sample/lib/src/push_notifications_manager.dart) at line 83. But actually this is not the issue at all. FirebaseMessaging works fine with notifications sent from FCM console.

And I figured out that handlers work fine and there's no need in the `flutter_local_notifications` dependency if `RemoteMessage` has `notification` field (`RemoteNotification`). Messages from FCM console have it and therefore they are shown and their selection handled properly:

<img width="589" alt="correct" src="https://user-images.githubusercontent.com/2230377/134218820-b1b6169e-64a7-449b-885f-7edfbf13b6ed.png">

The issue in the format you use to send push notifications, here's how your `RemoteMessage` looks like, notice absent `notification` field:

<img width="580" alt="Screenshot 2021-09-21 at 18 57 29" src="https://user-images.githubusercontent.com/2230377/134218617-e463abfe-e432-441b-a932-a07ddbd1672f.png">

**Steps to Reproduce:**
1.  Integrate firebase messaging and connecty cube
2. Send push notification from FCM console, check that it works 
3. Send push notification using connecty cube dashboard or create event using server API - discover the not handled by mobile app pushes and marked as delivered in dashboard logs

**Actual result:**
Push notifications have incorrect format which can't be handled correctly by FirebaseMessaging framework. If you are not going to fix the format so you have to notice user that your service doesn't support default format which is handled by FirebaseMessaging framework.

**Expected behavior:**
Push notifications have the same format as FCM console generates

**Comment by TatankaConCube** [comment]
As you know, FCM supports [two types](https://firebase.google.com/docs/cloud-messaging/concept-options#notifications_and_data_messages) of push notifications. The Connectycube server sends the second type of them (Data messages). In our Chat sample, we successfully manage them and show notifications after receiving new push notifications.

**Comment by GRyabkin** [comment]
@TatankaConCube ok, as I said support of the `Notification message` could reduce requirement of using additional dependency for showing push notification for user using ConnectyCube infrastructure and you have to forewarn in the documentation that user may send messages only using ConnectyCube service otherwise you need to change your handlers to support another format along with `Data message`

**Comment by GRyabkin** [comment]
Is there a way I can compose event with `notification` key to match `Notification message` format??

**Comment by TatankaConCube** [comment]
No, in the current realization of the server API it is not possible, but I will ask the server-side team about plans for this feature in the future.

**Comment by TatankaConCube** [comment]
Our server-side team added this feature to their roadmap, but I don't have any dates for its realization.

**Comment by aytunch** [comment]
Hi,
@GRyabkin have you found any solution to this push notification problem?
Our team will be deciding if `ConnectyCube` can be used reliably along with `FirebaseMessaging`
There is no way to interact with the push notifications sent from ConnectyCube when app is in the background and terminated. onTapped callbacks don't fire because FirebaseMessaging don't recognize ConnectyCube's notification format.

Also it is impossible to use `FlutterLocalPushNotification` together with `FirebaseMessaging` because of dependency issues.

@TatankaConCube is there any work being done to resolve this issue? Would creating a support ticket help?

**Comment by GRyabkin** [comment]
@aytunch no, I postponed work on a feature which uses push notifications on tap event and now considering replacing ConnectyCube at all.

**Comment by GRyabkin** [comment]
@aytunch true, but there's also another problem is that I couldn't find how not to store user messages in ConnectyCube backend what is violation for GDPR policies and the like, so anyway ...

**Comment by TatankaConCube** [comment]
@aytunch 
> Also it is impossible to use FlutterLocalPushNotification together with FirebaseMessaging because of dependency issues.

in our Chat sample, both plugins are used together for displaying the notifications, the navigation to the specific chat works too but only on the Android, need to investigate why it doesn't work on the iOS more deeply.

@GRyabkin to avoid the saving messages on the server-side you can set the parameter `message.saveToHistory = false;` or just delete this parameter from the sent message

**Comment by TatankaConCube** [comment]
@GRyabkin @aytunch happy to inform you that today our back-end team has released the Notification type for FCM. You can configure them in the Connectycube admin panel.

**Comment by aytunch** [comment]
> @GRyabkin @aytunch happy to inform you that today our back-end team has released the Notification type for FCM. You can configure them in the Connectycube admin panel.

@TatankaConCube I am very glad for this news. Can you point me to a link showing the documentation or migration process? Or a change log? Thanks

**Comment by TatankaConCube** [comment]
New options you can see in the Connectycube admin panel (Push Notifications -> Chat notifications). There were added a new checkbox and a few new configs such as NOTIFICATION TITLE, Chat message extra params to payload mapping. 
Server API documentation https://developers.connectycube.com/server/push_notifications?id=universal-push-notifications for manual creation event with the Notification type.
