### ISSUE TITLE
iOS Notifications not working correct

### ISSUE THREAD

**Issue by Maz47** [ConnectyCube/connectycube-flutter-samples#149]
**Specify the sample to which the issue belongs (use [x]):**
[x ] Chat sample
[ ] P2P Call sample
[ ] Conference Call sample

**Platform (use [x])**
[ ] Android
[ x] iOS

**Device info**
Manufacture: Apple
Model: every
OS version: every

**Describe the bug:**

We implemented firebase_messaging and flutter_local_notification into our app. We also registered the certificates in the ConnectyCube Admin Panel as well as in Firebase Console. We didn't get any notifications on iOS. So we implemented flutter_apns into our app. Now we are getting the notification in our iOS App but we can't customize it. The Notification get's displayed in a default way (title: our app name, body: title of message send). Especially for group chat messages we want to display the notification like so: <user_name>: <message>. How can I customize the flutter_apns notification? There are callbacks when initializing flutter_apns, but the notification gets displayed before going into these callbacks. So I think these APNS notifications get handled by the system some sort. Is there a way to catch the incoming notification like in firebase_messaging and show a custom notification with flutter_local_notification?

**Comment by Maz47** [comment]
> You can make some customizations from the Connectycube admin panel, just go to Chat -> Offline notifications, there you can change the template of a message and some other default parameters.

Thank you for the info. I already tried changing some of these values but they don't seem to do anything.

**Comment by TatankaConCube** [comment]
Have you saved your changes before the exit? Could you please share the screenshot with your changes?

**Comment by TatankaConCube** [comment]
I made similar changes for my app and result looks like:

<img src="https://user-images.githubusercontent.com/48598737/136359050-5b456308-bb81-4c49-ae13-bb09f5156e07.jpeg" height="350" />

Please, check one more time, have you save your settings by clicking on the 'Save' button at the bottom of the Settings page.

**Comment by Maz47** [comment]
yeah it is saved ... but thank you i will try it again
