### ISSUE TITLE
Null check operator used on a null value - When receive and send message

### ISSUE THREAD

**Issue by GimonLun** [ConnectyCube/connectycube-flutter-samples#151]
**Specify the sample to which the issue belongs (use [x]):**
[ x ] Chat sample
[ ] P2P Call sample
[ ] Conference Call sample

**Platform (use [x])**
[ x ] Android
[ x ] iOS

**Device info**
All device

**Describe the bug:**
We are getting `Null check operator used on a null value` error when receive and send message.
After we investigate this issues, we suspect it is only happens after CubeChatConnection.instance.relogin(); is called. 

The reason we suspect this is because our system is using custom identity provider and this relogin function will pass in the current cube user to the login methods directly.

From the login function, it use back the cube user current password directly, which maybe invalid or expired after first time verified it.

```dart
 xmpp.XmppAccountSettings account = xmpp.XmppAccountSettings(
        userJid, jid.local, jid.domain, cubeUser.password!, 5222,
        resource: resource);
 ```

According the [connect-to-chat-using-custom-authentication-providers](https://developers.connectycube.com/flutter/messaging?id=connect-to-chat-using-custom-authentication-providers) section, we need to pass in the password with CubeSessionManager.instance.activeSession?.token instead.

Is it the relogin function should accept a cube user instead for the case of using custom identity provider?

Sorry about we are not able to get the log since this only happens sometime and only in release app.

**Comment by TatankaConCube** [comment]
After the token expiration, you should renew it before using it as the password for the chat connection. We agree that it requires additional actions from developers, but at this moment it is the only variant for resolving your issue. We plan to implement the 'refresh token' creature and it should simplify resolving your issue, but we don't have the end date for implementation of this feature.
