### ISSUE TITLE
Archive Error

### ISSUE THREAD

**Issue by nambui2000k** [ConnectyCube/connectycube-flutter-samples#161]
**Specify the sample to which the issue belongs (use [x]):**
[] Chat sample
[x] P2P Call sample
[] Conference Call sample

**Platform (use [x])**
[] Android
[x] iOS
[] macOS
[] Windows
[] Web

**Device info**
Manufacture: 
Model: 
OS version:

**Describe the bug:**
When build archive I has error the same attachment image.
Run debug is OK.

<img width="1246" alt="Screen Shot 2021-11-01 at 09 14 20" src="https://user-images.githubusercontent.com/49670327/139612769-37dc35b2-8965-46f9-aef9-0923e77aa1b7.png">

**Steps to Reproduce:**
1.  Select tab Product
2. Select Archive
3.
4.

**Logs:**
```
log here
```
or
[Gist log](https://gist.github.com/)

**Actual result:**

**Expected behavior:**

**Additional info**

**Comment by TatankaConCube** [comment]
@nambui2000k after some investigation, we found that this issue is related to the `flutter_webrtc` which we use in our SDK. Its developers know about it and have the solution for it, but still don't release it. As a workaround use the previous version of our SDK `connectycube_sdk: 2.0.5`.

**Comment by nambui2000k** [comment]
> @nambui2000k after some investigation, we found that this issue is related to the `flutter_webrtc` which we use in our SDK. Its developers know about it and have the solution for it, but still don't release it. As a workaround use the previous version of our SDK `connectycube_sdk: 2.0.5`.

2.0.5 can i run flutter web?

**Comment by TatankaConCube** [comment]
> 2.0.5 can i run flutter web?

yes

**Comment by TatankaConCube** [comment]
@nambui2000k the version [2.0.7](https://pub.dev/packages/connectycube_sdk/versions/2.0.7) was released, try it. If the issue war resolved, please close this ticket.
