### ISSUE TITLE
p2p_call_sample google-services.json file missing error

### ISSUE THREAD

**Issue by KartikShrivastava** [ConnectyCube/connectycube-flutter-samples#162]
**Specify the sample to which the issue belongs (use [x]):**
[] Chat sample
[x] P2P Call sample
[] Conference Call sample

**Platform (use [x])**
[x] Android
[] iOS
[] macOS
[] Windows
[] Web

**Device info**
Manufacture: Motorola
Model: E4
OS version: Oreo

**Describe the bug:**
p2p_call_sample is not working out of the box, it is throwing google_services.json file not found error while building gradle files.

**Steps to Reproduce:**
1. Unzip the p2p_call_sample
2. Open in vscode
3. Run pub get
4. Hit play button with "Run without debugging" option

**Logs:**
```
Launching lib\main.dart on Moto E 4 in debug mode...
lib\main.dart:1

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  C:\Home\Projects\ProjectsArchive\p2p_call_sample\android\app\src\nullnull\google-services.json
  C:\Home\Projects\ProjectsArchive\p2p_call_sample\android\app\src\debug\google-services.json
  C:\Home\Projects\ProjectsArchive\p2p_call_sample\android\app\src\nullnullDebug\google-services.json
  C:\Home\Projects\ProjectsArchive\p2p_call_sample\android\app\src\nullnull\debug\google-services.json
  C:\Home\Projects\ProjectsArchive\p2p_call_sample\android\app\src\debug\nullnull\google-services.json
  C:\Home\Projects\ProjectsArchive\p2p_call_sample\android\app\google-services.json

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 2s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

**Actual result:**
Error thrown in gradle build stage.

**Expected behavior:**
App should start in the device.

**Additional info**
Please do point me to the right documentation if I'm missing some important step, I ran the code by referring to the ReadMe which says ```App will automatically run on your Android device.``` for android devices.

Thank you,
Kartik

**Comment by TatankaConCube** [comment]
Looks like you skip [this](https://github.com/ConnectyCube/connectycube-flutter-samples/tree/master/p2p_call_sample#configure-push-notifications) part of our guide, please check your steps one more time.

**Comment by KartikShrivastava** [comment]
Oh okay thank you for that. Would you mind putting it above ```Run``` in the readme as it goes well with the flow of readme, or maybe its just me who got confused.
