### ISSUE TITLE
How to play calling tune while P2P call is in connecting state

### ISSUE THREAD

**Issue by KartikShrivastava** [ConnectyCube/connectycube-flutter-samples#164]
Hi, this is neither a bug report nor a feature request.

It's a question regarding P2P calling, I just wanted to know how can we play some sort of audio in Device-1 speaker while it's calling Device-2 until Device-2 hasn't Accepted or Rejected the call?

Thanks,
ka_sh

**Comment by KartikShrivastava** [comment]
Is this repo not for asking general questions, but only bug reports or feature request?

**Comment by TatankaConCube** [comment]
Your feature is not related to Connectycube SDK or API. You can read the Flutter documentation on how to play audio in your app. Our samples are just an example of how to use Connectycube SDK in a project.

**Comment by KartikShrivastava** [comment]
Alright, thanks for clarification.

ka_sh
