### ISSUE TITLE
Need of setting accountKey in sendPushAboutRejectFromKilledState

### ISSUE THREAD

**Issue by KartikShrivastava** [ConnectyCube/connectycube-flutter-samples#166]
Hi,
Referencing the following lines of code:
https://github.com/ConnectyCube/connectycube-flutter-samples/blob/e235fce64a43b47ebc1781977c6c5d7b3ab3b5d9/p2p_call_sample/lib/src/managers/push_notifications_manager.dart#L234

What is the need of setting `accountKey` to send a reject call signal? I've noticed that even without setting `accountKey` is works fine.
And also in my usecase I don't want to retrieve `accountKey` from any source (be it sharedPrefs or cloud or hardcoded) when the app is in background(killed state), so is it okay to omit setting `accountKey` to send a reject signal, or it can cause some other issues which I'm not aware of?

**Comment by TatankaConCube** [comment]
We deprecated this field on the backend and you can skip it or set an empty string there. It doesn't have an effect on SDK's functionality.

**Comment by KartikShrivastava** [comment]
Got it, thanks for the info.
