### ISSUE TITLE
Handle case when user clicks on message area of notification banner in Android

### ISSUE THREAD

**Issue by KartikShrivastava** [ConnectyCube/connectycube-flutter-samples#167]
Hi,

When opponent calls a user in P2P sample, it handles `reject` and `accept` actions very well in all cases (like when android app is in background, foreground, locked state etc).

However, when user clicks in the message area of the call notification banner, fcm performs default action of opening up the app and it takes user to the `select_opponents_screen` ignoring the fact that opponent is still trying to call the user.

Can you please suggest a way to take user to `incoming_call_screen` when neither `reject` nor `accept` button is clicked rather user clicks somewhere in message area of the call notification banner? After that user can again decide whether to `accept` or `reject` the call.
My guess is that some case might need to be modified/added in `processCallNotification`:
https://github.com/ConnectyCube/connectycube-flutter-samples/blob/e235fce64a43b47ebc1781977c6c5d7b3ab3b5d9/p2p_call_sample/lib/src/managers/push_notifications_manager.dart#L173

**Comment by TatankaConCube** [comment]
in this case, you can check the call state on this screen and if it is `pending` show an Incoming call screen inside your app.

**Comment by TatankaConCube** [comment]
another solution - to add a separated event to `connectycube_flutter_call_kit` plugin like `onNotificationClick` or something like this.

**Comment by KartikShrivastava** [comment]
Thanks for these tips, I'll try to test them.

**Comment by KartikShrivastava** [comment]
Hi, I'm trying to go with the second solution given by you. After adding a new event to `connectycube_flutter_call_kit` and other required functions to the `p2p_sample` I got a bit confused about calling that event. Any suggestions on that?

**Comment by KartikShrivastava** [comment]
Closing as I felt this issue is not so relevant to this repo.
