### ISSUE TITLE
[Chat] Notification ios 

### ISSUE THREAD

**Issue by beheobong** [ConnectyCube/connectycube-flutter-samples#168]
**Specify the sample to which the issue belongs (use [x]):**
[x] Chat sample
[] P2P Call sample
[] Conference Call sample

**Platform (use [x])**
[x] Android
[x] iOS
[] macOS
[] Windows
[] Web

**Describe the bug:**
I uncheck  "ENABLE AUTOMATIC NOTIFICATIONS FOR OFFLINE USERS IN CHAT" from ConnectyCube Admin Panel
Because when my app onpause i don't want to logout socket. And then I use send push notifications of connectycube_sdk  for chat
But ios not show notification when my app in background. Then i subscribe APN of firebase_messaging . And notification show in ios but I Click notification ios not firing event. Please help me resole it? Thanks

**Comment by TatankaConCube** [comment]
> Because when my app onpause i don't want to logout socket.

for this case, you can use our new feature [Active/Inactive](https://developers.connectycube.com/flutter/messaging?id=mark-a-client-as-activeinactive), in this case you still logged in to the chat bar server will send chat push notifications if your user is `inactive`.

> but I Click notification ios not firing event.

sorry, but this issue is not related to the Connectycube SDK or API, follow the documentation for used plugin for getting required functionality

**Comment by beheobong** [comment]
Ok, I will try it. thank you so much

**Comment by beheobong** [comment]
How to remove "YOU HAVE 3 NEW MESSAGES." notification And where i can receive event click notification open app ?

**Comment by TatankaConCube** [comment]
> How to remove "YOU HAVE 3 NEW MESSAGES." notification

you can configure the template of the chat push notification in the Connectycube admin panel

> where i can receive event click notification open app ?

follow the documentation for the used plugin

**Comment by beheobong** [comment]
> follow the documentation for the used plugin
Can you share me link document? thanks. I create the same as sample but i can't receive event click notification open app in ios platform.
