### ISSUE TITLE
ConnectyCube code sample for Flutter doesn't work on mobile

### ISSUE THREAD

**Issue by Rizardomon** [ConnectyCube/connectycube-flutter-samples#170]
I am testing one of the code samples for flutter, the one with p2p calls. I cloned the repository for testing de SDK features and set my credentials from the dashboard. But when build the app on mobile for release and debug, the p2p call doesn't work, don't do calls and receive. Just on mobile, on web works fine. The logs just don't say nothing to I tried everything that says in the API docs, including another language samples, just for flutter i'm having this issue.

**Comment by TatankaConCube** [comment]
have you configured the push notifications in your project according to the [guide](https://github.com/ConnectyCube/connectycube-flutter-samples/tree/master/p2p_call_sample#background-calls)?

**Comment by Rizardomon** [comment]
Yes, I put in all the information requested in your guide, the key server is right too. But it also doesn't work on mobile, even when two phones are open and connected.

**Comment by Rizardomon** [comment]
@abhi-dasgupta hello sorry for the delay in responding here, I was busy with other company stuff, but what you said apparently worked, I am able to call and receive the calls just having updated the packages.

**Comment by Rizardomon** [comment]
> @Rizardomon can you see your push notifications in the Connectycube admin panel? The notification about the incoming calls on mobiles works via the push notifications feature (in background and foreground modes).

this is the menu of my push notifications

![image](https://user-images.githubusercontent.com/57680110/144240287-68e4f960-caa1-40a1-b221-4b7d2eebcbc3.png)
