### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by chaghen** [ConnectyCube/connectycube-flutter-samples#172]
**Specify the sample to which the issue belongs (use [x]):**
[] Chat sample
[] P2P Call sample
[] Conference Call sample

**Platform (use [x])**
[] Android
[] iOS
[] macOS
[] Windows
[] Web

**Device info**
Manufacture: 
Model: 
OS version:

**Describe the bug:**

**Steps to Reproduce:**
1. 
2.
3.
4.

**Logs:**
```
log here
```
or
[Gist log](https://gist.github.com/)

**Actual result:**

**Expected behavior:**

**Additional info**
CallManager.startNewCall managers/call_manager.dart:106

void startNewCall(BuildContext context, int callType, Set<int> opponents) {
    if (opponents.isEmpty) return;

    P2PSession callSession =
        _callClient!.createCallSession(callType, opponents);
    _currentCall = callSession;
    Navigator.push(
      context,
      MaterialPageRoute(
        builder: (context) => ConversationCallScreen(callSession, false),
      ),
    );

    _sendStartCallSignalForOffliners(_currentCall!);
  }

 _callClient! is null in p2P Sample when start call

**Comment by TatankaConCube** [comment]
please provide steps on how do you reproduce it in our sample

**Comment by chaghen** [comment]
i called  CallManager.instance
                      .startNewCall(context, CallType.VIDEO_CALL, cubeid); in my chat detail and pass it the id  (cubeid) of user which i want to call and the error trigger  Null check operator used on a null value

**Comment by chaghen** [comment]
_callClient! is null when i whant to call

**Comment by chaghen** [comment]
_callClient is not initialize, i don't known where initialized it

**Comment by TatankaConCube** [comment]
It means that you didn't create the instance of `_callClient`. Please be careful when you copy the code. In our sample, we call `CallManager. instance.init(context)` before using `CallManager`.

**Comment by TatankaConCube** [comment]
> _callClient is not initialize, i don't known where initialized it

[here](https://github.com/ConnectyCube/connectycube-flutter-samples/blob/master/p2p_call_sample/lib/main.dart#L29)

**Comment by TatankaConCube** [comment]
which one? do you reproduce it in your app or in our sample? if you reproduce it in your app please be more carefully when you copy our code to your project.

**Comment by chaghen** [comment]
i reproduce it in my app
