### ISSUE TITLE
Unable to get the ringtone for the second time after accepting the call.

### ISSUE THREAD

**Issue by Sriram-52** [ConnectyCube/connectycube-flutter-samples#178]
**Specify the sample to which the issue belongs (use [x]):**
[] Chat sample
[x] P2P Call sample
[] Conference Call sample

**Platform (use [x])**
[x] Android
[] iOS
[] macOS
[] Windows
[] Web

**Device info**
Manufacture:  Oneplus 7
Model: GM1901
OS version: Android 11

**Describe the bug:**
Unable to get the ringtone for the second time after accepting the call.
**Steps to Reproduce:**
1.Make a call from one device
2.Accept the call from other device
3.After some time cut, the call
4.Then call again 

**Actual result:**
Not getting ringtone after the first call.

**Expected behavior:**
Should get ringtone

**Comment by TatankaConCube** [comment]
@Sriram-52 we can't reproduce this issue on our devices. do you reproduce this issue in our sample or in your own app? do you have any other preconditions for reproducing it? does this issue reproduces on all your devices or only on the reported?
