### ISSUE TITLE
how to change the picture when calling?

### ISSUE THREAD

**Issue by chaghen** [ConnectyCube/connectycube-flutter-samples#181]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Please help me to change the picture when calling
**Describe alternatives you've considered**

**Additional context**

**Comment by TatankaConCube** [comment]
@chaghen Which picture do you mean? If it is about the incoming call screen then you should modify the [connectycube-flutter-call-kit](https://github.com/ConnectyCube/connectycube-flutter-call-kit) for setting the custom picture.

**Comment by chaghen** [comment]
talks about the image that is displayed when the application is in the background. your logo is displayed, it will mislead our users to see a call with a logo that they do not understand

![image](https://user-images.githubusercontent.com/84866822/148357082-7fb62e54-462b-4a6a-a7b2-7d82cc63c623.png)

**Comment by chaghen** [comment]
here is the image there, I must change this in which parameter?

**Comment by TatankaConCube** [comment]
this screen is displayed by the connectycube-flutter-call-kit plugin as I said before. It is an open-source lib and you can customize it according to your needs.

**Comment by chaghen** [comment]
please tell me wich parameter i can change. I spend many times yesterday but i don't know where i can change it

**Comment by chaghen** [comment]
please tell me wich parameter i can change. I spend many times yesterday but i don't know where i can change it

**Comment by TatankaConCube** [comment]
if you need just to change the picture you can replace this image https://github.com/ConnectyCube/connectycube-flutter-call-kit/blob/master/android/src/main/res/drawable-nodpi/cc_splash.png with your own.

**Comment by chaghen** [comment]
Thank you very much for your quick response. One last thing, I'm installing your plugin, how do I access your drawable? maybe the problem comes from me, but it is possible to access the drawable of your library?

**Comment by chaghen** [comment]
i installed using https://pub.dev/

**Comment by TatankaConCube** [comment]
you can fork this repo, make needed changes and use it in your project

**Comment by chaghen** [comment]
ok thank

**Comment by chaghen** [comment]
One thing that you will review in your project is the ringtone, when you receive a call, sometimes it rings and sometimes it is silent.

**Comment by TatankaConCube** [comment]
the ringtone plays from this lib too, you can fix it on your side and share the solution with the community)))

**Comment by chaghen** [comment]
thank you very much, you saved my day

**Comment by chaghen** [comment]
please is me again, i forked the repo but file flutter_call_kit.dart is missing, i only saw connectycube_flutter_call_kit.dart file

**Comment by chaghen** [comment]
i saw the problem

**Comment by chaghen** [comment]
Hello, just to tell you that I was able to edit ConnectyCube / connectycube-flutter-call- and use my own image as you can see in image. Now everything is working fine, I was able to integrate your plugin for video calls with flutter and it works perfectly. Even when the application is in the background or closed, we receive the video call. But I had to modify the pusnotification_manager file to make it work fine. For the ringtone which was random I had to modify the NotificationsManager.kt file as follows:

**Comment by chaghen** [comment]
![incoming](https://user-images.githubusercontent.com/84866822/148571274-c130fae8-e8c0-4947-b151-7740e285de3b.jpeg)

**Comment by chaghen** [comment]
Your code :   val ringtone: Uri = RingtoneManager.getActualDefaultRingtoneUri(
        context.applicationContext,
        RingtoneManager.TYPE_RINGTONE
    )

**Comment by chaghen** [comment]
my code :   val ringtone: Uri = RingtoneManager.getActualDefaultRingtoneUri(
        context,
        RingtoneManager.TYPE_RINGTONE
    )

**Comment by chaghen** [comment]
I used context instead of context.applicationContext

**Comment by chaghen** [comment]
I used context instead of context.applicationContext

**Comment by chaghen** [comment]
thank you very much
