### ISSUE TITLE
Video Encryption

### ISSUE THREAD

**Issue by KielCezar** [ConnectyCube/connectycube-flutter-samples#182]
I am trying to use this for my project and i have gone through the code and i still cant find where the video calling or audio call is encrypted in the code. This is the main part of my project (the encryption) and i was wondering if you could please point it out or explain how it works and if any keys are being exchanged

**Comment by TatankaConCube** [comment]
There are some links about the security in the WebRTC:
https://bloggeek.me/is-webrtc-safe/
https://webrtc-security.github.io/

Additionally, our SDK has the method `replaceMediaStream(MediaStream)` which provides you the possibility to set your own media stream after your transformations. 
Other helpful links:
https://webrtc.github.io/samples/
https://connectycube.com/2020/04/23/the-current-state-of-e2ee-in-webrtc/
