### ISSUE TITLE
Web integration instructions needed

### ISSUE THREAD

**Issue by KartikShrivastava** [ConnectyCube/connectycube-flutter-samples#187]
Hi,
It's been few months I'm working with cc flutter sdk and was able to make it work in android and ios. I'm only using voice calls and removed remote and local media stream to save some user data.
Yesterday I tried integrating it with flutter web app, and hit a roadblock. I'm not able to make web browser output the audio stream coming from peer user device. I've tried it between android<->chrome and android<-> edge browsers and both shows same results.
Also I tried searching for web integration steps in the docs but couldn't find any. So, can you please help me with this setup as it has really stopped our whole project progress.
I can surely provide logs but it doesn't seem to be relevant to me, as logs remain same as of android<->ios or android<->android tests. Kindly suggest some ways to troubleshoot this issue.

**Comment by TatankaConCube** [comment]
There is no specific logic for adding the web support for your app, it should work in the common Flutter way. As I understand you use the Windows OS for testing your Flutter web app if so have you provided all required permissions for the microphone for your browser (in the system settings) and for your web app before starting the call? Do you use other apps that use microphones at the same time with the call? Have you tried other OS like Linux or macOS? Do you have a similar issue there?

> I can surely provide logs but it doesn't seem to be relevant to me

provide them anyway here using [gist](https://gist.github.com/)

**Comment by KartikShrivastava** [comment]
That's right, I've only tested it in windows right now. I'll test it in macos and attatch the logs.

**Comment by KartikShrivastava** [comment]
At the moment I quickly tested p2p_call_sample in windows OS, as our project is heavily modified and getting logs there will take more time. Although in p2p_call_sample as well I'm not able to hear any audio coming out of web browser.
(Please note that I've also modified local copy of p2p_call_sample to some extinct and it does not matches with the original repo)
Logs: https://gist.github.com/KartikShrivastava/690e34aca2c0464ca82a0cb9c77d9197

**Comment by KartikShrivastava** [comment]
Here are the logs when call is initiated from android and receiver in chrome browser https://gist.github.com/KartikShrivastava/57a4d4f2216a958b70daf21adc1ea2c7.
In both logs I can notice onIceCandidate statements in android device but not in browser. Does it signifies some issue? And only permission in the browser I got was to enable microphone which was granted.

**Comment by TatankaConCube** [comment]
on the first look it looks ok, could you try to use version 2.0.9 of our SDK, it contains the latest version of [flutter_webrtc](https://pub.dev/packages/flutter_webrtc/changelog) lib with a lot of fixes for Windows.

**Comment by KartikShrivastava** [comment]
After upgrading the sdk to 2.0.9 in p2p_call_sample, chrome/windows is still not able to output the audio(tested it in macos as well but with our implementation and same results). But when using video call everything is working just fine. So, I'm still stuck as using video call with camera permission is not an option for us.

**Comment by TatankaConCube** [comment]
you didn't say that it reproduces only for audio calls, will check it on my side

**Comment by KartikShrivastava** [comment]
I'm not sure if its possible, but can we somehow log the audio and video stream packets separately using cc sdk? What I'm seeing is for some reason the browser does not receive audio if there is no incoming video stream.

**Comment by KartikShrivastava** [comment]
Hi @TatankaConCube, were you able to reproduce the audio issue? Just to be clear, it happens when we make audio call from/to the flutter web browser and browser is not able to play the audio coming from peer. I've tested it on latest p2p_call_sample with updated sdk and call_kit and it has the same issue.

**Comment by TatankaConCube** [comment]
I localized the issue and prepared the fix for SDK, will publish it soon in the new release

**Comment by KartikShrivastava** [comment]
Thanks a lot! Truly appreciate that, it's almost like you have saved us from investing in a turn server setup.

**Comment by TatankaConCube** [comment]
@KartikShrivastava version 2.0.10 has been published. In our sample it works without any changes, but as I understand you removed the logic of working with `RTCVideoRenderer` in your app. You should bring back it again, cause it is required for the Web for publishing the sound there in `AudioElement`.

P.S. if your issue was resolved, please close this ticket

**Comment by KartikShrivastava** [comment]
Just tested and it works perfectly. Thanks again for the prompt support! Truly life saver...
