### ISSUE TITLE
How to add custom parameters to message?

### ISSUE THREAD

**Issue by zombie6888** [ConnectyCube/connectycube-flutter-samples#189]
I've tried to add custom property to message properties map, but i can't get it from onReceiveMessage callback
```...
//sender
var message = CubeMessage();
message.properties['custom'] = 'custom param';
dialog.sendMessage(message);
...
//reciever
onReceiveMessage(CubeMessage message) {
   print(message.properties); //can't see my custom param here
}
```

**Comment by TatankaConCube** [comment]
Could you please provide the log from the flutter console from the sender side and the receiver side during sending these messages?

**Comment by TatankaConCube** [comment]
checked it just now in our Chat sample between Android and Web and it works well

**Comment by zombie6888** [comment]
i've tried it between 2 emulators. Sender  logs:
[log] ---Xmpp Sending:---
[log] <r xmlns="urn:xmpp:sm:3"/>
[log] ---Xmpp Receiving:---
[log] <a xmlns='urn:xmpp:sm:3' h='11'/>
[log] ---Xmpp Sending:---
[log] <message id="XINMWQEVS" type="chat" to="5323391-5842@chat.connectycube.com"><composing xmlns="http://jabber.org/protocol/chatstates"/></message>
[log] ---Xmpp Sending:---
[log] <message id="LXVGOBHKH" type="chat" to="5323391-5842@chat.connectycube.com"><composing xmlns="http://jabber.org/protocol/chatstates"/></message>
[log] ---Xmpp Sending:---
[log] <message id="IFDPCJUSQ" type="chat" to="5323391-5842@chat.connectycube.com"><composing xmlns="http://jabber.org/protocol/chatstates"/></message>
[log] ---Xmpp Sending:---
[log] <r xmlns="urn:xmpp:sm:3"/>
[log] ---Xmpp Receiving:---
[log] <a xmlns='urn:xmpp:sm:3' h='14'/>
[log] D/[StreamManagementModule]: Delivered: XINMWQEVS
[log] D/[StreamManagementModule]: Delivered: LXVGOBHKH
[log] D/[StreamManagementModule]: Delivered: IFDPCJUSQ
[log] ---Xmpp Sending:---
[log] <message id="TRGFVTWXF" type="chat" to="5323391-5842@chat.connectycube.com"><composing xmlns="http://jabber.org/protocol/chatstates"/></message>
I/flutter ( 1660): CB-SDK: : onSendMessage message= {_id: 61f7de60a685af56b63ee204, chat_dialog_id: null, message: test, date_sent: 1643634272, sender_id: null, recipient_id: null, read_ids: null, delivered_ids: null, views_count: null, attachments: [], id: null, created_at: null, updated_at: null, testprop: 2}
I/TextInputPlugin( 1660): Composing region changed by the framework. Restarting the input method.
W/IInputConnectionWrapper( 1660): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 1660): getTextBeforeCursor on inactive InputConnection
D/InputConnectionAdaptor( 1660): The input method toggled cursor monitoring on
[log] ---Xmpp Sending:---
I/flutter ( 1660): null
I/flutter ( 1660): null
I/flutter ( 1660): CB-SDK: : [getReadDeliveredWidget] sent
I/flutter ( 1660): null
I/flutter ( 1660): null
I/flutter ( 1660): CB-SDK: : [getReadDeliveredWidget] sent
I/flutter ( 1660): null
I/flutter ( 1660): null
I/flutter ( 1660): CB-SDK: : [getReadDeliveredWidget] sent
I/flutter ( 1660): null
I/flutter ( 1660): null
I/flutter ( 1660): CB-SDK: : [getReadDeliveredWidget] sent
I/flutter ( 1660): null
I/flutter ( 1660): null
I/flutter ( 1660): CB-SDK: : [getReadDeliveredWidget] sent
I/flutter ( 1660): null
I/flutter ( 1660): null
I/flutter ( 1660): CB-SDK: : [getReadDeliveredWidget] sent
I/flutter ( 1660): null
I/flutter ( 1660): null
I/flutter ( 1660): CB-SDK: : [getReadDeliveredWidget] sent
I/flutter ( 1660): markAsReadIfNeed message= {_id: 61f7d48fdf36f26e62950ff9, chat_dialog_id: 61dec100ae436100117f671f, message: fff, date_sent: 1643631759, sender_id: 5323391, recipient_id: 5323414, read_ids: [5323391, 5323414], delivered_ids: [5323391, 5323414], views_count: 0, attachments: [], id: null, created_at: 2022-01-31T12:22:39.000Z, updated_at: 2022-01-31T12:22:50.000Z, edited_at: null}, isOpponentMsgRead= true
I/flutter ( 1660): markAsReadIfNeed message= {_id: 61f7d443df36f26e62950ff8, chat_dialog_id: 61dec100ae436100117f671f, message: fff, date_sent: 1643631683, sender_id: 5323391, recipient_id: 5323414, read_ids: [5323391, 5323414], delivered_ids: [5323391, 5323414], views_count: 0, attachments: [], id: null, created_at: 2022-01-31T12:21:23.000Z, updated_at: 2022-01-31T12:21:48.000Z, edited_at: null}, isOpponentMsgRead= true
I/flutter ( 1660): markAsReadIfNeed message= {_id: 61f7ccbcdf36f26e62950ff7, chat_dialog_id: 61dec100ae436100117f671f, message: fff, date_sent: 1643629756, sender_id: 5323391, recipient_id: 5323414, read_ids: [5323391, 5323414], delivered_ids: [5323391, 5323414], views_count: 0, attachments: [], id: null, created_at: 2022-01-31T11:49:16.000Z, updated_at: 2022-01-31T11:49:27.000Z, edited_at: null}, isOpponentMsgRead= true
[log] <message id="61f7de60a685af56b63ee204" type="chat" to="5323391-5842@chat.connectycube.com"><body>test</body><extraParams xmlns="jabber:client"><date_sent>1643634272</date_sent><save_to_history>1</save_to_history><testprop>2</testprop><dialog_id>61dec100ae436100117f671f</dialog_id></extraParams><markable xmlns="urn:xmpp:chat-markers:0"/></message>
I/flutter ( 1660): null
I/flutter ( 1660): null
I/flutter ( 1660): CB-SDK: : [getReadDeliveredWidget] sent
[log] ---Xmpp Sending:---
[log] <r xmlns="urn:xmpp:sm:3"/>
[log] ---Xmpp Receiving:---
[log] <a xmlns='urn:xmpp:sm:3' h='16'/>
[log] D/[StreamManagementModule]: Delivered: TRGFVTWXF
[log] D/[StreamManagementModule]: Delivered: 61f7de60a685af56b63ee204

reciever logs: 

[log] ---Xmpp Sending:---
[log] <r xmlns="urn:xmpp:sm:3"/>
[log] ---Xmpp Receiving:---
[log] <a xmlns='urn:xmpp:sm:3' h='16'/>
[log] ---Xmpp Receiving:---
I/flutter ( 1660): CB-SDK: : Receive PRIVATE chat message 61f7debedf36f26e62950ffa
[log] <message xmlns="jabber:client" to="5323414-5842@chat.connectycube.com" id="61f7debedf36f26e62950ffa" type="chat" from="5323391-5842@chat.connectycube.com/flutter_790dc4b2287de17f"><body>test</body><extraParams xmlns="jabber:client"><date_sent>1643634366</date_sent><save_to_history>1</save_to_history><dialog_id>61dec100ae436100117f671f</dialog_id><message_id>61f7debedf36f26e62950ffa</message_id></extraParams><markable xmlns="urn:xmpp:chat-markers:0"/></message>
I/flutter ( 1660): CB-SDK: : onReceiveMessage message= {_id: 61f7debedf36f26e62950ffa, chat_dialog_id: 61dec100ae436100117f671f, message: test, date_sent: 1643634366, sender_id: 5323391, recipient_id: 5323414, read_ids: null, delivered_ids: null, views_count: null, attachments: [], id: null, created_at: null, updated_at: null, save_to_history: 1, dialog_id: 61dec100ae436100117f671f, message_id: 61f7debedf36f26e62950ffa}
I/flutter ( 1660): markAsReadIfNeed message= {_id: 61f7debedf36f26e62950ffa, chat_dialog_id: 61dec100ae436100117f671f, message: test, date_sent: 1643634366, sender_id: 5323391, recipient_id: 5323414, read_ids: null, delivered_ids: null, views_count: null, attachments: [], id: null, created_at: null, updated_at: null, save_to_history: 1, dialog_id: 61dec100ae436100117f671f, message_id: 61f7debedf36f26e62950ffa}, isOpponentMsgRead= false
I/flutter ( 1660): null
I/flutter ( 1660): null
I/flutter ( 1660): CB-SDK: : [getReadDeliveredWidget] sent
I/flutter ( 1660): null
I/flutter ( 1660): null
I/flutter ( 1660): CB-SDK: : [getReadDeliveredWidget] sent
I/flutter ( 1660): null
I/flutter ( 1660): null
I/flutter ( 1660): CB-SDK: : [getReadDeliveredWidget] sent
I/flutter ( 1660): null
I/flutter ( 1660): null
I/flutter ( 1660): CB-SDK: : [getReadDeliveredWidget] sent
I/flutter ( 1660): null
I/flutter ( 1660): null
I/flutter ( 1660): CB-SDK: : [getReadDeliveredWidget] sent
I/flutter ( 1660): null
I/flutter ( 1660): null
I/flutter ( 1660): CB-SDK: : [getReadDeliveredWidget] sent
I/flutter ( 1660): null
I/flutter ( 1660): null
I/flutter ( 1660): CB-SDK: : [getReadDeliveredWidget] sent
I/flutter ( 1660): markAsReadIfNeed message= {_id: 61f7d48fdf36f26e62950ff9, chat_dialog_id: 61dec100ae436100117f671f, message: fff, date_sent: 1643631759, sender_id: 5323391, recipient_id: 5323414, read_ids: [5323391, 5323414], delivered_ids: [5323391, 5323414], views_count: 0, attachments: [], id: null, created_at: 2022-01-31T12:22:39.000Z, updated_at: 2022-01-31T12:22:50.000Z, edited_at: null}, isOpponentMsgRead= true
I/flutter ( 1660): markAsReadIfNeed message= {_id: 61f7d443df36f26e62950ff8, chat_dialog_id: 61dec100ae436100117f671f, message: fff, date_sent: 1643631683, sender_id: 5323391, recipient_id: 5323414, read_ids: [5323391, 5323414], delivered_ids: [5323391, 5323414], views_count: 0, attachments: [], id: null, created_at: 2022-01-31T12:21:23.000Z, updated_at: 2022-01-31T12:21:48.000Z, edited_at: null}, isOpponentMsgRead= true
I/flutter ( 1660): markAsReadIfNeed message= {_id: 61f7ccbcdf36f26e62950ff7, chat_dialog_id: 61dec100ae436100117f671f, message: fff, date_sent: 1643629756, sender_id: 5323391, recipient_id: 5323414, read_ids: [5323391, 5323414], delivered_ids: [5323391, 5323414], views_count: 0, attachments: [], id: null, created_at: 2022-01-31T11:49:16.000Z, updated_at: 2022-01-31T11:49:27.000Z, edited_at: null}, isOpponentMsgRead= true
[log] ---Xmpp Sending:---
[log] <message id="TPHNVNPTA" type="chat" to="5323391-5842@chat.connectycube.com"><displayed xmlns="urn:xmpp:chat-markers:0" id="61f7debedf36f26e62950ffa"/><extraParams xmlns="jabber:client"><dialog_id>61dec100ae436100117f671f</dialog_id></extraParams></message>
[log] ---Xmpp Receiving:---
[log] <r xmlns='urn:xmpp:sm:3' />
[log] ---Xmpp Sending:---
[log] <a xmlns="urn:xmpp:sm:3" h="11"/>
[log] ---Xmpp Sending:---
[log] <r xmlns="urn:xmpp:sm:3"/>
[log] ---Xmpp Receiving:---
[log] <a xmlns='urn:xmpp:sm:3' h='17'/>
[log] D/[StreamManagementModule]: Delivered: TPHNVNPTA

**Comment by zombie6888** [comment]
oops i think the problem is that i didn't rebuild second emulator. Now it works. I recieved my custom prop. Thank you for feedback

**Comment by TatankaConCube** [comment]
if your issue was resolved, please close this ticket
