### ISSUE TITLE
hey when i added  my credentials it wont work

### ISSUE THREAD

**Issue by pyanishjain** [ConnectyCube/connectycube-flutter-samples#19]

**Comment by pyanishjain** [comment]
it gives me loggin error Something went wrong during login to ConnectyCube

**Comment by CubeRomanMagellan** [comment]
Hello! Did you look at similar [issue](https://github.com/ConnectyCube/connectycube-flutter-samples/issues/4)?

**Comment by pyanishjain** [comment]
issuse still not solved

**Comment by CubeRomanMagellan** [comment]
Did you create new users in admin panel and set them in config? If you still have issue, please provide us logs from flutter console to better understanding your issue.

**Comment by TatankaConCube** [comment]
Seems there is no much activity out there. Closing the issue as stale. If it’s still actual - please raise a new one.
