### ISSUE TITLE
This app is using a deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by 2i2i** [ConnectyCube/connectycube-flutter-samples#190]
**Specify the sample to which the issue belongs (use [x]):**
[] Chat sample
[x] P2P Call sample
[] Conference Call sample

**Platform (use [x])**
[] Android
[] iOS
[] macOS
[] Windows
[x] Web

**Device info**
Manufacture: apple
Model: macOS
OS version: 12.0.1

**Describe the bug:**

after git clone, flutter pub get inside p2p_call_sample, flutter run gives the following error (and does not run).

imi:2022-02-03 22:01:41:p2p_call_sample $ flutter run
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Warning
──────────────────────────────────────────────────────────────────────────────
Your Flutter application is created using an older version of the Android
embedding. It is being deprecated in favor of Android embedding v2. Follow the
steps at

https://flutter.dev/go/android-project-migration

to migrate your project. You may also pass the --ignore-deprecation flag to
ignore this check and continue with the deprecated v1 embedding. However,
the v1 Android embedding will be removed in future versions of Flutter.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
The detected reason was:

  /Users/imi/Documents/connectycube-flutter-samples/p2p_call_sample/android/app/src/main/AndroidManifest.xml uses
  `android:name="io.flutter.app.FutterApplication"`
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This app is using a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to migrate this app to the V2 embedding.
Take a look at the docs for migrating an app:
https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects
The plugin `connectycube_flutter_call_kit` requires your app to be migrated to the Android embedding v2. Follow the
steps on https://flutter.dev/go/android-project-migration and re-run this command.

**Steps to Reproduce:**
1.  git clone ...
2.  cd p2p_call_sample
3. flutter pub get
4. flutter run

**Logs:**
```
log here
```
or
[Gist log](https://gist.github.com/)

**Actual result:**

**Expected behavior:**

**Additional info**

**Comment by TatankaConCube** [comment]
updated in the latest version, please check it
