### ISSUE TITLE
Android and iOS build error RTCDataChannelNative

### ISSUE THREAD

**Issue by kaciula** [ConnectyCube/connectycube-flutter-samples#193]
**Specify the sample to which the issue belongs (use [x]):**
[] Chat sample
[x] P2P Call sample
[] Conference Call sample

**Platform (use [x])**
[x] Android
[x] iOS
[] macOS
[] Windows
[] Web

**Device info**
All

**Describe the bug:**

I try to build the P2P code sample on Android and iOS but I get the following error:

Error: The non-abstract class 'RTCDataChannelNative' is missing implementations for these members:
../…/native/rtc_data_channel_impl.dart:16
 - RTCDataChannel.bufferedAmount
 - RTCDataChannel.id

Here is the output of Flutter doctor:

[✓] Flutter (Channel stable, 2.10.2, on macOS 11.6 20G165 darwin-arm, locale en-RO)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.65.2)
[✓] Connected device (6 available)
[✓] HTTP Host Availability

**Comment by TatankaConCube** [comment]
try to do 
```bash
flutter clean
flutter pub get
cd ios 
pod update
cd ..
```

then try to build the ios

**Comment by TatankaConCube** [comment]
one more question: which version of the `flutter-webrtc` lib do you use, integrated into our SDK or another changed via overriding dependencies?

**Comment by kaciula** [comment]
I've done the steps you mentioned on ios and I still get the same build error.

I do notice however that the Podfile.lock changed the webrtc pod version:

- flutter_webrtc (0.7.1):
    - Flutter
    - Libyuv (= 1703)
    - WebRTC-SDK (= 97.4692.02)
    
 Keep also in mind that I get the same build error for Android also.

**Comment by TatankaConCube** [comment]
@kaciula try to override the current version with the latest by adding into your `pubspec.yaml` next code:
```yaml
dependency_overrides:
  flutter_webrtc: 0.8.5
```
then do actions from this [post](https://github.com/ConnectyCube/connectycube-flutter-samples/issues/193#issuecomment-1087268261) and try to build your app again

**Comment by aytunch** [comment]
I think the problem comes from web_rtc
https://github.com/flutter-webrtc/flutter-webrtc/issues/899
@TatankaConCube can you update the dependency so we don't have to use dependency_overrides?

**Comment by TatankaConCube** [comment]
I agree with you concerning the `dependency_overrides`, I just asked you to check this temp workaround. If it works we will release a new version with updated dependencies.

**Comment by aytunch** [comment]
@TatankaConCube This solved it for our case:
```
dependency_overrides: 
  webrtc_interface: 1.0.2
```

**Comment by kaciula** [comment]
@TatankaConCube Using dependency_overrides made the build work. 

On a different note, do we need to have a Firebase project to test the sample functionality? I see you are using the google-services plugin and I need to provide a google-services.json file. I've disabled the plugin but I see that I cannot establish a call between 2 users using the sample.

**Comment by TatankaConCube** [comment]
@kaciula yes, for mobile platforms we use push notifications for notifying opponents about an incoming call. You can comment this [line](https://github.com/ConnectyCube/connectycube-flutter-samples/blob/master/p2p_call_sample/lib/src/managers/call_manager.dart#L85) for showing the Incoming call screen when app is open.
