### ISSUE TITLE
Chat sample build error. firebase_options.dart missing file

### ISSUE THREAD

**Issue by kaciula** [ConnectyCube/connectycube-flutter-samples#194]
I cannot build the chat sample app. 

Target of URI doesn't exist: 'firebase_options.dart'.

Can you please update your samples so that they can be successfully built and run out of the box?

**Comment by TatankaConCube** [comment]
No, it is the config file related to **your** firebase account. See this short [guide](https://github.com/ConnectyCube/connectycube-flutter-samples/tree/master/chat_sample#configure-push-notifications) how to generate it
