### ISSUE TITLE
ConferenceRole.LISTENER

### ISSUE THREAD

**Issue by hasanvlt** [ConnectyCube/connectycube-flutter-samples#195]
When i use ConferenceRole.Listener in callSession.joinDialog ...
OnRemoteStreamReceived Event not work
Can you help me plz
Thank you

**Comment by TatankaConCube** [comment]
I will modify the sample and check, then back to you with an answer.

**Comment by hasanvlt** [comment]
> I will modify the sample and check, then back to you with an answer.

Hello
Any new please?

**Comment by TatankaConCube** [comment]
we found some issues on the SDK side, we are investigating them, will notify you later

**Comment by hasanvlt** [comment]
> 

Thank you

**Comment by TatankaConCube** [comment]
@hasanvlt today we hawe release new version with needed fixes, try use it.

pay attention, for getting the remote stream of publisher you should subscribe on it first.

**Comment by hasanvlt** [comment]
> @hasanvlt today we have released a new version with needed fixes, try use it.
> 
> pay attention, for getting the remote stream of publisher you should subscribe on it first.

Thank you
I'll try now

**Comment by hasanvlt** [comment]
Thank you
I'll try now

**Comment by hasanvlt** [comment]
> 

Hello
Plz what you mean subscribe on it first?

**Comment by hasanvlt** [comment]
> @hasanvlt today we have released a new version with needed fixes, try use it.
> 
> pay attention, for getting the remote stream of publisher you should subscribe on it first.

Hello
Plz what you mean subscribe on it first?

**Comment by TatankaConCube** [comment]
@hasanvlt I mean [this](https://developers.connectycube.com/flutter/videocalling-conference?id=subscribeunsubscribe) API

**Comment by hasanvlt** [comment]
> @hasanvlt I mean [this](https://developers.connectycube.com/flutter/videocalling-conference?id=subscribeunsubscribe) API

Put subscribeyopublisher(id publisher or id subscribe) in onPublishersReceived event 
Or 
In another side after joinDialog (watcher)?

**Comment by TatankaConCube** [comment]
you can use both these callbacks for it 

if you have no empty list of publishers in the callback `joinDialog`, you can subscribe there

**Comment by hasanvlt** [comment]
> you can use both these callbacks for it
> 
> if you have no empty list of publishers in the callback `joinDialog`, you can subscribe there

Thank you a lot 
I'll try it

**Comment by hasanvlt** [comment]
> you can use both these callbacks for it
> 
> if you have no empty list of publishers in the callback `joinDialog`, you can subscribe there

Its work
Thank you
Another question 
How convert from listener to publisher in live
