### ISSUE TITLE
Screen sharing does not work on Android 11 with targetSdkVersion 31

### ISSUE THREAD

**Issue by kaciula** [ConnectyCube/connectycube-flutter-samples#196]
**Specify the sample to which the issue belongs (use [x]):**
[] Chat sample
[x] P2P Call sample
[] Conference Call sample

**Platform (use [x])**
[x] Android 11
[] iOS
[] macOS
[] Windows
[] Web

If I update the sample to use targetSdkVersion 31 for Android and I try to enable screen sharing using a phone with Android 11, I get a crash with the following error:

java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION

Please advise on how to make it work with latest Android version. We need to use the latest targetSdkVersion otherwise we cannot publish the app on Google Play.

**Comment by TatankaConCube** [comment]
it requires some investigation on our side, will back later

**Comment by TatankaConCube** [comment]
@kaciula for fixing this issue you should do next:
- connect the `flutter_background` plugin to your project using 
```yaml
    flutter_background: ^1.1.0
```

- add to the file `p2p_call_sample/android/app/src/main/AndroidManifest.xml` to section `manifest` next permissions:
```xml
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>
    <uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS" />
```

- add to the file `p2p_call_sample/android/app/src/main/AndroidManifest.xml` to section `application` next srvice
```xml
        <service android:name="de.julianassmann.flutter_background.IsolateHolderService"
            android:foregroundServiceType="mediaProjection"
            android:enabled="true"
            android:exported="false"/>
```

- add next function to the file `p2p_call_sample/lib/src/conversation_screen.dart`:
```dart
Future<bool> initForegroundService() async {
  final androidConfig = FlutterBackgroundAndroidConfig(
    notificationTitle: 'P2P Calls sample',
    notificationText: 'Screen sharing in in progress',
    notificationImportance: AndroidNotificationImportance.Default,
    notificationIcon: AndroidResource(
        name: 'ic_launcher_foreground',
        defType: 'drawable'),
  );
  return FlutterBackground.initialize(androidConfig: androidConfig);
}
```
- rewrite the method `_toggleScreenSharing` in the next way:
```dart
  _toggleScreenSharing() async {
    if (Platform.isAndroid) {
      var foregroundServiceFuture = _enableScreenSharing
          ? FlutterBackground.enableBackgroundExecution()
          : FlutterBackground.disableBackgroundExecution();

      bool hasPermissions = await FlutterBackground.hasPermissions;

      if (!hasPermissions) {
        await initForegroundService();
      }

      foregroundServiceFuture.then((_) {
        _callSession
            .enableScreenSharing(_enableScreenSharing)
            .then((voidResult) {
          setState(() {
            _enableScreenSharing = !_enableScreenSharing;
          });
        });
      });
    } else {
      _callSession.enableScreenSharing(_enableScreenSharing).then((voidResult) {
        setState(() {
          _enableScreenSharing = !_enableScreenSharing;
        });
      });
    }
  }
```

we will update our sample soon for integration this functionality

**Comment by TatankaConCube** [comment]
then wait for our updates for the samples

**Comment by TatankaConCube** [comment]
@kaciula needed improvements were published to the `master` branch, try it now)))

**Comment by kaciula** [comment]
@TatankaConCube Thank you for the support. It now works properly.
