### ISSUE TITLE
Conference room for guests

### ISSUE THREAD

**Issue by kaciula** [ConnectyCube/connectycube-flutter-samples#198]
Is there support for guests in a conference room with the ConnectyCube SDK? 

If there is, could you please add a Flutter sample (or modify the conference sample) to show how to achieve this?

My specific usecase is the following: users of my app can share their screen with a support person to help them navigate the app. Ideally, the support person opens a conference room and just gives the user a code. Then the user uses the code inside the app to connect to that room as a guest and be able to share his screen. Is this doable?

**Comment by TatankaConCube** [comment]
for this feature, you can use the Conference calls feature from our SDK. If I understand your request correctly the flow can be next:
- support person creates a meeting and shares its id with a user (can be invisible using [System messages](https://developers.connectycube.com/flutter/messaging?id=system-messages) feature)
-  on the user side you will display only the 'Share screen' button;
- by clicking the 'Share screen' button the support person joins to meeting as ConferenceRole.LISTENER and user 
 joins to it as ConferenceRole.PUBLISHER;

> could you please add a Flutter sample (or modify the conference sample)

sorry, but we can't provide the ready solutions for all possible cases, we provide the main functionality and you can adapt it for your needs

**Comment by TatankaConCube** [comment]
No, you need a ConnectyCube user anyway. Your server can create it when creates your own user. You can invent some algorithm for the generation password, for example using login and some 'code salt'. On the front-end, your user will have the Connectycube login and password generated on the front-end and use them for login and performing required requests.
