### ISSUE TITLE
Push notifications issues

### ISSUE THREAD

**Issue by zombie6888** [ConnectyCube/connectycube-flutter-samples#199]
From yesterday we faced with problem related to push notifications. We were testing custom events and it worked before but now we don't get any notifications. It looks like there is no problem with subscriptions, but i found this error from admin interface logs: Error: getaddrinfo EMFILE [fcm.googleapis.com](http://fcm.googleapis.com/) : getaddrinfo EMFILE [fcm.googleapis.com](http://fcm.googleapis.com/). It looks like DNS issue. Also i noticed that some fcm events was missing in push notifications query admin interface and now links to logs are disabled 
![image](https://user-images.githubusercontent.com/7497489/163561613-837fdf21-10bd-4eae-902d-a1d45fac727f.png)

Can you confirm, if it's a temproary issue on your server side or look into this?

**Comment by TatankaConCube** [comment]
sorry, I forgot to answer you after consultation with the back-end team, now it should work, check, please

**Comment by zombie6888** [comment]
thanks, fixed!
