### ISSUE TITLE
Cannot make P2P call when switching from WIFI to Mobile data or vice versa

### ISSUE THREAD

**Issue by rdhillbb** [ConnectyCube/connectycube-flutter-samples#20]
**Specify the sample to which the issue belongs (use [x]):**
[ X] P2P Call sample
[ ] Conference Call sample

**Platform (use [x])**
[ X] Android
[ ] iOS

**Device info**
Manufacture: Oppo :  Realme
Model: Model Oppo: CPH2063 : Realme: RMX2061Plus 6
OS version:Oppo: Version 9 Android: RealMe Android Version 10

**Describe the bug:**
After the P2P app is started and user is logged in, switching to either WIFI or Mobile data, A P2P call cannot be established.

**Steps to Reproduce:**
1. Activate both WIFI and Mobile Data on Each phone
2.Login with separate User IDs on each phone.
3. Initiate P2P call. A connection can be made.
4. On one phone, deactivate WIFI. Mobile data is now active. Important: Do not stop the P2P application.
5. Bring up P2P application. Initiate a call to the other phone. A P2P call cannot be established.
6. Stop application and re-login.
7. Initiate call. A call can be established. One phone on Mobile Data while the other is on WIFI.

Should not have to stop the application and restart. 
**Logs:**
```
log here
```
or
[Gist log](https://gist.github.com/)

**Actual result:**

**Expected behavior:**

**Additional info**

**Comment by TatankaConCube** [comment]
Hello @rdhillbb. We are working on this problem now. In next version we will add simple reconnection manager to SDK and provide API for user to organise own Reconnection manager.

**Comment by rdhillbb** [comment]
Thank you

**Comment by TatankaConCube** [comment]
today we released a new version, please find out our [documentation](https://developers.connectycube.com/flutter/messaging?id=reconnection) to organize reconnection logic after changing the network type

**Comment by rdhillbb** [comment]
Thank you will test it out

**Comment by rdhillbb** [comment]
I was not able to test as I received java errors. I open a new issue.

**Comment by TatankaConCube** [comment]
@rdhillbb any updates here?

**Comment by rdhillbb** [comment]
The issue has gone away. I  tested with the updated SDK. . I did provide an update on github on my findings. All good.

On September 4, 2020 at 11:05 PM, TatankaConCube <notifications@github.com> wrote:






@rdhillbb any updates here?

**Comment by rdhillbb** [comment]
Closing out.
