### ISSUE TITLE
Convert from Listener to Publisher in Live

### ISSUE THREAD

**Issue by hasanvlt** [ConnectyCube/connectycube-flutter-samples#201]
Hello
Conference meeting..
How convert from Listener to Publisher 
Then from Publisher to Listener in live
Thank you

**Comment by TatankaConCube** [comment]
You can do it by leaving the room an join again with needed role (listener or publisher)

**Comment by hasanvlt** [comment]
> You can do it by leaving the room an join again with needed role (listener or publisher)

Ok thank you very much
