### ISSUE TITLE
Do not have push notification subscriptions

### ISSUE THREAD

**Issue by quangvinhvux** [ConnectyCube/connectycube-flutter-samples#205]
P2P Call sample
Flutter Web
Hi guys, I'm trying to make a video call from user to another user and i getting this error. i have followed sample project, but it doesn't work on my Flutter Web project. 
do you guys have any suggestion to resolve this ?
Thank you very much for your contributions.
**Logs:**
https://api.connectycube.com/events
Request Method: POST
Status Code: 422 Unprocessable Entity
Request payload
{
  "event": {
    "id": null,
    "created_at": null,
    "updated_at": null,
    "notification_type": "push",
    "environment": "development",
    "message": "eyJtZXNzYWdlIjoiSW5jb21pbmcgVmlkZW8gY2FsbCIsImNhbGxfdHlwZSI6MSwic2Vzc2lvbl9pZCI6ImQzOWJiMzg0LTI4ZTMtNGNhNC1hNTQwLTIzNjUxYzRkYTViNCIsImNhbGxlcl9pZCI6NTgwMzk5MSwiY2FsbGVyX25hbWUiOjU4MDM5OTEsImNhbGxfb3Bwb25lbnRzIjoiNTgwMzk5MSIsImlvc192b2lwIjoxLCJzaWduYWxfdHlwZSI6InN0YXJ0Q2FsbCJ9",
    "user": {
      "ids": "5803991"
    }
  }
}

Response
{"errors":{"base":["Users with ids 5803991 do not have push notification subscriptions"]}}

**Comment by TatankaConCube** [comment]
looks like your opponent doesn't have the subscription for the push notifications. please follow the documentation on how to configure FCM for Web in the Flutter. in our [README.md](https://github.com/ConnectyCube/connectycube-flutter-samples/tree/master/chat_sample#configure-push-notifications) file we provide the short guide how to do this, but you can follow the official FCM documentation for getting more detailed guides. pay attention, we implemented the push notifications feature for all supported platforms (Android, iOS, macOS, Web) only in the Chat sample, but you can do it for the P2P Calls sample in a similar way.

**Comment by quangvinhvux** [comment]
hi @TatankaConCube i have added but got same errror.  what i have to do next?
Thank you for your support.
![Screen Shot 2022-05-12 at 10 39 42](https://user-images.githubusercontent.com/32142256/167987500-a81bf45f-dff6-46ea-ab11-eb761ce896d2.png)
![Screen Shot 2022-05-12 at 10 40 28](https://user-images.githubusercontent.com/32142256/167987505-a54ce351-41b5-4cd4-b5aa-b0cc9187cfa3.png)

**Comment by quangvinhvux** [comment]
hi @TatankaConCube I passed this issue and can send notification. 
now i get this issue when showCallNotification, do you have any suggestion? 
MissingPluginException(No implementation found for method showCallNotification on channel connectycube_flutter_call_kit.methodChannel)

**Comment by TatankaConCube** [comment]
the plugin [connectycube-flutter-call-kit ](https://github.com/ConnectyCube/connectycube-flutter-call-kit)still doesn't support the Web platform
