### ISSUE TITLE
Ar integreated

### ISSUE THREAD

**Issue by hasanvlt** [ConnectyCube/connectycube-flutter-samples#206]
Hello
I need to integreated ar (filter face etc..) with connectycube
How can do it please
Thank you

**Comment by TatankaConCube** [comment]
@hasanvlt  in our Flutter SDK, we have the method `replaceMediaStream(MediaStream)` which provides the possibility for replacing the original stream with the custom. You can modify the original stream and set it via this method. Unfortunately, we don't yet have the worked example for the required feature.
