### ISSUE TITLE
Ringtone not playing when ConnectycubeFlutterCallKit.showCallNotification is called from within the FirebaseMessaging.onBackgroundMessage

### ISSUE THREAD

**Issue by lifehetu** [ConnectyCube/connectycube-flutter-samples#208]
When the App is in the running state, and the custom ringtone, kept in app/src/main/res/raw folder plays when ConnectycubeFlutterCallKit.showCallNotification(callEvent); is called.

ConnectycubeFlutterCallKit.instance.init(
        onCallAccepted: _onCallAccepted,
        onCallRejected: _onCallRejected,
        ringtone: 'custom_ringtone',
        icon: 'lifehetu_logo',
        color: '#07711e');

But when the Flutter App is in the background state, the ringtone does not play when Connecticube updateConfig is called from within the FirebaseMessaging.onBackgroundMessage method.

ConnectycubeFlutterCallKit.instance.updateConfig(
      ringtone: 'custom_ringtone', icon: 'lifehetu_logo', color: '#07711e');
How do I play my custom ringtone when Connecticube ConnectycubeFlutterCallKit.showCallNotification(callEvent); is invoked from within the firebase background handler method?

**Comment by prashantjdgit** [comment]
Any updates on this issue?

**Comment by CubeRomanMagellan** [comment]
check on latest sample and if issue still persists feel free to re-open.
