### ISSUE TITLE
Is Client Needed To Implement SSL Pinning? 

### ISSUE THREAD

**Issue by blackkara** [ConnectyCube/connectycube-flutter-samples#217]
I'm using connectycube sdk methods and requesting over http for custom objects. There are two things I am wondering

1. Does SDK use SSL pinning when requesting connectycube endpoints internally? 
2. As a client, should we use ssl pinning when requesting over http (for custom objects)?

**Comment by DaveLomber** [comment]
We do not use SSL pinning 

But at other side, we use HTTPS/TLS for any possible communication with backend

**Comment by blackkara** [comment]
Correct me if I understand the things wrong

That's okay the endpoint has HTTPS but is it enough to be only HTTPS to prevent MITM attacks?

To be more specific, in this [example](https://developers.connectycube.com/server/custom_objects?id=request-example) from the documentation, the curl converted to dart code

```
curl -X POST \
-H "CB-Token: <TOKEN>" \
-H "Content-Type: application/json" \
-d '{"full_name": "Nadine Collier", "age": "41", "job": "accountant", "country_of_birth": "Germany"}' \
https://api.connectycube.com/data/profile
```

so a possible custom object request

```
var headers = {
  'CB-Token': '<TOKEN>',
  'Content-Type': 'application/json',
};

var data = '{"full_name": "Nadine Collier", "age": "41", "job": "accountant", "country_of_birth": "Germany"}';

var url = Uri.parse('https://api.connectycube.com/data/profile');
var res = await http.post(url, headers: headers, body: data);
if (res.statusCode != 200) throw Exception('http.post error: statusCode= ${res.statusCode}');
```
Is it needed to use SSL pinning [(like ssl_pinning_plugin)](https://pub.dev/packages/ssl_pinning_plugin) at this point to be secure?

**Comment by DaveLomber** [comment]
having HTTPS is more than enough 

If you are very paranoidic regarding security - an SSL pinning can be added

**Comment by blackkara** [comment]
Thanks thats enough
