### ISSUE TITLE
Regarding the chat issue while 

### ISSUE THREAD

**Issue by kalyan5g6** [ConnectyCube/connectycube-flutter-samples#219]
While we are sending a link in a chat that is like (www.google.com) that text cannot be highlighting into the hyperlink. As we need this emergency for now please have a look on this and  update asap
<img width="469" alt="Screenshot 2022-10-04 at 10 44 59 AM" src="https://user-images.githubusercontent.com/101690096/193739886-eb519250-be34-4820-9f59-6eaea503338a.png">

**Comment by TatankaConCube** [comment]
@kalyan5g6 you can use [flutter_linkify](https://pub.dev/packages/flutter_linkify) or [linkwell](https://pub.dev/packages/[linkwell](https://pub.dev/packages/linkwell)) or other for recognising links in a text
