### ISSUE TITLE
Session problems

### ISSUE THREAD

**Issue by mlukovic** [ConnectyCube/connectycube-flutter-samples#22]
**Specify the sample to which the issue belongs (use [x]):**
[x ] P2P Call sample
[ ] Conference Call sample

**Platform (use [x])**
[ ] Android
[ x] iOS

**Describe the bug:**
We started integration of ConnectyCube SDK for Flutter in one of our products. But we have a serious issue with the chat/call sessions. After the user is logged in and the device is locked for more than 30 seconds, the SDK stop to provide events for incoming call sessions. The chat stops working as well. I’ve tried to re-log in the user, after app becomes active again, but this fix didn’t work for me.

**Steps to Reproduce:**

1. Run the example on iPhone
2. Login with one of the user
3. Lock the iPhone for 1 minute
4. Start a call session from other device
5. Unlock the iPhone 

**Actual result:**
Won’t receive the incoming call
**Expected behavior:**
Receive incoming call

**Additional info**
I also find next problem. If the user is re-logged in it will not receive the incoming call. Step to reproduce:
1. Run the example on device
2. Login with one of the user
3. Logout and then login again with the same user
4. Start a call session from other device
5. The first device doesn’t receive the incoming call

I think the problem in both situations is the same.
Can you provide us a solution for this problem(s)?

**Comment by TatankaConCube** [comment]
we are working on this problem now, we will release new version in near few days

**Comment by mlukovic** [comment]
Hi @TatankaConCube, tnx for quick response. Is the issue in ConnectyCube SDK or in example?

**Comment by TatankaConCube** [comment]
jus now we released a new version of our SDK, please find out our [documentation](https://developers.connectycube.com/flutter/messaging?id=reconnection) to organize reconnection logic in your app

**Comment by mlukovic** [comment]
@TatankaConCube We have just tested it with 0.4.0 version and it seams the issue is resolved. Thank you so much!

**Comment by mlukovic** [comment]
@TatankaConCube We have just tested it with 0.4.0 version and it seams the issue is resolved. Thank you so much!
