### ISSUE TITLE
Destroy session token

### ISSUE THREAD

**Issue by quangvinhvux** [ConnectyCube/connectycube-flutter-samples#221]
hi ConnectyCube,
I have tried to call deleteSessionsExceptCurrent function but got 404, how I can destroy all sessions token?
HttpException: E_ROUTE_NOT_FOUND: Route not found DELETE /session/list

**Comment by TatankaConCube** [comment]
@quangvinhvux the server-side team deprecated and deleted this API, we will do the same in the SDK soon. For now available deleting only the current session via `deleteSession`
