### ISSUE TITLE
Not Received Push Notifications On Production

### ISSUE THREAD

**Issue by jostney** [ConnectyCube/connectycube-flutter-samples#223]
```
  CreateSubscriptionParameters parameters = CreateSubscriptionParameters();
  bool isProduction = kIsWeb ? true : bool.fromEnvironment('dart.vm.product');
  parameters.environment = isProduction ? CubeEnvironment.PRODUCTION : CubeEnvironment.DEVELOPMENT;
 
  if (Platform.isAndroid) {
    parameters.channel = NotificationsChannels.GCM;
    parameters.platform = CubePlatform.ANDROID;
    parameters.bundleIdentifier = Environment.packageName();
  } else if (Platform.isIOS) {
    parameters.channel = NotificationsChannels.APNS;
    parameters.platform = CubePlatform.IOS;
    parameters.bundleIdentifier = Environment.packageName();
  }

  String? deviceId = await PlatformDeviceId.getDeviceId;
  parameters.udid = deviceId;
  parameters.pushToken = pushToken;

  var subscriptionResult = await createSubscription(parameters.getRequestParameters());
```

My app receives notifications if it's marked 'development',  but not working if marked as 'production'. 

In production mode,  i am able to get push token and create subscription to Connectycube server successfully, but cant receive notifications. 

If i try send a push notification(like from Connectycube dashboard), notifications not receive... And `getSubscriptions()` return empty.  I repeated this so many times, and same thing happening

1. `createSubscription(...)` works successfully
2. `getSubscriptions()` returns NOT empty
3. Try sending push notification
4. `getSubscriptions()` returns empty (Why ??)

What's happening after trying notification ? Why the subscription get deleted ?? 

[----> YOU CAN WATCH IT <----](https://youtu.be/P-i2X2msplc)

**Comment by TatankaConCube** [comment]
@jostney  do you reproduce it on iOS? The iOS platform has some features when you build your app via Xcode. The system returns true on `bool.fromEnvironment('dart.vm.product')` when building the `Release` build in Xcode but returns the same token with the `Development` build. You should use `Archive` for building a Production app for iOS. 

> Why the subscription get deleted ??

It happens when you created the Production subscription with a Development token or vice-versa. The server tries to send the request to Apple but gets the error and deletes the wrong subscription. This situation is actual for the iOS platform only. For Android server just sends two events on Production and Development tokens.

**Comment by jostney** [comment]
To make guaranteed i hardcoded the environment;

` parameters.environment = CubeEnvironment.PRODUCTION;`

So no way to set the environment as `development` by mistake, but same things happening...

This is how the subscription model is look

<img width="547" alt="Screen Shot 2022-10-18 at 05 43 05" src="https://user-images.githubusercontent.com/108373490/196324042-7ad2d3b7-fd6c-4133-a1f1-150c42c84100.png">

And this is how the certificate look
<img width="685" alt="Screen Shot 2022-10-18 at 05 49 13" src="https://user-images.githubusercontent.com/108373490/196324251-ec250a0d-f870-4df0-b44a-142b7319e91e.png">

The bundle identifier is correct on both subscription and certificate. But why connectycube consider it development ? 

if i set this ` parameters.environment = CubeEnvironment.DEVELOPMENT;` then it works !

**Comment by TatankaConCube** [comment]
The reason is that I have described before - the system returns the Development token in both cases (Debug and release build). For getting the Production token you should build the Archive using Xcode tools.

**Comment by jostney** [comment]
@TatankaConCube It's worked via archiving ! 

But please describe why the below configuration didn't work. Is that ` "flutterMode": "release"` buggy ? 

    {
            "name": "[PROD-RELEASE] Kipyo",
            "request": "launch",
            "type": "dart",
            "args": [
                "--flavor",
                "production"
              ],
              "flutterMode": "release"
        }

**Comment by TatankaConCube** [comment]
> Is that "flutterMode": "release" buggy ?

I'm not sure is this bug or feature, but I met it while working with the push notifications in the Flutter iOS projects.

**Comment by jostney** [comment]
Thanks for support @TatankaConCube. Closing this
