### ISSUE TITLE
About Last Request At field. Seems Not Working 

### ISSUE THREAD

**Issue by jostney** [ConnectyCube/connectycube-flutter-samples#226]
Is the` Last Request At ` field working currently ? 

I saw this field in `User` table of ConnectyCube Admin Panel but field is empty even my users are active and requesting connectycube sdk/api. 

And no information about this field on documents. How this field works @TatankaConCube ?

**Comment by TatankaConCube** [comment]
@jostney I redirected your question to the back-end team, will wait theirs answer.

**Comment by TatankaConCube** [comment]
they promised to fix it soon

**Comment by jostney** [comment]
Where it will be announced ? Here or cc documentation ?

**Comment by TatankaConCube** [comment]
@jostney they already have pushed the fix today

**Comment by jostney** [comment]
@TatankaConCube  working!

Closed.
