### ISSUE TITLE
While we are recieving the chat from a person. In a particular chat list space we need to display the unread messages count on a particular chat card. when the messages are recieved from the another user we need to display the count . I have read the document but i am failed to implement this Can anyone please look into this  

### ISSUE THREAD

**Issue by KalyanVeeravalli** [ConnectyCube/connectycube-flutter-samples#227]
**Specify the sample to which the issue belongs (use [x]):**
[] Chat sample
[] P2P Call sample
[] Conference Call sample

**Platform (use [x])**
[] Android
[] iOS
[] macOS
[] Windows
[] Web

**Device info**
Manufacture: 
Model: 
OS version:

**Describe the bug:**

**Steps to Reproduce:**
1. 
2.
3.
4.

**Logs:**
```
log here
```
or
[Gist log](https://gist.github.com/)

**Actual result:**

**Expected behavior:**

**Additional info**

**Comment by jostney** [comment]
If i understood,  you asking how to show unread messages count when displaying dialogs.

In `CubeDialog` object there is a field `unreadMessageCount`. 

Maybe this is what you want.

**Comment by TatankaConCube** [comment]
@KalyanVeeravalli @jostney our SDK has the method `getUnreadMessagesCount()` it returns the map where the `dialogId` is key and the `unreadCount` is the value.
