### ISSUE TITLE
Is there any behaviour change about login on server side ?

### ISSUE THREAD

**Issue by jostney** [ConnectyCube/connectycube-flutter-samples#228]
@TatankaConCube @DaveLomber 

If I log in two times consecutively, the first login succeeds but the second fails with the `user not found` error message.

In my initial page(like splash screen), I retrieve the stored username and password and then make login (if there is a previously logged-in user, then the app uses his username and password otherwise, the app goes to the login page)

Until yesterday, I was able to have successful attempts consecutively (even though I restarted the app lots of times)

I am absolutely sure that the server-side changed behavior.

**Comment by TatankaConCube** [comment]
@jostney could you please provide the data required in templates, at least provide the logs with the first login in the next logins.
