### ISSUE TITLE
Speaker phone disabled by default and too much phone echoing

### ISSUE THREAD

**Issue by raj457036** [ConnectyCube/connectycube-flutter-samples#230]
**Specify the sample to which the issue belongs (use [x]):**
[] Chat sample
[*] P2P Call sample
[] Conference Call sample

**Platform (use [x])**
[] Android
[*] iOS
[] macOS
[] Windows
[] Web

**Device info**
Manufacture: Apple
Model: Iphone 11, 12, 13 Pro, 13 Pro Max
OS version: 16.0, 16.1

**Describe the bug:**

We are experiencing two issues first when call connects earpiece is enabled by default instead of speaker phone.

if we enable speaker phone by calling `callSession.enableSpeakerphone(enable);` on both the ends. we start to experience too much **phone echoing** if either of the participant mute themself, echo vanishes completely. 

The second one is only happening when calling ios to ios. 

if you need the logs let me know!

**Steps to Reproduce:**
1. 
2.
3.
4.

**Logs:**
```
log here
```
or
[Gist log](https://gist.github.com/)

**Actual result:**

**Expected behavior:**

**Additional info**

**Comment by TatankaConCube** [comment]
We made few a little changes to the audio in the new version. We will publish it in a few days.

**Comment by raj457036** [comment]
ohkay thanks

**Comment by prashantjdgit** [comment]
> We made few a little changes to the audio in the new version. We will publish it in a few days.
any updates on this issue?

**Comment by TatankaConCube** [comment]
We have released all planed features, please try the latest version
