### ISSUE TITLE
Microphone gets cut off while on the call when device goes to sleep

### ISSUE THREAD

**Issue by MrunalrajRedij** [ConnectyCube/connectycube-flutter-samples#232]
**Specify the sample to which the issue belongs (use [x]):**
[] P2P Call sample

**Platform (use [x])**
[] Android

**Device info**
Manufacturer: Samsung, Redmi, Micromax IN (We tested on wide range of devices same issue)
OS version: android 9 to android 12.

**Describe the bug:**
While on the call, microphone access gets cut off after a few seconds of the device going to sleep. You can hear other people but other person can't hear you.

**Steps to Reproduce:**
1. Start call between any users
2. Either wait till the device goes to auto sleep (due to inactivity) or manually sleep the device by pressing the power button.
3. After a few seconds other person on the call will be unable to hear you.

**Logs:**
Didn't notice any particular error in the logs. It was producing logs the same as when the microphone was working.

**Actual result:**
Another person cant hear you. While you can hear another person.

**Expected behavior:**
Both people should be able to hear each other.

**Additional info**
To tackle this problem I added a wake-lock so the device will stay awake. And its working but the problem arises when a user manually puts device to sleep. After a few seconds microphone access gets cut off.

**Comment by MrunalrajRedij** [comment]
Is there any information/update on this issue? Its been a while since I opened the issue.

**Comment by TatankaConCube** [comment]
@MrunalrajRedij I'm investigating this issue, it looks like the issue is related to working the app in the background, and if the app is placed in the background for 30 seconds or more the system disables the camera and microphone for this app. I have a few ideas on how to avoid it and will back to you if found any workaround.

**Comment by MrunalrajRedij** [comment]
Thanks. Please keep me updated as "Calling" is one of the major feature our app delivers.

**Comment by TatankaConCube** [comment]
@MrunalrajRedij in my case the starting of the foreground service fixes the issue. You can add the `_ConversationCallScreenState` as a `WidgetsBindingObserver` for listening to the app lifecycle and star the Foreground service when the app moves to the background. For it add the `_ConversationCallScreenState` as the lifecycle listener in the callback `initState()`:
```dart
  @override
  void initState() {
    super.initState();

    // some code there

    WidgetsBinding.instance.addObserver(this);
  }
```
then implement the method `didChangeAppLifecycleState(AppLifecycleState state)`:
```dart
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    log("[didChangeAppLifecycleState] state: ${state.name}", TAG);
    if (_enableScreenSharing) return; // for screen sharing we manage it separately

    if (state == AppLifecycleState.paused) {
      startBackgroundExecution();
    } else {
      stopBackgroundExecution();
    }
  }
```

and don't forget to remove the observer after closing the screen:
```dart
  @override
  void deactivate() {
    super.deactivate();

    // some code there

    WidgetsBinding.instance.removeObserver(this);
  }
```

**Comment by MrunalrajRedij** [comment]
What is the function `startBackgroundExecution()` and `stopBackgroundExecution()` ? Other than that I got it.

**Comment by MrunalrajRedij** [comment]
You said start foreground service when app is in background. What code should be the written in that service?

**Comment by TatankaConCube** [comment]
https://github.com/ConnectyCube/connectycube-flutter-samples/blob/master/p2p_call_sample/lib/src/utils/platform_utils.dart#L23-L39

we already use it for starting the Screen sharing

**Comment by MrunalrajRedij** [comment]
Okay, got it. Will implement and let you know.

**Comment by MrunalrajRedij** [comment]
Done all of the steps. Still not working.

**Comment by TatankaConCube** [comment]
Hmm... Interesting... Have you implemented all requirements of the [`flutter_background`](https://pub.dev/packages/flutter_background) plugin? After adding the code above to our P2P Calls sample it started working in the background without any problem.

**Comment by MrunalrajRedij** [comment]
For some reason was not using this permission
    `<uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS" />`
After adding the permission it works fine.
Will test it more thoroughly and with different versions. Will close the issue then. Thanks.

**Comment by MrunalrajRedij** [comment]
Just a question. (Rare scenario) If user has denied permission for **bg_service**. And since asking for permission is coded in `startBackgroundExecution();` So If the app is asking for permission when device goes to `paused `state. There will be no use since user can't see the permission as device screen is off. 
What If I call `startBackgroundExecution();` at start of the call? This will ensure that user know that permission is asked. And I don't have to check for **paused** or **inactive state**. I can just `stopBackgroundExecution(); ` when screen deactivates.
Will it work or it will have issues that I am unaware of?

**Comment by TatankaConCube** [comment]
In my opinion, you can ask permission after the first start of the application and the second time (if wasn't provided) before the call. Yes, you can call the `startBackgroundExecution()` immediately after starting the call it will notify a user about a call that continues in the background at any app's lifecycle.

**Comment by MrunalrajRedij** [comment]
Okay. Thanks for your support.
