### ISSUE TITLE
Push notification not working as intended for "fixed_date"

### ISSUE THREAD

**Issue by MrunalrajRedij** [ConnectyCube/connectycube-flutter-samples#233]
I want to create push notifications for a specific date in the future.
I have followed the steps from docs, that is to:
For `createEvent();` method:-
- Set `params.event_type = "fixed_date"`
- Set `params.date = $timestamp_in_seconds`

**Question: Doc. only says timestamp in seconds to be placed in the event[date]. Can you elaborate on what to place here?** 
> I didn't understand it, so I tried  bunch of stuff such as _unix timestamp_, _millisecondsSinceEpoch_ and then converting it to seconds, etc

The push notification is working but it sends a notification as soon as I hit send. I want to get a notification at a specified time.
I have also set up server API for the same. It also gave similar results. That is to send push notification as `one_shot` not on specified time.

**Comment by MrunalrajRedij** [comment]
It would be really helpful if you bring back this feature. It will solve our major problem. Thanks

**Comment by TatankaConCube** [comment]
how do you use it? could you please describe your feature?

**Comment by MrunalrajRedij** [comment]
Let's say there are two users **_A_** and **_B_**
**_A_** has three of the timeslots available. Selecting one of them 
should trigger a schedule notification for **_B_** five minutes prior to selected timeslots.

Example: **_A_** has selected the timeslot `4:05 PM` three days from now then user **_B_** should receive a notification at `4:00 PM` from three days from now.

**Comment by TatankaConCube** [comment]
As a workaround, you can write your own script on Node JS and start a cronjob for launching this script.
