### ISSUE TITLE
Chat Notifications Not Working On iOS ?

### ISSUE THREAD

**Issue by jostney** [ConnectyCube/connectycube-flutter-samples#240]
Firstly, 

- All tests run on real devices, NO simulators/emulators.
- And we are run on production, so it's ARHCIVE of the app.
- Our test clients receive app from TestFlight 

Our iOS app able to

- Receive notification if other client send manuel notification like below
```
Future<List<CubeEvent>> sendLikeNotificationConnectycube(String username, int likedId) {
  final CreateEventParams params = CreateEventParams();

  params.parameters = {
    'message': '❤️ $username',
    'event': 'like',
  };

  params.notificationType = NotificationType.PUSH;
  const bool isProduction = bool.fromEnvironment('dart.vm.product');
  params.environment = isProduction ? CubeEnvironment.PRODUCTION : CubeEnvironment.DEVELOPMENT;
  params.usersIds = [likedId];

  return createEvent(params.getEventForRequest());
}
```
- Receive notification if it's sent from ConnectyCube dashboard
<img width="621" alt="image" src="https://user-images.githubusercontent.com/108373490/216593647-abf6f771-8514-4807-9f7d-2577b5e9bc82.png">

BUT,  our app does not receive chat notification if any other client send chat message.

This is Offline Notifications page
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/108373490/216595362-cf91bfbf-eb62-4133-8867-ffb1eac460b7.png">

**Comment by TatankaConCube** [comment]
@jostney have you tried both `PUSH TYPE` (**alert** and **background**) from the `IOS SETTINGS`?

**Comment by jostney** [comment]
I tried it, and it's working !

Wondering and querying those parameters. Why this is worked for now, while `background` didn't ? 

And notifications are didn't group by conversation. I have just combined/tried/tested `BODY TEMPLATES`. All notifications above from same chat. So it show a new notification per new chat message. 

![image](https://user-images.githubusercontent.com/108373490/216618456-09f44bf3-2c66-4206-9e76-3699c747e83d.png)

**Comment by jostney** [comment]
The weird thing is, before setting to `ALERT`, the android clients are already able to receive notifications.

Now android still able to receive but the situation is weird, why 'ALERT' made this possible for iOS side ?

**Comment by TatankaConCube** [comment]
https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns there is the official Apple documentation, please follow it for a better understanding of the flags meaning.
I'm not well-experienced with the iOS platform but I think that you should listen to the **background** notifications in the `didReceiveRemoteNotification` and update your app in the background if needed (including manually showing the local notifications), more [there](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_background_updates_to_your_app).

**Comment by jostney** [comment]
@TatankaConCube I'll review links. Thanks for responses

**Comment by jostney** [comment]
What about grouping notifications ? How does `connectycube-flutter-samples` show notifications from same conversation ? 

I did not get how to group them ?

- ConnectyCube SDK ?
- ConnectyCube Dashboard ?
