### ISSUE TITLE
Android build failure,

### ISSUE THREAD

**Issue by prashantjdgit** [ConnectyCube/connectycube-flutter-samples#245]
**Specify the sample to which the issue belongs (use [x]):**
[] Chat sample
[x] P2P Call sample
[] Conference Call sample

**Platform (use [x])**
[x] Android
[] iOS
[] macOS
[] Windows
[] Web

**Describe the bug:**
Android build failure,
Could not find android-104.5112.05.aar (com.github.webrtc-sdk:android:104.5112.05).

**Comment by TatankaConCube** [comment]
Have you done `flutter pub get` before building the android app? Could you please provide the steps on how do you build the android app?

**Comment by prashantjdgit** [comment]
> > Have you done `flutter pub get` before building the android app? Could you please provide the steps on how do you build the android app?
> 
> yes , we followed all the steps mentioned in documentation of your sdk (ConnectyCubeSdk)

**Comment by TatankaConCube** [comment]
could you please provide a full build log? I switched to the master branch, did the next commands 
`flutter clean`
`flutter pub get`
`flutter run -d b2ef296f` where the `b2ef296f` is the id of the android device

and the app has successfully built and run on the device

**Comment by TatankaConCube** [comment]
looks like this thread is related to your issue too https://github.com/ConnectyCube/connectycube-flutter-sdk-releases/issues/87

try the provided solutions from it
