### ISSUE TITLE
CubeChatConnection: Chat connection ForcefullyClosed

### ISSUE THREAD

**Issue by quangvinhvux** [ConnectyCube/connectycube-flutter-samples#247]
Hi,
can you please help to check CubeChatConnection issue, it auto ForcefullyClosed after login , i'm using version 2.4.0
this is my implementation: 

```
Future<CubeUser> signInCube(String token) {
    if (CubeSessionManager.instance.activeSession?.user != null) {
      var user = CubeSessionManager.instance.activeSession!.user!;
      return signInCubeChat(user);
    }
    var user = CubeUser(login: token);
    return signIn(user).then((cubeSession) {
      user=cubeSession;
      return signInCubeChat(user);
    });
  }

 Future<CubeUser> signInCubeChat(CubeUser user) async {
    CubeChatConnectionSettings.instance.totalReconnections = 0;
    user.password = CubeSessionManager.instance.activeSession?.token;
    return CubeChatConnection.instance.login(user).then((cubeUser) {
      return cubeUser;
    });
}
```

I'm using custom identify authentication  

![image](https://user-images.githubusercontent.com/32142256/223540182-1f1c6ee5-3fd8-473a-9159-147ad70aa84a.png)

**Comment by TatankaConCube** [comment]
could you please provide the full log from starting login till getting this issue? additionally please check if this user login to the chat in another tab or using the same resource id on another device.

**Comment by quangvinhvux** [comment]
> could you please provide the full log from starting login till getting this issue? additionally please check if this user login to the chat in another tab or using the same resource id on another device.

Hi TatankaConCube, i found out i logged in account in another web browser, after i logout out it ok now. how can I deal with that? does ConnectyCube chat not support multi devices?

**Comment by TatankaConCube** [comment]
sure it supports this feature. I suppose the issue is related to the resource id, according to the XMPP specification only one user can log in with a unique resource id. the plugin that we are using for the calculation the resource id can generate the same resource ids. try to use your own resource id in the `login` method, for example, you can use `uuid` if you don't need to link the device and user.

```dart
    var resourceId = Uuid().v4(); // https://pub.dev/packages/uuid
    CubeChatConnection.instance.login(user, resourceId: resourceId);
```

**Comment by quangvinhvux** [comment]
> sure it supports this feature. I suppose the issue is related to the resource id, according to the XMPP specification only one user can log in with a unique resource id. the plugin that we are using for the calculation the resource id can generate the same resource ids. try to use your own resource id in the `login` method, for example, you can use `uuid` if you don't need to link the device and user.
> 
> ```dart
>     var resourceId = Uuid().v4(); // https://pub.dev/packages/uuid
>     CubeChatConnection.instance.login(user, resourceId: resourceId);
> ```

thank, it work.
