### ISSUE TITLE
P2P call session

### ISSUE THREAD

**Issue by prashantjdgit** [ConnectyCube/connectycube-flutter-samples#249]
How can we get the video call duration in P2P call connection?

**Comment by TatankaConCube** [comment]
You can manually calculate it by yourself. For it, you can start the timer on the first calling of the callback `onConnectedToUser ` and end the timer after receiving the callback `onConnectionClosedForUser` for the last member. The time between these callbacks is the call duration.

**Comment by prashantjdgit** [comment]
Thanks for the answer ,I will do that , please tell me why my speaker and microphone buttons are not working in flutter web in P2P videocall session.
