### ISSUE TITLE
Error Response in Login

### ISSUE THREAD

**Issue by prashantjdgit** [ConnectyCube/connectycube-flutter-samples#250]
"ResponseException: 422: {"errors":{"base":["email must be unique"]}}" , When using login or signup .
The error response i got is = "ResponseException: 422: {"errors":{"base":["email must be unique"]}}".
How can i fetch the value of base and response code using variable?
Please guide.

**Comment by TatankaConCube** [comment]
we process the response in the next way:
```dart
      case 400:
      case 401:
      case 403:
      case 404:
      case 422:
      case 429:
      case 500:
      case 503:
        completer.completeError(ResponseException(
            "ResponseException: ${response.statusCode}: ${response.body}"));
        break;
```
it means that you can get the status code and error in the JSON format using the next snippet in the `catchError` callback:
```dart
var error = onError.toString();
var statusCode = error.split(': ')[1];
var statusMessageJson = jsonDecode(error.split(': ')[2]);
```

but pay attention, the code can stop working after some changes on the server side

**Comment by prashantjdgit** [comment]
Thank you
