### ISSUE TITLE
Background call notification is not working in release mode.

### ISSUE THREAD

**Issue by prashantjdgit** [ConnectyCube/connectycube-flutter-samples#251]
My background call notification is not working in release mode.
Not creating params in   "  _sendStartCallSignalForOffliners " method.
Is there any changes we need to make in release mode for push notification?

**Comment by VTeresh** [comment]
could you please fill in all required fields in the issue template? we prepared it for getting initial information for starting to investigate your issues

**Comment by TatankaConCube** [comment]
could you please fill in all required fields in the issue template? we prepared it for getting initial information for starting to investigate your issues
