### ISSUE TITLE
Call Notification icon and ringtone is not working

### ISSUE THREAD

**Issue by prashantjdgit** [ConnectyCube/connectycube-flutter-samples#252]
Specify the sample to which the issue belongs (use [x]):
[] Chat sample
[x] P2P Call sample
[] Conference Call sample

Platform (use [x])
[x] Android
[] iOS
[] macOS
[] Windows
[] Web

Device info
Manufacture: Samsung , Nothing Phone1
Model: Galaxy S9 ,A063 
android version: 10 , 13

Describe the bug:
I have implemented the icons and ringtone functioning in 
 ConnectycubeFlutterCallKit.instance.init(
        onCallAccepted: _onCallAccepted,
        onCallRejected: _onCallRejected,
        icon: Platform.isAndroid ? 'logo.png' : 'CallkitIcon',
        notificationIcon: 'logo.png',
        color: '#A74E3D',
        ringtone: Platform.isAndroid ? 'sound.wav' : 'custom_ringtone.caf');

  

I have placed the .wav file in res/raw in android module.
And placed the logo.png in drawable in android module.
Only icon color is working.
Please help me out.

**Comment by TatankaConCube** [comment]
Set the Android resources names **without** an extension, in your case, it should be `logo` and `sound`. For iOS, it should be **with** an extension.
