### ISSUE TITLE
createSession(), signIn() Methods Throws Timeout exception 

### ISSUE THREAD

**Issue by jostney** [ConnectyCube/connectycube-flutter-samples#258]
Our testers and developers started to report timeout exceptions, even the production app happens same exception.

This occurs for random period, then it works normally.

From exception 
`SocketException (SocketException: Operation timed out (OS Error: Operation timed out, errno = 60), address = api.connectycube.com, port = 55712)`

**Comment by TatankaConCube** [comment]
yesterday we have some issues with our backend, now it should work as expected
