### ISSUE TITLE
Chat Data and Media retention periods?

### ISSUE THREAD

**Issue by aytunch** [ConnectyCube/connectycube-flutter-samples#26]
When do chat messages/images/videos get deleted from the servers? What is the life span for all of these? I checked the pricing page but I could not see a size limit or time limit even on the free tier. Can someone point me to this info? And I am very glad you guys are officially supporting Flutter.

**Comment by TatankaConCube** [comment]
hello @aytunch, we don't have any limits for the lifetime of data on the Connectycube server.

**Comment by aytunch** [comment]
@TatankaConCube this is good news, and thanks for the quick reply. We are in the midst of choosing a chat service for our startup and during the MVP period we are considering a service which has a free tier for low number of users but still have near full functionality. 

About data retention question above, is it true for the free tier as well?

**Comment by TatankaConCube** [comment]
Yes, it is actually for Free plan too. But you can have some limits like API-calls per hour or another. Please contact to our sale-department for more details sales@connectycube.com

**Comment by TatankaConCube** [comment]
Seems there is no much activity out there. Closing the issue as stale. If it’s still actual - please raise a new one.
