### ISSUE TITLE
I want to use Firebase FCM instead of APNS,

### ISSUE THREAD

**Issue by Badar25** [ConnectyCube/connectycube-flutter-samples#262]
I want to use Firebase FCM instead of APNS, but in console i dont have any option to see or customize the FCM payload such. as adding new key params. Im not talking about data notification

**Comment by Badar25** [comment]
Provide us customization to FCM payload so we can configure the field ourself. Rightnow, in my app, I can get all notification (not from your SDK), except notification generating from your sdk.

Acutally FIrebase onMessageListen its not catching it, not even in terminated state. Its just catching when app is open but in background thats it. 

Do you guys have any idea? Im using FCM (gcm) channel for iOS

**Comment by TatankaConCube** [comment]
could you please specify what data you required in the FCM push notification for iOS?

**Comment by TatankaConCube** [comment]
have you tried to enable the "Notifications" push type for FCM in the Connectycube admin panel?
<img width="647" alt="Screenshot 2023-06-05 at 11 08 32" src="https://github.com/ConnectyCube/connectycube-flutter-samples/assets/48598737/e58c87a6-fb07-4f23-9203-f7e84082647d">

**Comment by Badar25** [comment]
Im actually not getting fcm msgs from onListen method in flutter

**Comment by TatankaConCube** [comment]
I modified our Chat sample a little bit. And it can receive FCM push notifications in the same way as Android. The callbacks  `onMessageOpenedApp` and `onBackgroundMessage ` work well on the iOS side. I suppose other callbacks should work on iOS in the same way as Android. 

A few notes: 
- you should create the subscription on iOS in the same way as Android;
- the iOS system returns the dev token even if you build a release build, except if you build an archive to TestFlight, in this case, the system returns the production token, which means you should add both *.p12 certificates to the firebase developer console;

**Comment by Badar25** [comment]
Youre right, im using fcm in ios (gcm) that means not depending upon on
apns.

Im generating notifications from postman, im able to receive but not
getting from cc server (just onMessage.listen) rest of listeners are
working fin.

**Comment by Badar25** [comment]
what does that mean? "marked the chat connection inactive for receiving Chat push notification"

**Comment by Badar25** [comment]
```
FirebaseMessaging.onMessage.listen((message) async {
        debugPrint('onMessage: $message');  //<=== Not even this is printing, but when I send a notification from postman, its getting called but not from ConnectyCube server FCM
});
```

**Comment by TatankaConCube** [comment]
you will receive push notifications about the chat messages only in case when you are don't connected to the chat. for it you can logout from chat using `CubeChatConnection.instance.logout()` or you can mark the chat connection inactive using `CubeChatConnection.instance.markInactive()`

**Comment by TatankaConCube** [comment]
> If app is in background, terminated state, i am able to catch it, but when app is open I am not able able to recieve notification which should be listen by below code.

it is expected behavior because in our sample we mark the chat connection as inactive when moving to the background, the callback `onMessage` works in case when the app is in foreground state

**Comment by Badar25** [comment]
Oh still its not working for me tho?

**Comment by Badar25** [comment]
> > If app is in background, terminated state, i am able to catch it, but when app is open I am not able able to recieve notification which should be listen by below code.
> 
> it is expected behavior because in our sample we mark the chat connection as inactive when moving to the background, the callback `onMessage` works in case when the app is in foreground state

Perfect, this was the case. Thanks

**Comment by Badar25** [comment]
Sorry, its not working :(

**Comment by TatankaConCube** [comment]
What exactly doesn't work?

**Comment by Badar25** [comment]
Not getting the notification even tho I marked '''CubeChatConnection.instance.markInactive()'''

**Comment by TatankaConCube** [comment]
It doesn't make sense. When you have an active chat connection you will receive messages through it. When you are disconnected you will receive the push notification.

**Comment by Badar25** [comment]
> It doesn't make sense. When you have an active chat connection you will receive messages through it. When you are disconnected you will receive the push notification.
In my scenario, i had to show notification. Anyhow Im marking this as done, as I was doing a mistake in putting inside a screen I have just completely disabled it and it got working! 😄 🚀

**Comment by Badar25** [comment]
> It doesn't make sense. When you have an active chat connection you will receive messages through it. When you are disconnected you will receive the push notification.

In my scenario I had to, Anyhow marking as closed as I have completely disabled this markInactive/active from main.dart and it got working 😄.
