### ISSUE TITLE
Location sharing

### ISSUE THREAD

**Issue by aytunch** [ConnectyCube/connectycube-flutter-samples#27]
I haven't seen any examples on this. Is location sharing and displaying a screenshot of the LatLng (from a free maps provider) supported? If not, how should we handle it? it is necessary for our project. thanks

**Comment by TatankaConCube** [comment]
hello @aytunch, if you mean sending the message's attachment with type 'location', you can do this. Just set 'type' as 'location' and in the field 'data' put location data, like this `String data = "\"lat\":\"50.014141\",\"lng\":\"36.229058\"";`. Or it can be in another comfortable for your format.

**Comment by aytunch** [comment]
@TatankaConCube ok so there is support good news. What about the client UI support for location typed messages? Do we need to implement the desired message bubble with a map screenshot of the latlong or is it implemented in this Ui? Thanks

**Comment by TatankaConCube** [comment]
For now, we don't have any fully ready for use UI kits on flutter, you have to implement it by yourself.

**Comment by aytunch** [comment]
Ok thanks for the info
