### ISSUE TITLE
Device is showing call-kit notification as well as full screen custom notification in IOS device. 

### ISSUE THREAD

**Issue by MrunalrajRedij** [ConnectyCube/connectycube-flutter-samples#270]
**Specify the sample to which the issue belongs (use [x]):**
[] Chat sample
[x] P2P Calls sample
[] Conference Calls sample

**Platform (use [x])**
[] Android
[x] iOS
[] macOS
[] Windows
[] Web
[] Linux

**Device info**
Manufacture: Apple
OS version: 16.1

**Describe the bug:**
_Have uploaded video to get a clear idea.
https://github.com/ConnectyCube/connectycube-flutter-samples/assets/75795149/7b45bb60-7414-4e6e-a2cd-6139e149aa8c_

Device is showing call-kit notification as well as full-screen custom notification in IOS device. 
And after accepting it is sending multiple signals, causing full-screen notification to popping multiple times

**Logs:**
```
log here
```

**Actual result:**
Both call-kit notification and full screen custom notification is appearing simultaneously.

**Expected behavior:**
Call-kit notification should only be visible when app is in background and full-screen notification screen should only be visible when device is in foreground.

**Additional info**
This works fine in Android devices.

**Comment by TatankaConCube** [comment]
but it is your internal logic, you can show only one of them, as I understand your CallKit notification is showing by VoIP push notification and the full-screen notification is showing from the `onReceiveNewSession` callback

we develop this logic in our sample to simplify users testing the app in the case when the push notifications are not configured in the project

**Comment by MrunalrajRedij** [comment]
IOS is showing a full-screen call kit notification, I want to disable it when an app is in the foreground. I searched but didn't find anything. If you know how to do it please add comment below.
To fix it, I have disabled my own custom full-screen when in the foreground. It does the job.
