### ISSUE TITLE
Firebase_options.dart is missing 

### ISSUE THREAD

**Issue by prashantJangidSys** [ConnectyCube/connectycube-flutter-samples#275]
Chat Samples (Flutter)
I have issues in creating the firebase_options.dart file Or it is the library file.
Please help me out .
I have to use the sample chat code but stuck on this file.

**Comment by TatankaConCube** [comment]
please follow the guide from our README, namely the part about the [Configuring Push notifications](https://github.com/ConnectyCube/connectycube-flutter-samples/tree/master/chat_sample#configure-push-notifications). You should just follow the guide of the Firebase team on how to integrate the Firebase to the app.
