### ISSUE TITLE
is there any methods for showing isOnline status of currrent user in chat ?

### ISSUE THREAD

**Issue by VivekBViOS** [ConnectyCube/connectycube-flutter-samples#278]
I have added image for the same 
![image](https://github.com/ConnectyCube/connectycube-flutter-samples/assets/76780663/d83989ac-a2bb-4572-b8cb-5665c010bc34)

**Comment by TatankaConCube** [comment]
you can use the [Get last activity](https://developers.connectycube.com/flutter/messaging?id=get-last-activity) request and [Last activity subscription](https://developers.connectycube.com/flutter/messaging?id=last-activity-subscription) feature for implementing the required feature

**Comment by richanshah** [comment]
thanks
