### ISSUE TITLE
Can't see reconnected user in video conference

### ISSUE THREAD

**Issue by tw1st88** [ConnectyCube/connectycube-flutter-samples#28]
**Specify the sample to which the issue belongs (use [x]):**
[ ] Chat sample
[ ] P2P Call sample
[x] Conference Call sample

**Platform (use [x])**
[x] Android
[x] iOS

**Describe the bug:**
If one of the users restarted the app during a call and reconnected to the room he can see others, but his video does not appear on remote sides anymore (onPublishersReceived called, but onRemoteStreamReceived doesn't).

**Steps to Reproduce:**
1. connect to video conf
2. restart the app
3. reconnect to the video conf

**Logs:**
https://gist.github.com/tw1st88/3e196bf0fd623affb81dfa02970955f5

**Actual result:**
Video of the reconnected user doesn't appear anymore on remote sides.

**Expected behavior:**
Video of the reconnected user reappears for all participants.

**Additional info**
I'm on the free plan. In my case I don't need accept/reject call UX, just connect/disconnect video room.
Code that I use 
sign up screen:

    await createSession();
    final cubeUser = CubeUser(
      login: nickname,
      password: '00000000',
    );
    await signUp(cubeUser);

call screen:

    ConferenceConfig.instance.url = SERVER_ENDPOINT;

    final cubeUser = CubeUser(
      login: nickname,
      password: '00000000',
    );

    if (!CubeSessionManager.instance.isActiveSessionValid()) await createSession(cubeUser);
    final user = await signIn(cubeUser);  // from connectycube_core.dart
    _callClient = ConferenceClient.instance;
    _callSession = await _callClient.createCallSession(user.id);

    RTCMediaConfig mediaConfig = RTCMediaConfig.instance;
    mediaConfig.minHeight = 180; 
    mediaConfig.minWidth = 180;  
    mediaConfig.minFrameRate = 15; 

    _addEventHandlers(_callSession); // same as in example
    _callSession.setSessionCallbacksListener(this);  // as in example, but commented _closeSessionIfLast() for reconnection testing

    _callSession.joinDialog(widget.roomId, ((publishers) {
    }));

**Comment by TatankaConCube** [comment]
Hello @tw1st88, sorry for the late answer. Please, check on the opponents' side, did they subscribe to the user again after its reconnect. Can you reproduce the same issue in our sample?

**Comment by tw1st88** [comment]
Hello, @TatankaConCube. 
I checked this. The user subscribes again after his opponent reconnected. 
And I can reproduce the issue in your sample with small adaptations. Here is the code https://github.com/tw1st88/connectycube-flutter-samples

**Comment by TatankaConCube** [comment]
If the issue still reproduces, please create one more ticket. Closing
