### ISSUE TITLE
ios push notifications not working 

### ISSUE THREAD

**Issue by richanshah** [ConnectyCube/connectycube-flutter-samples#280]

**Comment by TatankaConCube** [comment]
for clarification - do you use the FCM push notifications on iOS? If so, have you configured the Firebase console for working with APNS? Have you added the required certificates there? Please recheck our and Firebase guides one more time https://developers.connectycube.com/flutter/push-notifications?id=fcm-on-the-iosmacos

**Comment by richanshah** [comment]
yes, we have done everything as provided in the documents still facing issues.

**Comment by TatankaConCube** [comment]
Then we need the next info:
- log with the subscription request/response (or full log from starting the app till finishing the subscription flow);
- screenshot of the subscribed user profile on the Connectycube dashboard, please open the subscription details and take a screenshot;
- two JSON files with reports of the sent push notification that can be downloaded from the Connectycube dashboard by path Dashboard -> App -> Push Notifications -> Queue by clicking on the `sent` link.

Have you configured the Firebase console for linking the APNS and iOS? Please take a screenshot with the attached certificates.

**Comment by richanshah** [comment]
Ok, I will provide you today. also, I have a few queries.

1. I want my one-to-one user in chat to have a profile image field. can u provide me with any reference material to add to my users
2. What are the unique ids to fetch users for one-to-one chat and group chat? suppose I have a list of users in my app coming from API. so what parameters are needed to open chat for the first time which I need to store in my APIs as well?

**Comment by TatankaConCube** [comment]
please create separate tickets with your latest questions, cause they are not related to the current topic

**Comment by richanshah** [comment]
ok

**Comment by richanshah** [comment]
![Screenshot from 2023-08-11 14-14-56](https://github.com/ConnectyCube/connectycube-flutter-samples/assets/16899603/69b0877c-7b6d-4ce1-899e-49255d6793de)
![Screenshot from 2023-08-11 14-14-43](https://github.com/ConnectyCube/connect
![Screenshot from 2023-08-11 14-14-56](https://github.com/ConnectyCube/connectycube-flutter-samples/assets/16899603/1a23df08-5d9d-4f01-991d-8601c3097c70)
ycube-flutter-samples/assets/16899603/172c8fb2-6f96-4790-b7de-c64b9648d9bc)

[Logs.docx](https://github.com/ConnectyCube/connectycube-flutter-samples/files/12319894/Logs.docx)

let me know if u can find any issues

**Comment by richanshah** [comment]
hi @TatankaConCube  , ios to ios working now
i have updated some variables in dashboard

**Comment by TatankaConCube** [comment]
> also i am not able to send to only ios user notifications from connecttycube dashboard.

before I study logs just pay your attention to my answer [here](https://github.com/ConnectyCube/connectycube-flutter-samples/issues/279#issuecomment-1671418228)

**Comment by TatankaConCube** [comment]
>  ios to ios working now

you don't need my help here, right?

**Comment by richanshah** [comment]
yaaa its working for now. although i havent checked in all available devices but for now its working with one iphone device
