### ISSUE TITLE
I want my one-to-one user in chat to have a profile image field. can u provide me with any reference material to add to my users

### ISSUE THREAD

**Issue by richanshah** [ConnectyCube/connectycube-flutter-samples#281]
I want my one-to-one user in chat to have a profile image field. can u provide me with any reference material to add to my users

**Comment by TatankaConCube** [comment]
It is easy, your user just should to have the `avatar` and our server will set this field to the `photo` field of the private dialog. There is documentation on how to set user avatar https://developers.connectycube.com/flutter/authentication-and-users?id=user-avatar. Also, this functionality is presented in our [Chat sample](https://github.com/ConnectyCube/connectycube-flutter-samples/blob/master/chat_sample/lib/src/settings_screen.dart#L166).
