### ISSUE TITLE
Filter by custom parameter

### ISSUE THREAD

**Issue by Badar25** [ConnectyCube/connectycube-flutter-samples#286]
**Is your feature request related to a problem? Please describe.**
Currently I want to implement a feature where I want to just filter my messages of chatroom ie fetch me messages that were sent as anonymous etc.

**Describe the solution you'd like**
I'd like to fetch messages according to my specified condition ie: Fetch me all messages that have my custom param in it.

Is there any alternative for this approach to have filter on my custom parameter?
![Screenshot 2023-08-21 at 11 56 16 AM](https://github.com/ConnectyCube/connectycube-flutter-samples/assets/122017969/8ca80c7f-8c96-4a21-8a18-74b805b0e68e)

**Comment by TatankaConCube** [comment]
unfortunately, we don't have these filters, there is documentation with possible parameters for fetching messages request https://developers.connectycube.com/server/chat?id=parameters-6

**Comment by Badar25** [comment]
Is there any way I can fetch such messages with specific criteria?

**Comment by TatankaConCube** [comment]
I provided the possible criteria list in the previous message. Unfortunatelly we don't have other variants for messages filtering.
