### ISSUE TITLE
I have followed demo but it is adding new messages on the top of the tray instead of in bottom. so can u tell me what has been used for that? 

### ISSUE THREAD

**Issue by richanshah** [ConnectyCube/connectycube-flutter-samples#287]
I have followed demo but it is adding new messages on the top of the tray instead of in bottom. so can u tell me what has been used for that?  in chat screen

**Comment by TatankaConCube** [comment]
https://github.com/ConnectyCube/connectycube-flutter-samples/blob/master/chat_sample/lib/src/chat_dialog_screen.dart#L806 as you can see, we use the reversed list in our example

**Comment by richanshah** [comment]
ok
