### ISSUE TITLE
I have one feature where need to open camera and upload file from there. 

### ISSUE THREAD

**Issue by richanshah** [ConnectyCube/connectycube-flutter-samples#288]
I have one feature where need to open camera and upload file from there. with ur current code i am not able to add because in ur code there is a concept of Cubefile which doesnt seem working with default camera option, can u help me to accomplish this features ?

**Comment by richanshah** [comment]
also i have feature of picking multiple photos from gallery, can u guide for the same?

**Comment by TatankaConCube** [comment]
> doesnt seem working with default camera option, can u help me to accomplish this features ?

our SDK supports two types of data for uploading `Future<CubeFile> uploadFile(File file,
    {bool? isPublic, String? mimeType, Function(int progress)? onProgress})` and `Future<CubeFile> uploadRawFile(List<int> bytes, String name,
    {bool? isPublic, String? mimeType, Function(int progress)? onProgress})`. what type of data do you have after requesting data from a camera?

> also i have feature of picking multiple photos from gallery, can u guide for the same?

you need to refactor the code a little bit for requesting few files then uploading few files in queue and then send them as attachments in the message

**Comment by richanshah** [comment]
ok i will check these methods.
