### ISSUE TITLE
I have feature in chat where I have to add custom feild in message and display different type of data, for example i have to share contact in chat and display in the chat list.

### ISSUE THREAD

**Issue by richanshah** [ConnectyCube/connectycube-flutter-samples#292]
I have feature in chat where I have to add custom feild in message and display different type of data, for example, i have to share contact in chat and display in the chat list. Is there any way to implement this and provide custom data in the message?

**Comment by richanshah** [comment]
@tatanka987  , can you guide me for this? share contact feature example
![Screenshot from 2023-08-28 15-28-43](https://github.com/ConnectyCube/connectycube-flutter-samples/assets/16899603/a5af84a9-a0e2-4592-913f-1f82e408337a)

**Comment by TatankaConCube** [comment]
the `CubeMessage` model has the `properties` field that you can use for storing any custom data related to your message.

**Comment by TatankaConCube** [comment]
please don't mention @tatanka987 in your questions, mention me please if it is required

**Comment by richanshah** [comment]
ok

**Comment by richanshah** [comment]
> properties

I have implemented this , if anyone needs a code for sample i am adding it here. 

 /// Create Cube Message
  CubeMessage createCubeMsg() {
    var message = CubeMessage();
    message.dateSent = DateTime.now().millisecondsSinceEpoch ~/ 1000;
    message.markable = true;
    message.saveToHistory = true;
    return message;
  }

  /// Send Chat Status to ConnectyCube for share contact
  void onSendChatMessageToShareContact() {
    final message = createCubeMsg();
    if (navigatedFrom == AppPages.playerDetail) {
      message.properties[AppConstant.userUUID] = userUUID ?? '';
      message.properties[AppConstant.userName] = userName ?? '';
      message.properties[AppConstant.profilePic] = profilePic ?? '';
    } else if (navigatedFrom == AppPages.playOfTheWeek) {
      message.properties[AppConstant.playOfWeek] = jsonEncode(playOfWeek);
    } else if (navigatedFrom == AppPages.openMatches) {
      message.properties[AppConstant.matchInfo] = jsonEncode(matchInfo);
    } else if (navigatedFrom == AppPages.scheduledMatches) {
      message.properties[AppConstant.scheduledMatchInfo] =
          jsonEncode(scheduledMatchInfo);
    } else if (navigatedFrom == AppPages.newsAnnouncement) {
      message.properties[AppConstant.newsAnnouncement] =
          jsonEncode(newsAnnouncement);
    } else if (navigatedFrom == AppConstant.congratulations) {
      message.properties[AppConstant.congratulations] =
          jsonEncode(congratulationInfo);
    } else if (navigatedFrom == AppConstant.pastMatches) {
      message.properties[AppConstant.pastMatches] = jsonEncode(pastMatches);
    } else if (navigatedFrom == AppPages.matchDetails) {
      message.properties[AppConstant.matchDetails] = jsonEncode(matchDetails);
    } else if (navigatedFrom == AppPages.scheduleMatchDetails) {
      message.properties[AppConstant.scheduleMatchDetails] =
          jsonEncode(scheduleMatchDetails);
    } else if (navigatedFrom == AppPages.pastMatchDetails) {
      message.properties[AppConstant.pastMatchesDetails] =
          jsonEncode(pastMatchDetails);
    } else if (navigatedFrom == AppPages.newsDetails) {
      message.properties[AppConstant.newsDetails] = jsonEncode(newsDetails);
    } else if (navigatedFrom == AppPages.clubDetails) {
      message.properties[AppConstant.clubDetails] = jsonEncode(clubDetailsData);
    }
    // message.body = "Share Profile";

    onSendMessageToAllDialogs(message);
  }
