### ISSUE TITLE
i have added custom data in user on signup 

### ISSUE THREAD

**Issue by richanshah** [ConnectyCube/connectycube-flutter-samples#294]
I have added custom data in the user on signup, in the admin panel i am getting this data. but in logs of user, I am not getting it. 

 userToSignUp.customData= user?.uuid;
    CubeDialogCustomData customData = CubeDialogCustomData(user?.uuid ?? "");
    customData.fields['uuid'] = user?.uuid;
    userToSignUp.customDataClass = customData;
    mainController.connectyCubeService.signInCC(userToSignUp)

login  = {full_name: rrrrrrr sssssss, address_book_name: null, email: rr@gmail.com, login: rrrrrrr, phone: 3333333330, website: null, last_request_at: null, external_user_id: null, external_id: null, facebook_id: null, twitter_id: null, password: 123456, oldPassword: null, custom_data: null, avatar: https://main-court-demo.s3.amazonaws.com/images/User/User.png, guest: null, timezone: null, tag_list: null, id: 10484765, created_at: null, updat
![Screenshot from 2023-08-25 18-37-30](https://github.com/ConnectyCube/connectycube-flutter-samples/assets/16899603/7df00a11-f7d8-4f09-b8c9-7334c6b11de3)
ed_at: null}

**Comment by TatankaConCube** [comment]
> Password not verified

means your login/email doesn't match with password
