### ISSUE TITLE
is there any methods avaialble to send message to multiple users or dialog at single shot ?

### ISSUE THREAD

**Issue by richanshah** [ConnectyCube/connectycube-flutter-samples#296]
@TatankaConCube 

is there any methods avaialble to send message to multiple users or dialog at single shot ?

**Comment by TatankaConCube** [comment]
what do you mean? in the group chat the message will be sent to all members

**Comment by richanshah** [comment]
no not like that, if I have a different dialog list and on the selection of a few dialogs I want to send a  message in all selected list.

**Comment by richanshah** [comment]
onSendMessageToAllDialogs message= {_id: 64f1bd969e8761b5db7014dd, chat_dialog_id: null, message: null, date_sent: 1693564310, sender_id: null, recipient_id: null, read_ids: null, delivered_ids: null, views_count: null, attachments: null, reactions: null, id: null, created_at: null, updated_at: null, userUUID: a014ef63-e94c-4eeb-b16b-f90e4c681fbf, userName: Richa Shah, profilePic: 

CB-SDK: : onSendMessageToAllDialogs ex= IllegalStateException: Check you set participant and login to the chat



  void onSendMessageToAllDialogs(CubeMessage message) async {
    log("onSendMessageToAllDialogs message= $message");

    for (var dialogItem in dialogList) {
      if (dialogItem.isSelected) {
        final CubeDialog dialog = dialogItem.data;
        showLoader(value: true);
        await dialog.sendMessage(message).then((value) {
          log("onSendMessageToAllDialogs value= $value");
          showLoader(value: false);
          Get.back();
        }).catchError((ex) {
          log("onSendMessageToAllDialogs ex= $ex");
          showLoader(value: false);
          showSnackBar(message: 'Error in sending message$ex');
        });
      }
    }
  }



i have tried this but not working

**Comment by TatankaConCube** [comment]
> i have tried this but not working

what error do you have here?

**Comment by TatankaConCube** [comment]
saw

**Comment by richanshah** [comment]
Check you set participant and login to the chat

**Comment by richanshah** [comment]
i know u told me before but still i didnt find a proper way to handle this error. because it is not even going on session restore.

**Comment by richanshah** [comment]
ok got it , if i pause n resume then it is working. but when i come to app as a normal flow i need to handle it somewhere.

**Comment by TatankaConCube** [comment]
>  Check you set participant and login to the chat

the error message says that your dialog should have not empty `occupantsIds` list and it should contains the user(s) different than the current user id. the group dialog should have the dialogId. and your app should be logged in to the chat.

**Comment by richanshah** [comment]
ok thanks. this feature is working now so closing the thread.

**Comment by richanshah** [comment]
@TatankaConCube , getting this message frequntly today while developing and testing, not sure why. 

IllegalStateException: Check you set participant and login to the chat

**Comment by TatankaConCube** [comment]
the reason is the same https://github.com/ConnectyCube/connectycube-flutter-samples/issues/296#issuecomment-1702545568

here are some parts of the code what generate this exception
```dart
if (CubeDialogType.PRIVATE == type) {
      int recipientId = getRecipientId();
      if (recipientId == -1) {
        completer.completeError(IllegalStateException(
            "Check you set participant and login to the chat"));
        return completer.future;
      }

      PrivateChatManager? privateChatManager =
          CubeChatConnection.instance.privateChatManager;
      if (privateChatManager == null) {
        completer.completeError(IllegalStateException(
            "Need login to the chat before perform chat related operations"));
        return completer.future;
      }

      PrivateChat privateChat = privateChatManager.getChat(recipientId);

      completer.complete(privateChat);
    }
```
```dart
  int getRecipientId() {
    if (CubeDialogType.PRIVATE != type || isEmptyList(occupantsIds)) {
      return -1;
    }

    CubeChatConnection chatConnection = CubeChatConnection.instance;

    if (chatConnection.currentUser == null) return -1;

    for (int occupantId in occupantsIds!) {
      if (occupantId != chatConnection.currentUser!.id) return occupantId;
    }

    return -1;
  }
```

**Comment by richanshah** [comment]
> @TatankaConCube
> 
> is there any methods avaialble to send message to multiple users or dialog at single shot ?

I have implemented this , code for reference. 


 void onSendMessageToAllDialogs(CubeMessage message) async {
    log("onSendMessageToAllDialogs message= $message");

    for (var dialogItem in dialogList) {
      if (dialogItem.isSelected) {
        final CubeDialog dialog = dialogItem.data;
        showLoader(value: true);
        await dialog.sendMessage(message).then((value) {
          log("onSendMessageToAllDialogs value= $value");
          showLoader(value: false);
          Get.back();
        }).catchError((ex) {
          log("onSendMessageToAllDialogs ex= $ex");
          showLoader(value: false);
          showSnackBar(message: 'Error in sending message$ex');
        });
      }
    }
  }
