### ISSUE TITLE
when i try to send message it doesnt update the ui in some cases

### ISSUE THREAD

**Issue by richanshah** [ConnectyCube/connectycube-flutter-samples#297]
onSendMessage message= {_id: 64f56b2a64537bef9fb3c39f, chat_dialog_id: null, message: hii, date_sent: 1693805354, sender_id: null, recipient_id: null, read_ids: null, delivered_ids: null, views_count: null, attachments: null, reactions: null, id: null, created_at: null, updated_at: null}

can u tell me the problem here? @TatankaConCube

**Comment by TatankaConCube** [comment]
our sdk doesn't provide any UI components or solutions, please take a look more carefully at your code to determine what required data is absent
