### ISSUE TITLE
update image / avtar not working 

### ISSUE THREAD

**Issue by richanshah** [ConnectyCube/connectycube-flutter-samples#299]
_updateUser user with login: Bhumi, name: Bhumi Parikh, avatarUrl: https://main-court-demo122136-dev.s3.amazonaws.com/public/User/1694006678805563
18:54:40.885                                      I  CB-SDK: : =========================================================
18:54:40.885                                      I  === REQUEST ==== 3352b174-6634-430c-b21b-4100468c2cea ===
18:54:40.885                                      I  REQUEST
18:54:40.885                                      I    PUT https://api.connectycube.com/users/10551524 
18:54:40.885                                      I  HEADERS
18:54:40.885                                      I    {Content-type: application/json, ConnectyCube-REST-API-Version: 0.1.1, CB-SDK: Flutter 2.7.0, CB-Token: 29C95E91BA345F8E63656735E8681B9F566C}
18:54:40.885                                      I  BODY
18:54:40.886                                      I    {"user":{"full_name":"Bhumi Parikh","login":"Bhumi","avatar":"https://main-court-demo122136-dev.s3.amazonaws.com/public/User/1694006678805563","id":10551524}}
CB-SDK: : *********************************************************
18:54:42.010                                      I  *** RESPONSE *** 200 *** 3352b174-6634-430c-b21b-4100468c2cea ***

**Comment by richanshah** [comment]
when i update avtar its not working. do i also have to uplaod it to connectycube server? although i am not getting it from connectycube portal

**Comment by TatankaConCube** [comment]
could you please show the user before updating the avatar and after updating?

**Comment by richanshah** [comment]
resolved issue
