### ISSUE TITLE
Add existings users of my application to connetycube

### ISSUE THREAD

**Issue by richanshah** [ConnectyCube/connectycube-flutter-samples#310]
Hi @TatankaConCube  , is there any way i can provide you my users table and u can store all users in db of connectycube ?

**Comment by TatankaConCube** [comment]
I know, the back-end team did it for other customers. Please contact our Support team [support@connectycube.com](mailto:support@connectycube.com) and they help you with this.

**Comment by TatankaConCube** [comment]
Another variant - use our Custom Identity Provider feature. It allows you to authenticate the user on your server via Connectycube API and returns the Connectycube user on the login request, more details by link https://developers.connectycube.com/guides/custom-identity-provider

**Comment by richanshah** [comment]
ok thanks
