### ISSUE TITLE
Multiple Device login in web for p2p calls

### ISSUE THREAD

**Issue by b2bPrasad** [ConnectyCube/connectycube-flutter-samples#317]
**Specify the sample to which the issue belongs (use [x]):**
[] Chat sample
[x] P2P Calls sample
[] Conference Calls sample

**Platform (use [x])**
[] Android
[] iOS
[] macOS
[] Windows
[x] Web
[] Linux

**Device info**
Manufacture: 
Model: 
OS version:

**Describe the bug:**
So I am trying to integrate for web without push notification right now. I have a scenario as stated below:
1. User A logs in.
2. Calls B is logged in from multiple browsers - B1 and B2
3. A calls B
4. The incoming call screen is displayed on both the devices, which is correct.
5. When B receives the call from one of the browsers, B1, the incoming call screen should be closed on B2.
6. This is not happening right now.
7. Is there a way to achieve this on the web and on devices?

**Steps to Reproduce:**
1.  Use the p2p call sample and replicate the above scenario.

I found [this issue](https://github.com/ConnectyCube/connectycube-flutter-samples/issues/247) which talks about it.

@tatanka987 can you help me point to the documentation or explain how to achieve this?

**Comment by b2bPrasad** [comment]
@TatankaConCube this worked. Thank you.

The only issue we are facing right now is iOS to iOS the audio volume is very low and it is happening consistently. Do you have any insights on this?

**Comment by TatankaConCube** [comment]
please, create a new issue with this topic, I will describe possible reasons and the possible solutions for them

**Comment by b2bPrasad** [comment]
noted,

@TatankaConCube closing this issue.
New issue listed [https://github.com/ConnectyCube/connectycube-flutter-samples/issues/318](here)
