### ISSUE TITLE
issue with public group

### ISSUE THREAD

**Issue by richanshah** [ConnectyCube/connectycube-flutter-samples#320]
Hi @TatankaConCube ,  Hope u r doing well

In public group once i unsubscribe user from group , and try to subscribe again but at that time i am not able to find the public group data fron dialogs user has, can u guide me for the same

@TatankaConCube  in admin portal I am not able to see custom feilds i pass to dialogs , can u make that possible for me ?

**Comment by TatankaConCube** [comment]
> i am not able to find the public group data fron dialogs user has, can u guide me for the same

could you please describe in more datails what do you mean? can't you get the dialog data after unsubscribe?

> in admin portal I am not able to see custom feilds

the custom data of dialog is the deprecated feature and we don't plan to extend this feature. For now, you can use the [Extensions](https://developers.connectycube.com/server/chat?id=dialog-extensions) feature (will add Flutter doc later), also you will see the saved dialog extensions in the admin panel

**Comment by TatankaConCube** [comment]
> can u make that possible for me ?

you can see the saved Custom objects related to the dialogs in the list of Custom data by path `App -> Custom -> List`

**Comment by richanshah** [comment]
@TatankaConCube  , yes after unsubscribe the public dialog , when I fetch avaialble dialog list of user, I am not able to find that dialog in the list, which I need due to rejoin feature in our app.

**Comment by richanshah** [comment]
> > can u make that possible for me ?
> 
> you can see the saved Custom objects related to the dialogs in the list of Custom data by path `App -> Custom -> List`

yes I know that, but suppose For every dialog i have one custom field which I want to see in dialog list, but which is not available.

**Comment by TatankaConCube** [comment]
it is impossible cause after unsubscribe the user is not a member of this dialog and can't get it. your user need to have the dialog id to rejoin it again

**Comment by richanshah** [comment]
@TatankaConCube  but first time also  when user is not in the public group , still he gets the public dialog in the list but after subscribe and unsubscribe , it gets removed..

**Comment by richanshah** [comment]
/// Join group Request api implementation
  Future<void> joinGroupRequest({
    required int index,
    required QueryGetNotificationListnotificationListdata? notificationData,
  }) async {
    final response = await apiManager.joinGroupRequest(
      userID: SharedPref.getString(PrefsKey.uuID),
      groupID: notificationData?.group?.uuid ?? '',
    );
    if (response.isSuccess) {
      if (response.body?.joinGroup.meta.status_code ==
          AppConstant.successStatusCode) {
        final statusData = notificationData?.group?.copyWith.call(
          is_accept: NotiRequestStatus.accepted.status,
        );
        final data = notificationData?.copyWith.call(
          group: statusData,
          is_read: 1,
        );

        // invitesNotificationList[index] = data;
        // update();
        userConnectyCubeList.add(SharedPref.getUser()?.id ?? 0);
        await getChatDialog(notificationData?.group?.uuid ?? '')
                .then((connectyCubeDialogId) {
              if (connectyCubeDialogId?.isNotEmpty ?? false) {
                subscribeToDialog(connectyCubeDialogId ?? "").then((value) {
                  log("subscribeToDialog successCallback= $value");
                  invitesNotificationList[index] = data;
                  update();
                  userConnectyCubeList.add(SharedPref.getUser()?.id ?? 0);
                }).onError((error, stackTrace) {
                  invitesNotificationList[index] = data;
                  update();
                  log("subscribeToDialog errorCallback= $error");
                  showSnackBar(message: error.toString());
                });
              } else {
                invitesNotificationList[index] = data;
                update();
              }
            }) ??
            "";
        invitesNotificationList[index] = data;
       // showSnackBar(message: response.body?.joinGroup.meta.message ?? "");
        update();
        _successMessage(msg: response.body?.joinGroup.meta.message ?? '');
      } else {
        showSnackBar(message: response.body?.joinGroup.meta.message ?? "");
      }
    } else {
      showSnackBar(message: response.body?.joinGroup.meta.message ?? "");
    }
  }
  
  
   /// Create chat dialog with selected users
  Future<String?> getChatDialog(String? groupUuid) async {
    showLoader(value: true);
    String? chatGroupUuid;
    await mainController.connectyCubeService
        .getChatDialogs()
        .then((value) async {
      dialogList = value;
      log("_createDialog with user= $currentUser");
      showLoader(value: false);
      if (dialogList.isNotEmpty) {
        CubeDialog? newDialog = dialogList.firstWhereOrNull((element) {
          return element.data.customData?.fields['groupUuid'] == groupUuid;
        })?.data;

        // Find if any private chat with occupant id already created then return or else create new chat
        if (newDialog != null) {
          chatGroupUuid = newDialog.dialogId;
        } else {
          // Todo Richa check this point
          //showSnackBar(message: "No Group Found");
          return null;
        }
      } else {
        //showSnackBar(message: "No Group Found");
        return null;
      }
    });
    return chatGroupUuid;
  }
  
  this works fine first time when user tries to subscribe , but once he leave the dialog then he cant get in the list

**Comment by richanshah** [comment]
@TatankaConCube  can i pass dialogId from my side? I tried once but it seems it is being auto genrated

**Comment by TatankaConCube** [comment]
could you please provide a full log that contains all requests from the first time flow and the logs during the second flow requests?

> can i pass dialogId from my side?

what do you mean? do you want to set the dialog id during creation? but your issue was about subscribe/unsubscribe? to for subscription to the public dialog you need the dialog is you want to subscribe to

**Comment by richanshah** [comment]
@TatankaConCube  , logs will take some time,  yes I want to set  the dialog id during creation , is it possible?

**Comment by TatankaConCube** [comment]
> yes I want to set the dialog id during creation , is it possible?

no, it is a unique field in our DB and the server generates it by itself

why do you need it? what issue does it resolve for you?

**Comment by richanshah** [comment]
@TatankaConCube  
the thing is , I used custom feild as my group uuid, so I can find dialog id based on condition if it contains custom group uuid which I passed, but now I dont have public dialogs in the connectycube user as per our current discussion , so is there any way without depedending on our server to store this public dialog id field , i can make find this dialog id based on group uuid i have or else I can pass my group uuid as dialog id so I just need to subscribe to that dialog. I hope you understand my point and help me with this flow.

**Comment by richanshah** [comment]
@TatankaConCube  any update on this?

**Comment by richanshah** [comment]
@TatankaConCube  can i pass custom jid?

**Comment by richanshah** [comment]
@TatankaConCube  , for invite group flow , the steps you suggested didnt work for us. but now we have handled with storing dialog Id of group in our server. thanks for your support.
