### ISSUE TITLE
Notifications and incoming call screen appear on the same time, when the app is open.

### ISSUE THREAD

**Issue by radyhaggag** [ConnectyCube/connectycube-flutter-samples#328]
**Specify the sample to which the issue belongs (use [x]):**
[] Conference Calls sample

**Platform (use [x])**
[] Android
[] iOS

**Describe the bug:**
When make a new session the incoming call screen appear and also the notification appear above it in case i'm opening the app.

but when the app on background, the notification only appear, and if on lock screen and no opened as you said the incoming only appear.

![photo_2024-01-19_19-00-07](https://github.com/ConnectyCube/connectycube-flutter-samples/assets/74488175/eea0087d-44af-40ec-8ca2-713d1368a838)

**Comment by TatankaConCube** [comment]
it happens becaose you show it from two places. 1 - the callkit shows the notification, 2- your app shows the Incoming call screen after receving the signaling message about new call. you nee to deside how to resolve it on your side. starting from the version 2.6.0 of the CallKit plugin you have the `onCallIncoming ` callback what fires before showing the incoming call notification

**Comment by radyhaggag** [comment]
> onCallIncoming

Can you please some details please, so now what the methods that responsible for handling this on the forground?

**Comment by radyhaggag** [comment]
@TatankaConCube is there update here please? another issue on the same foreground is when receive the call from ios to android, a duplication of the incoming call screen occur?

**Comment by TatankaConCube** [comment]
it is a completely client-side feature, you can show the call notification from the callkit only. please describe your needs, if you require additional functionality from the CallKit plugin

**Comment by TatankaConCube** [comment]
you can't ignore the VoIP push notifications for iOS, it is a system limitation, the system will ignore all VoIP notifications if your app skips about five VoIP push notifications

you can try not to send the push notification in case the opponent is online, you can use the [Get last activity](https://developers.connectycube.com/flutter/messaging?id=get-last-activity) feature for it. bur here is the risk of missing the call in case the app moves to the background during starting the call

for android it looks possible to ignore a push notification, but the app should regularly notify the plugin about ignoring/allowing notifications. you can create the feature request for the CallKit repo

**Comment by TatankaConCube** [comment]
> a duplication of the incoming call screen occur

what do you mean? does the CallKit show two CallKit screens?

**Comment by radyhaggag** [comment]
> > a duplication of the incoming call screen occur
> 
> what do you mean? does the CallKit show two CallKit screens?

On the main screen we handled on receive new call method on the call manger like that 

`  void _initCalls() {
    log('[_initCalls]');
    CallManager.instance.onReceiveNewCall = (
      callId,
      meetingId,
      initiatorId,
      participantIds,
      callType,
      callName,
    ) {
      _showIncomingCallScreen(
        callId,
        meetingId,
        initiatorId,
        participantIds,
        callType,
        callName,
      );
    };
  }

  void _showIncomingCallScreen(
    String callId,
    String meetingId,
    int initiatorId,
    List<int> participantIds,
    int callType,
    String callName,
  ) {
    log('[_showIncomingCallScreen]');

    Navigator.of(context).push(
      MaterialPageRoute(
        builder: (context) => IncomingCallScreen(
          currentUser: currentUser,
          callId: callId,
          meetingId: meetingId,
          initiatorId: initiatorId,
          participantIds: participantIds,
          callType: callType,
          callName: callName,
        ),
      ),
    );
  }

`

So when the caller device is IOS and make a call to android device this method called twice and the incoming call screen show twice so when he reject the call in the first screen, he see the incoming call again.


this is the main problem, the first one we solved it by using the lifecycle handler, so the main problem currently is "duplication of the incoming call screen"

**Comment by TatankaConCube** [comment]
then you need to check how many times the ios user sends the call invitation signaling message/push

**Comment by radyhaggag** [comment]
> then you need to check how many times the ios user sends the call invitation signaling message/push

This on the code or what? if on the code can you tell me in which class or file?
