### ISSUE TITLE
need audio/video call history

### ISSUE THREAD

**Issue by BhavyKoshti9spl** [ConnectyCube/connectycube-flutter-samples#33]
**Is your feature request related to a problem? Please describe.**
right now i am unable to get my video/audio call history.

**Describe the solution you'd like**
provide the audio/video call history just like whatsapp

**Describe alternatives you've considered**
right now i am thinking to store details of call into db and show it.

**Additional context**

**Comment by TatankaConCube** [comment]
For this functionality on other platforms, we recommend using the Custom objects feature from CunnectyCube API, but this feature not implemented in our Flutter SDK yet. We have this task in our roadmap and we will release it soon.

**Comment by BhavyKoshti9spl** [comment]
@TatankaConCube 
ok, thanks.

**Comment by TatankaConCube** [comment]
Hello @BhavyKoshti9spl, today we released new version [0.6.0](https://pub.dev/packages/connectycube_sdk/versions/0.6.0) with needed functionality. Now you can realize your functionality using our [Custom objects](https://developers.connectycube.com/server/custom_objects) feature.
