### ISSUE TITLE
Support for WEB flutter

### ISSUE THREAD

**Issue by MohammadEhsanMirzaaee** [ConnectyCube/connectycube-flutter-samples#34]
do you have any SDK for the flutter web?

**Comment by TatankaConCube** [comment]
hello @MohammadEhsanMirzaaee, sorry for the long time answer. No, we don't have Flutter SDK for the web yet. But we have [JavaScript SDK](https://developers.connectycube.com/js/?id=javascript-getting-started) for the web.
