### ISSUE TITLE
Getting notification a call is in progress..after video call was completed

### ISSUE THREAD

**Issue by wrteam-priyansh** [ConnectyCube/connectycube-flutter-samples#40]
In P2P Calls Sample using video call getting notification like a call is in progress, after call was completed 

Flutter doctor -v 
Flutter (Channel stable, 1.22.3, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.22.3 at /home/priyansh/snap/flutter/common/flutter
    • Framework revision 8874f21e79 (3 weeks ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/priyansh/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /home/priyansh/Android/Sdk
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • M2006C3MI (mobile) • 7L8LMVJZNVEY5H8D • android-arm • Android 10 (API 29)

**Comment by TatankaConCube** [comment]
@wrteam-priyansh can you please provide detailed steps, how can we reproduce it on our sample?

**Comment by wrteam-priyansh** [comment]
@TatankaConCube i have run sample application and getting this error
![Screenshot_2020-11-23-12-42-21-462_com connectycube flutter p2p_call_sample](https://user-images.githubusercontent.com/73931541/99949431-0a41c880-2da1-11eb-9ffd-662bdbf32ee3.jpg)

**Comment by TatankaConCube** [comment]
Which branch do you use for tests? Did you do any modifications there?

**Comment by wrteam-priyansh** [comment]
i did not modify anything

**Comment by TatankaConCube** [comment]
It looks like the system notification. We don't show any notifications from our code in the 'master' branch. Which OS do you use? MIUI? Can you reproduce the same behavior on other devices?

**Comment by wrteam-priyansh** [comment]
@TatankaConCube using miui 12.0.3 stable version,
i have tested in other device not getting notification. Maybe issue in MIUI

**Comment by TatankaConCube** [comment]
I think you are right, it can be MIUI, because I didn't see this issue on our Android and iOS devices.
