### ISSUE TITLE
Flutter - method  getDialogs() does not return public dialogs to others users -

### ISSUE THREAD

**Issue by Hemedy** [ConnectyCube/connectycube-flutter-samples#41]
**Specify the sample to which the issue belongs (use [x]):**
[x] Chat sample
[ ] P2P Call sample
[ ] Conference Call sample

**Platform (use [x])**
[x] Android
[x] iOS

**Describe the bug:**
I am using the connectycube flutter sdk, the issue am facing is that when I call method getDialogs() so I can get public dialogs it only return groups a user is added and the ones he created. Please help out.

**Comment by TatankaConCube** [comment]
If your user wants to get public dialogs, he should subscribe to it first. Use [this API](https://developers.connectycube.com/flutter/messaging?id=subscribe-to-public-dialog) for subscription to public dialogs.
