### ISSUE TITLE
Unhandled Exception: SocketException: OS Error: Connection reset by peer, errno = 104, address = chat.connectycube.com, port = 58158

### ISSUE THREAD

**Issue by himanshukh** [ConnectyCube/connectycube-flutter-samples#42]
I'm using Audio and Video call API for flutter. I'm getting this error when application is active mode for some time. Could you help please me to resolve this.

**Comment by TatankaConCube** [comment]
please, provide detailed steps, how can we reproduce this issue on our sample. Please, provide a full log, not only an error message, it will be more helpful.

Additional thing - if you had some issues with the internet connection, you can try using reconnection manager, more details [here](https://developers.connectycube.com/flutter/messaging?id=reconnection)

**Comment by himanshukh** [comment]
> please, provide detailed steps, how can we reproduce this issue on our sample. Please, provide a full log, not only an error message, it will be more helpful.
> 
> Additional thing - if you had some issues with the internet connection, you can try using reconnection manager, more details [here](https://developers.connectycube.com/flutter/messaging?id=reconnection)

This is not an internet connection issue. I'm using connectycube_sdk: ^0.3.0-beta1 version right now. 
If any user available on application for some time user not able to get call or not able to dial a call due to this error. How to check connection and re-login for this version. Please suggest me any solution. Thanks.

**Comment by TatankaConCube** [comment]
without logs, we can't understand, what happens with your internet connection, so, we need them anyway.

one more thing - why you don't use the latest version (at this moment it is [1.0.0](https://pub.dev/packages/connectycube_sdk/versions/1.0.0)) of our SDK?

**Comment by himanshukh** [comment]
Thanks @TatankaConCube. I have upgraded to latest version bu having some issues in IOS version 
**CocoaPods could not find compatible versions for pod "GoogleWebRTC"** 
Is need to upgrade CocoaPods? or can get any solution for this. Please

**Comment by TatankaConCube** [comment]
yes, just run 'pod update' in 'ios' directory

**Comment by himanshukh** [comment]
> yes, just run 'pod update' in 'ios' directory

Thanks. I have run **pod update GoogleWebRTC** and it's working fine now.

**Comment by himanshukh** [comment]
Hi @TatankaConCube I'm again facing issues when application reconnect with internet.

I have used 

CubeChatConnectionSettings chatConnectionSettings = CubeChatConnectionSettings.instance;
    chatConnectionSettings.totalReconnections = 5;     // set 0 to disable internal reconnection manager or value more than 0 to set quantity of times to try to reconnect, default 5 times
    chatConnectionSettings.reconnectionTimeout = 5000;

    Connectivity().onConnectivityChanged.listen((connectivityType) {

      if (connectivityType != ConnectivityResult.none) {
        bool isChatDisconnected = CubeChatConnection.instance.chatConnectionState == CubeChatConnectionState.Closed;

        if (isChatDisconnected && CubeChatConnection.instance.currentUser != null) {
          CubeChatConnection.instance.relogin();
        }
      }
    });

But not able to login again.. Is there any changes in re-login function ?

Please check below log:

[log] D/[Connection]: State: XmppConnectionState.Authenticated
[log] D/[ConnectionNegotiatorManager]: Found matching negotiator true
[log] ---Xmpp Sending:---
[log] <resume xmlns="urn:xmpp:sm:3" h="6" id="86ea396c-c47b-4c12-9876-f7170d2ca21a"/>
[log] D/[ConnectionNegotiatorManager]: ACTIVE FEATURE: {name: StreamManagementModule, name_space: null, priority: 1000, state: NegotiatorState.NEGOTIATING}, isReady: true
[log] D/[ConnectionNegotiatorManager]: Feature Started Parsing
[log] ---Xmpp Receiving:---
I/flutter (13240): CB-SDK: CubeChatConnection: Chat connection ForcefullyClosed
[log] <?xml version='1.0'?><stream:stream xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' from='chat.connectycube.com' id='1528d3fd-e269-4bd4-bc4d-3df06c05a972' version='1.0' xml:lang='en'>
[log] D/[Connection]: processInitialStream
[log] D/[Connection]: Handle secured connection done
[log] D/[Connection]: State: XmppConnectionState.ForcefullyClosed
[log] D/[ReconnectionManager]: Connection forcefully closed!
[log] D/[ReconnectionManager]: TimeOut is: 10000 reconnection counter 0
F/OIC_SRM_DOXM(16342): UpdatePersistentStorage failed!
[log] D/[Connection]: State: XmppConnectionState.Reconnecting
I/flutter (13240): CB-SDK: CubeChatConnection: Chat connection Reconnecting
I/flutter (13240): CB-SDK: CubeChatConnection: Chat connection SocketOpening
[log] D/[Connection]: State: XmppConnectionState.SocketOpening
[log] D/[Connection]: State: XmppConnectionState.SocketOpened
[log] ---Xmpp Sending:---
I/flutter (13240): CB-SDK: CubeChatConnection: Chat connection SocketOpened
[log] <?xml version='1.0'?>
<stream:stream xmlns='jabber:client' version='1.0' xmlns:stream='http://etherx.jabber.org/streams'
to='chat.connectycube.com'
xml:lang='en'
>

Can you please check and update me asap.

Thanks.

**Comment by TatankaConCube** [comment]
@himanshukh in the provided log I can't see any errors after starting reconnection. Please provide a full log with the error.

**Comment by himanshukh** [comment]
> @himanshukh in the provided log I can't see any errors after starting reconnection. Please provide a full log with the error.

Whenever internet off it providing this:

ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: SocketException: OS Error: Software caused connection abort, errno = 103, address = chat.connectycube.com, port = 37726

After internet connected 

![Screenshot 2020-12-03 at 2 26 27 PM](https://user-images.githubusercontent.com/15867195/100995431-c491b680-357d-11eb-8429-b5f45eeecef5.png)


Is this useful or need to provide more logs ?

**Comment by TatankaConCube** [comment]
do you use `Connectivity` for listening connection as you provided in the previous message? looks like you use only default reconnection, and it does not wait for connection and tries to reconnect after the timeout.

**Comment by TatankaConCube** [comment]
> Is this useful or need to provide more logs ?

you said you get this error after reconnection, but provided error only when a lost connection (it is expected). I asked one more time - do you have the same error after the internet connection was established? If yes, please provide a full log.

**Comment by himanshukh** [comment]
> > Is this useful or need to provide more logs ?
> 
> you said you get this error after reconnection, but provided error only when a lost connection (it is expected). I asked one more time - do you have the same error after the internet connection was established? If yes, please provide a full log.

Okay let me share everything what i did.. 

**After off the internet connection:**

[log] D/[Connection]: Handle Secured Error  SocketException: OS Error: Software caused connection abort, errno = 103, address = chat.connectycube.com, port = 40190
[log] D/[Connection]: State: XmppConnectionState.ForcefullyClosed
[log] D/[Connection]: Handle secured connection done
[log] D/[Connection]: State: XmppConnectionState.ForcefullyClosed
[log] D/[ReconnectionManager]: Connection forcefully closed!
I/flutter (12499): CB-SDK: CubeChatConnection: Chat connection ForcefullyClosed
[log] D/[ReconnectionManager]: TimeOut is: 10000 reconnection counter 0
I/flutter (12499): CB-SDK: CubeChatConnection: Chat connection ForcefullyClosed
[log] D/[ReconnectionManager]: Connection forcefully closed!
[log] D/[ReconnectionManager]: TimeOut is: 20000 reconnection counter 1
E/flutter (12499): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: SocketException: OS Error: Software caused connection abort, errno = 103, address = chat.connectycube.com, port = 40190
E/flutter (12499): 
I/flutter (12499): connectivityType ConnectivityResult.none
I/flutter (12499): ConnectivityResult ConnectivityResult
I/ViewRootImpl@31d5d74[MainActivity](12499): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(12499): prepareNavigationBarInfo() DecorView@fea470a[MainActivity]
D/InputMethodManager(12499): getNavigationBarColor() -855310
[log] D/[Connection]: State: XmppConnectionState.Reconnecting
I/flutter (12499): CB-SDK: CubeChatConnection: Chat connection Reconnecting
[log] D/[Connection]: State: XmppConnectionState.SocketOpening
I/flutter (12499): CB-SDK: CubeChatConnection: Chat connection SocketOpening
I/flutter (12499): CB-SDK: CubeChatConnection: Chat connection ForcefullyClosed
[log] E/[Connection]: Socket ExceptionSocketException: Failed host lookup: 'chat.connectycube.com' (OS Error: No address associated with hostname, errno = 7)
[log] D/[Connection]: State: XmppConnectionState.ForcefullyClosed
[log] D/[ReconnectionManager]: Connection forcefully closed!
[log] D/[ReconnectionManager]: TimeOut is: 40000 reconnection counter 2
I/flutter (12499): CB-SDK: CubeChatConnection: Chat connection Reconnecting
[log] D/[Connection]: State: XmppConnectionState.Reconnecting
[log] D/[Connection]: State: XmppConnectionState.SocketOpening
I/flutter (12499): CB-SDK: CubeChatConnection: Chat connection SocketOpening
I/flutter (12499): CB-SDK: CubeChatConnection: Chat connection ForcefullyClosed
[log] E/[Connection]: Socket ExceptionSocketException: Failed host lookup: 'chat.connectycube.com' (OS Error: No address associated with hostname, errno = 7)
[log] D/[Connection]: State: XmppConnectionState.ForcefullyClosed
[log] D/[ReconnectionManager]: Connection forcefully closed!

**After on internet connection repeatedly call:**

[log] D/[Connection]: State: XmppConnectionState.Authenticated
[log] D/[ConnectionNegotiatorManager]: Found matching negotiator true
[log] ---Xmpp Sending:---
[log] <resume xmlns="urn:xmpp:sm:3" h="6" id="7c337792-d00a-489b-b1b4-a69e3d1e500e"/>
[log] D/[ConnectionNegotiatorManager]: ACTIVE FEATURE: {name: StreamManagementModule, name_space: null, priority: 1000, state: NegotiatorState.NEGOTIATING}, isReady: true
[log] D/[ConnectionNegotiatorManager]: Feature Started Parsing
[log] ---Xmpp Receiving:---
I/flutter (12502): CB-SDK: CubeChatConnection: Chat connection ForcefullyClosed
I/flutter (12502): isme check kar555
[log] <?xml version='1.0'?><stream:stream xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' from='chat.connectycube.com' id='b6673e46-d3b3-449b-ac19-19dea8edd8c6' version='1.0' xml:lang='en'>
[log] D/[Connection]: processInitialStream
[log] D/[Connection]: Handle secured connection done
[log] D/[Connection]: State: XmppConnectionState.ForcefullyClosed
[log] D/[ReconnectionManager]: Connection forcefully closed!
[log] D/[ReconnectionManager]: TimeOut is: 10000 reconnection counter 0
I/flutter (12502): CB-SDK: CubeChatConnection: Chat connection Reconnecting
[log] D/[Connection]: State: XmppConnectionState.Reconnecting
I/flutter (12502): isme check kar555
I/flutter (12502): CB-SDK: CubeChatConnection: Chat connection SocketOpening
[log] D/[Connection]: State: XmppConnectionState.SocketOpening
I/flutter (12502): CB-SDK: CubeChatConnection: Chat connection SocketOpened
[log] D/[Connection]: State: XmppConnectionState.SocketOpened
[log] ---Xmpp Sending:---
[log] <?xml version='1.0'?>
<stream:stream xmlns='jabber:client' version='1.0' xmlns:stream='http://etherx.jabber.org/streams'
to='chat.connectycube.com'
xml:lang='en'
>

Okay. Suggest me how i can reconnect to the server so can get calls i'm not able to reconnect after internet connection failed.

**Comment by TatankaConCube** [comment]
hello @himanshukh today we released the [new version](https://pub.dev/packages/connectycube_sdk/changelog), which contains the fixes and improvements for the chat connection, please try it.

If the issue was resolved, please close this ticket.

**Comment by himanshukh** [comment]
Hi @TatankaConCube Thanks for update.. Now it's working fine thanks.
