### ISSUE TITLE
Random Issue: Call screen coming again after reject the call.

### ISSUE THREAD

**Issue by himanshukh** [ConnectyCube/connectycube-flutter-samples#45]
**Specify the sample to which the issue belongs (use [x]):**
[ ] Chat sample
[x] P2P Call sample
[ ] Conference Call sample

**Platform (use [x])**
[x] Android
[x] iOS

**Describe the bug:**
Many times when user1 connect to call with user2 and user2 reject the call, calling screen coming again after 2-3 seconds delay.

**Steps to Reproduce:**
1. Logged in with any user and connect call with other
2. User2 reject the call.
3. Call screen coming again on User2 end.

**Actual result:**
Getting this issue randomly when user reject call, call screen coming again.

**Expected behavior:**
When user reject call, it's mandatory call screen not showing again.

**Comment by TatankaConCube** [comment]
looks like you get dilling packages, which were sent after you sent the reject package, we will investigate, what we can do with this on the SDK side.

**Comment by amarSuthar437** [comment]
Hi @TatankaConCube I'm getting same problem after reject call, after 2-3 second i'm getting same user call again.

**Complete Logs:-**

[log] ---Xmpp Receiving:---
[log] <message id="KHXAJHBXH" type="headline" to="2926194-3869@chat.connectycube.com" xmlns="jabber:client" from="2926197-3869@chat.connectycube.com/flutter_80d190e08fb2cdc3"><extraParams xmlns="jabber:client"><opponentsIDs><opponentID>2926194</opponentID></opponentsIDs><moduleIdentifier>WebRTCVideoChat</moduleIdentifier><callerID>2926197</callerID><callType>2</callType><sessionID>57517ddf-5e94-4eb5-aadd-645efcb40d79</sessionID><signalType>call</signalType><platform>flutter</platform><version_sdk>1.0.0</version_sdk><sdp>v=0
o=- 2640520795539531559 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio
a=msid-semantic: WMS d9f35937-edbf-40f5-b611-253d1688eb65
m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 110 112 113 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:4HyY
a=ice-pwd:rfTOQjskua8IAYK1WTbDOGlW
a=ice-options:trickle renomination
a=fingerprint:sha-256 0E:CF:92:8B:65:E3:51:CF:0F:95:A7:6D:1C:6C:74:5A:93:32:E1:AD:28:DC:5D:CD:0E:EC:F4:39:19:CD:26:27
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:102 ILBC/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:1638831366 cname:EstpqznyDM4LZQMH
a=ssrc:1638831366 msid:d9f35937-edbf-40f5-b611-253d1688eb65 f1d9d103-7cc7-4b1a-b573-820931127f58
a=ssrc:1638831366 mslabel:d9f35937-edbf-40f5-b611-253d1688eb65
a=ssrc:1638831366 label:f1d9d103-7cc7-4b1a-b573-820931127f58
</sdp></extraParams></message>
[log] ---Xmpp Receiving:---
[log] <r xmlns='urn:xmpp:sm:3' />
[log] ---Xmpp Sending:---
I/flutter (13018): CB-SDK: : processIceCandidates, _sdp = CubeRTCSessionDescription: {sessionId = 57517ddf-5e94-4eb5-aadd-645efcb40d79, callerId = 2926197, opponents = {2926194}, conferenceType = 2, userInfo = {}}
I/flutter (13018): CB-SDK: PeerConnection: processIceCandidates, user id = 2926197
[log] <a xmlns="urn:xmpp:sm:3" h="60"/>
[log] ---Xmpp Sending:---
[log] <a xmlns="urn:xmpp:sm:3" h="60"/>
[log] ---Xmpp Receiving:---
[log] <message id="JXOOLHPAD" type="headline" to="2926194-3869@chat.connectycube.com" xmlns="jabber:client" from="2926197-3869@chat.connectycube.com/flutter_80d190e08fb2cdc3"><extraParams xmlns="jabber:client"><opponentsIDs><opponentID>2926194</opponentID></opponentsIDs><moduleIdentifier>WebRTCVideoChat</moduleIdentifier><callerID>2926197</callerID><callType>2</callType><sessionID>57517ddf-5e94-4eb5-aadd-645efcb40d79</sessionID><signalType>iceCandidates</signalType><platform>flutter</platform><version_sdk>1.0.0</version_sdk><iceCandidates><iceCandidate><sdpMLineIndex>0</sdpMLineIndex><sdpMid>audio</sdpMid><candidate>candidate:3397386668 1 udp 2122262783 2405:205:1106:fe54:4b0c:9c26:1011:f320 48371 typ host generation 0 ufrag 4HyY network-id 3 network-cost 900</candidate></iceCandidate></iceCandidates></extraParams></message>
[log] ---Xmpp Receiving:---
[log] <r xmlns='urn:xmpp:sm:3' />
[log] ---Xmpp Sending:---
[log] <a xmlns="urn:xmpp:sm:3" h="62"/>
[log] ---Xmpp Sending:---
[log] <a xmlns="urn:xmpp:sm:3" h="62"/>
I/flutter (13018): CB-SDK: : processIceCandidates, _sdp = CubeRTCSessionDescription: {sessionId = 57517ddf-5e94-4eb5-aadd-645efcb40d79, callerId = 2926197, opponents = {2926194}, conferenceType = 2, userInfo = {}}
I/flutter (13018): CB-SDK: PeerConnection: processIceCandidates, user id = 2926197
[log] ---Xmpp Receiving:---
I/flutter (13018): CB-SDK: : processIceCandidates, _sdp = CubeRTCSessionDescription: {sessionId = 57517ddf-5e94-4eb5-aadd-645efcb40d79, callerId = 2926197, opponents = {2926194}, conferenceType = 2, userInfo = {}}
I/flutter (13018): CB-SDK: PeerConnection: processIceCandidates, user id = 2926197
I/flutter (13018): CB-SDK: : processIceCandidates, _sdp = CubeRTCSessionDescription: {sessionId = 57517ddf-5e94-4eb5-aadd-645efcb40d79, callerId = 2926197, opponents = {2926194}, conferenceType = 2, userInfo = {}}
I/flutter (13018): CB-SDK: PeerConnection: processIceCandidates, user id = 2926197
[log] <message id="YQCXLIHIJ" type="headline" to="2926194-3869@chat.connectycube.com" xmlns="jabber:client" from="2926197-3869@chat.connectycube.com/flutter_80d190e08fb2cdc3"><extraParams xmlns="jabber:client"><opponentsIDs><opponentID>2926194</opponentID></opponentsIDs><moduleIdentifier>WebRTCVideoChat</moduleIdentifier><callerID>2926197</callerID><callType>2</callType><sessionID>57517ddf-5e94-4eb5-aadd-645efcb40d79</sessionID><signalType>iceCandidates</signalType><platform>flutter</platform><version_sdk>1.0.0</version_sdk><iceCandidates><iceCandidate><sdpMLineIndex>0</sdpMLineIndex><sdpMid>audio</sdpMid><candidate>candidate:3397386668 1 udp 2122197247 2405:205:1106:fe54:4b0c:9c26:1011:f320 44676 typ host generation 0 ufrag 4HyY network-id 5 network-cost 900</candidate></iceCandidate></iceCandidates></extraParams></message>
[log] ---Xmpp Receiving:---
[log] <r xmlns='urn:xmpp:sm:3' />
[log] ---Xmpp Sending:---
[log] <a xmlns="urn:xmpp:sm:3" h="64"/>
[log] ---Xmpp Sending:---
[log] <a xmlns="urn:xmpp:sm:3" h="64"/>
[log] ---Xmpp Receiving:---
I/flutter (13018): CB-SDK: : processIceCandidates, _sdp = CubeRTCSessionDescription: {sessionId = 57517ddf-5e94-4eb5-aadd-645efcb40d79, callerId = 2926197, opponents = {2926194}, conferenceType = 2, userInfo = {}}
I/flutter (13018): CB-SDK: PeerConnection: processIceCandidates, user id = 2926197
I/flutter (13018): CB-SDK: : processIceCandidates, _sdp = CubeRTCSessionDescription: {sessionId = 57517ddf-5e94-4eb5-aadd-645efcb40d79, callerId = 2926197, opponents = {2926194}, conferenceType = 2, userInfo = {}}
I/flutter (13018): CB-SDK: PeerConnection: processIceCandidates, user id = 2926197
[log] <message id="ALQRKCCHI" type="headline" to="2926194-3869@chat.connectycube.com" xmlns="jabber:client" from="2926197-3869@chat.connectycube.com/flutter_80d190e08fb2cdc3"><extraParams xmlns="jabber:client"><opponentsIDs><opponentID>2926194</opponentID></opponentsIDs><moduleIdentifier>WebRTCVideoChat</moduleIdentifier><callerID>2926197</callerID><callType>2</callType><sessionID>57517ddf-5e94-4eb5-aadd-645efcb40d79</sessionID><signalType>iceCandidates</signalType><platform>flutter</platform><version_sdk>1.0.0</version_sdk><iceCandidates><iceCandidate><sdpMLineIndex>0</sdpMLineIndex><sdpMid>audio</sdpMid><candidate>candidate:3397386668 1 udp 2122131711 2405:205:1106:fe54:4b0c:9c26:1011:f320 47251 typ host generation 0 ufrag 4HyY network-id 6 network-cost 900</candidate></iceCandidate></iceCandidates></extraParams></message>
[log] ---Xmpp Receiving:---
[log] <r xmlns='urn:xmpp:sm:3' />
[log] ---Xmpp Sending:---
[log] <a xmlns="urn:xmpp:sm:3" h="66"/>
[log] ---Xmpp Sending:---
[log] <a xmlns="urn:xmpp:sm:3" h="66"/>
[log] ---Xmpp Receiving:---
[log] <message id="XNQIKEBWQ" type="headline" to="2926194-3869@chat.connectycube.com" xmlns="jabber:client" from="2926197-3869@chat.connectycube.com/flutter_80d190e08fb2cdc3"><extraParams xmlns="jabber:client"><opponentsIDs><opponentID>2926194</opponentID></opponentsIDs><moduleIdentifier>WebRTCVideoChat</moduleIdentifier><callerID>2926197</callerID><callType>2</callType><sessionID>57517ddf-5e94-4eb5-aadd-645efcb40d79</sessionID><signalType>iceCandidates</signalType><platform>flutter</platform><version_sdk>1.0.0</version_sdk><iceCandidates><iceCandidate><sdpMLineIndex>0</sdpMLineIndex><sdpMid>audio</sdpMid><candidate>candidate:3272336840 1 udp 2122063615 25.19.162.37 38779 typ host generation 0 ufrag 4HyY network-id 4 network-cost 900</candidate></iceCandidate></iceCandidates></extraParams></message>
[log] ---Xmpp Receiving:---
[log] <r xmlns='urn:xmpp:sm:3' />
[log] ---Xmpp Sending:---
[log] <a xmlns="urn:xmpp:sm:3" h="68"/>
[log] ---Xmpp Sending:---
[log] <a xmlns="urn:xmpp:sm:3" h="68"/>
[log] ---Xmpp Receiving:---
[log] <message id="WGBRABRYB" type="headline" to="2926194-3869@chat.connectycube.com" xmlns="jabber:client" from="2926197-3869@chat.connectycube.com/flutter_80d190e08fb2cdc3"><extraParams xmlns="jabber:client"><opponentsIDs><opponentID>2926194</opponentID></opponentsIDs><moduleIdentifier>WebRTCVideoChat</moduleIdentifier><callerID>2926197</callerID><callType>2</callType><sessionID>57517ddf-5e94-4eb5-aadd-645efcb40d79</sessionID><signalType>iceCandidates</signalType><platform>flutter</platform><version_sdk>1.0.0</version_sdk><iceCandidates><iceCandidate><sdpMLineIndex>0</sdpMLineIndex><sdpMid>audio</sdpMid><candidate>candidate:559267639 1 udp 2122005759 ::1 39046 typ host generation 0 ufrag 4HyY network-id 2</candidate></iceCandidate></iceCandidates></extraParams></message>
[log] ---Xmpp Receiving:---
[log] <r xmlns='urn:xmpp:sm:3' />
[log] ---Xmpp Sending:---
[log] <a xmlns="urn:xmpp:sm:3" h="70"/>
[log] ---Xmpp Sending:---
[log] <a xmlns="urn:xmpp:sm:3" h="70"/>
[log] ---Xmpp Receiving:---
[log] <message id="BTUCHGFNX" type="headline" to="2926194-3869@chat.connectycube.com" xmlns="jabber:client" from="2926197-3869@chat.connectycube.com/flutter_80d190e08fb2cdc3"><extraParams xmlns="jabber:client"><opponentsIDs><opponentID>2926194</opponentID></opponentsIDs><moduleIdentifier>WebRTCVideoChat</moduleIdentifier><callerID>2926197</callerID><callType>2</callType><sessionID>57517ddf-5e94-4eb5-aadd-645efcb40d79</sessionID><signalType>iceCandidates</signalType><platform>flutter</platform><version_sdk>1.0.0</version_sdk><iceCandidates><iceCandidate><sdpMLineIndex>0</sdpMLineIndex><sdpMid>audio</sdpMid><candidate>candidate:1510613869 1 udp 2121932543 127.0.0.1 37639 typ host generation 0 ufrag 4HyY network-id 1</candidate></iceCandidate></iceCandidates></extraParams></message>
[log] ---Xmpp Receiving:---
[log] <r xmlns='urn:xmpp:sm:3' />
[log] ---Xmpp Sending:---
[log] <a xmlns="urn:xmpp:sm:3" h="72"/>
[log] ---Xmpp Sending:---
[log] <a xmlns="urn:xmpp:sm:3" h="72"/>
I/flutter (13018): CB-SDK: : processIceCandidates, _sdp = CubeRTCSessionDescription: {sessionId = 57517ddf-5e94-4eb5-aadd-645efcb40d79, callerId = 2926197, opponents = {2926194}, conferenceType = 2, userInfo = {}}
I/flutter (13018): CB-SDK: PeerConnection: processIceCandidates, user id = 2926197
[log] ---Xmpp Receiving:---
[log] <message id="VYGLAPGPU" type="headline" to="2926194-3869@chat.connectycube.com" xmlns="jabber:client" from="2926197-3869@chat.connectycube.com/flutter_80d190e08fb2cdc3"><extraParams xmlns="jabber:client"><opponentsIDs><opponentID>2926194</opponentID></opponentsIDs><moduleIdentifier>WebRTCVideoChat</moduleIdentifier><callerID>2926197</callerID><callType>2</callType><sessionID>57517ddf-5e94-4eb5-aadd-645efcb40d79</sessionID><signalType>iceCandidates</signalType><platform>flutter</platform><version_sdk>1.0.0</version_sdk><iceCandidates><iceCandidate><sdpMLineIndex>0</sdpMLineIndex><sdpMid>audio</sdpMid><candidate>candidate:1876313031 1 tcp 1518025983 ::1 47561 typ host tcptype passive generation 0 ufrag 4HyY network-id 2</candidate></iceCandidate></iceCandidates></extraParams></message>
[log] ---Xmpp Receiving:---
[log] <r xmlns='urn:xmpp:sm:3' />
[log] ---Xmpp Sending:---
[log] <a xmlns="urn:xmpp:sm:3" h="74"/>
[log] ---Xmpp Sending:---
[log] <a xmlns="urn:xmpp:sm:3" h="74"/>
[log] ---Xmpp Sending:---
[log] <r xmlns="urn:xmpp:sm:3"/>
I/flutter (13018): CB-SDK: : processIceCandidates, _sdp = CubeRTCSessionDescription: {sessionId = 57517ddf-5e94-4eb5-aadd-645efcb40d79, callerId = 2926197, opponents = {2926194}, conferenceType = 2, userInfo = {}}
I/flutter (13018): CB-SDK: PeerConnection: processIceCandidates, user id = 2926197
[log] ---Xmpp Receiving:---
I/flutter (13018): CB-SDK: : processIceCandidates, _sdp = CubeRTCSessionDescription: {sessionId = 57517ddf-5e94-4eb5-aadd-645efcb40d79, callerId = 2926197, opponents = {2926194}, conferenceType = 2, userInfo = {}}
I/flutter (13018): CB-SDK: PeerConnection: processIceCandidates, user id = 2926197
I/flutter (13018): CB-SDK: : processIceCandidates, _sdp = CubeRTCSessionDescription: {sessionId = 57517ddf-5e94-4eb5-aadd-645efcb40d79, callerId = 2926197, opponents = {2926194}, conferenceType = 2, userInfo = {}}
I/flutter (13018): CB-SDK: PeerConnection: processIceCandidates, user id = 2926197
[log] <message id="OODLEFLOT" type="headline" to="2926194-3869@chat.connectycube.com" xmlns="jabber:client" from="2926197-3869@chat.connectycube.com/flutter_80d190e08fb2cdc3"><extraParams xmlns="jabber:client"><opponentsIDs><opponentID>2926194</opponentID></opponentsIDs><moduleIdentifier>WebRTCVideoChat</moduleIdentifier><callerID>2926197</callerID><callType>2</callType><sessionID>57517ddf-5e94-4eb5-aadd-645efcb40d79</sessionID><signalType>iceCandidates</signalType><platform>flutter</platform><version_sdk>1.0.0</version_sdk><iceCandidates><iceCandidate><sdpMLineIndex>0</sdpMLineIndex><sdpMid>audio</sdpMid><candidate>candidate:344579997 1 tcp 1517952767 127.0.0.1 46469 typ host tcptype passive generation 0 ufrag 4HyY network-id 1</candidate></iceCandidate></iceCandidates></extraParams></message>
[log] ---Xmpp Receiving:---
[log] <r xmlns='urn:xmpp:sm:3' />
[log] ---Xmpp Sending:---
[log] <a xmlns="urn:xmpp:sm:3" h="76"/>
[log] ---Xmpp Sending:---
[log] <a xmlns="urn:xmpp:sm:3" h="76"/>
[log] ---Xmpp Receiving:---
[log] <message id="AGPJPWFHB" type="headline" to="2926194-3869@chat.connectycube.com" xmlns="jabber:client" from="2926197-3869@chat.connectycube.com/flutter_80d190e08fb2cdc3"><extraParams xmlns="jabber:client"><opponentsIDs><opponentID>2926194</opponentID></opponentsIDs><moduleIdentifier>WebRTCVideoChat</moduleIdentifier><callerID>2926197</callerID><callType>2</callType><sessionID>57517ddf-5e94-4eb5-aadd-645efcb40d79</sessionID><signalType>iceCandidates</signalType><platform>flutter</platform><version_sdk>1.0.0</version_sdk><iceCandidates><iceCandidate><sdpMLineIndex>0</sdpMLineIndex><sdpMid>audio</sdpMid><candidate>candidate:842163049 1 udp 1685855999 157.38.95.253 38779 typ srflx raddr 25.19.162.37 rport 38779 generation 0 ufrag 4HyY network-id 4 network-cost 900</candidate></iceCandidate></iceCandidates></extraParams></message>
[log] ---Xmpp Receiving:---
[log] <r xmlns='urn:xmpp:sm:3' />
[log] ---Xmpp Sending:---
[log] <a xmlns="urn:xmpp:sm:3" h="78"/>
[log] ---Xmpp Sending:---
[log] <a xmlns="urn:xmpp:sm:3" h="78"/>
[log] ---Xmpp Receiving:---
[log] <message id="SMYWVGVEB" type="headline" to="2926194-3869@chat.connectycube.com" xmlns="jabber:client" from="2926197-3869@chat.connectycube.com/flutter_80d190e08fb2cdc3"><extraParams xmlns="jabber:client"><opponentsIDs><opponentID>2926194</opponentID></opponentsIDs><moduleIdentifier>WebRTCVideoChat</moduleIdentifier><callerID>2926197</callerID><callType>2</callType><sessionID>57517ddf-5e94-4eb5-aadd-645efcb40d79</sessionID><signalType>iceCandidates</signalType><platform>flutter</platform><version_sdk>1.0.0</version_sdk><iceCandidates><iceCandidate><sdpMLineIndex>0</sdpMLineIndex><sdpMid>audio</sdpMid><candidate>candidate:1026230121 1 udp 41689087 3.121.84.95 62402 typ relay raddr 157.38.95.253 rport 38779 generation 0 ufrag 4HyY network-id 4 network-cost 900</candidate></iceCandidate></iceCandidates></extraParams></message>
[log] ---Xmpp Receiving:---
[log] <r xmlns='urn:xmpp:sm:3' />
[log] ---Xmpp Sending:---
[log] <a xmlns="urn:xmpp:sm:3" h="80"/>
[log] ---Xmpp Sending:---
[log] <a xmlns="urn:xmpp:sm:3" h="80"/>
[log] ---Xmpp Receiving:---
[log] <a xmlns='urn:xmpp:sm:3' h='6'/>
I/flutter (13018): CB-SDK: : processIceCandidates, _sdp = CubeRTCSessionDescription: {sessionId = 57517ddf-5e94-4eb5-aadd-645efcb40d79, callerId = 2926197, opponents = {2926194}, conferenceType = 2, userInfo = {}}
I/flutter (13018): CB-SDK: PeerConnection: processIceCandidates, user id = 2926197
[log] ---Xmpp Receiving:---
[log] <message id="XUIGCCTLI" type="headline" to="2926194-3869@chat.connectycube.com" xmlns="jabber:client" from="2926197-3869@chat.connectycube.com/flutter_80d190e08fb2cdc3"><extraParams xmlns="jabber:client"><opponentsIDs><opponentID>2926194</opponentID></opponentsIDs><moduleIdentifier>WebRTCVideoChat</moduleIdentifier><callerID>2926197</callerID><callType>2</callType><sessionID>57517ddf-5e94-4eb5-aadd-645efcb40d79</sessionID><signalType>iceCandidates</signalType><platform>flutter</platform><version_sdk>1.0.0</version_sdk><iceCandidates><iceCandidate><sdpMLineIndex>0</sdpMLineIndex><sdpMid>audio</sdpMid><candidate>candidate:2532103853 1 udp 24911615 35.158.208.53 52309 typ relay raddr 157.38.95.253 rport 40045 generation 0 ufrag 4HyY network-id 4 network-cost 900</candidate></iceCandidate></iceCandidates></extraParams></message>
[log] ---Xmpp Receiving:---
[log] <r xmlns='urn:xmpp:sm:3' />
[log] ---Xmpp Sending:---
[log] <a xmlns="urn:xmpp:sm:3" h="82"/>
[log] ---Xmpp Sending:---
[log] <a xmlns="urn:xmpp:sm:3" h="82"/>
[log] ---Xmpp Sending:---
I/flutter (13018): CB-SDK: BaseSession: closeCurrentSession
I/flutter (13018): CB-SDK: BaseSession: _notifySessionClosed
I/flutter (13018): CB-SDK: IncomingCallScreen: _onSessionClosed
[log] <message id="HEHVVRLJF" type="headline" to="2926197-3869@chat.connectycube.com"><extraParams xmlns="jabber:client"><opponentsIDs><opponentID>2926194</opponentID></opponentsIDs><moduleIdentifier>WebRTCVideoChat</moduleIdentifier><callerID>2926197</callerID><callType>2</callType><sessionID>57517ddf-5e94-4eb5-aadd-645efcb40d79</sessionID><signalType>reject</signalType><platform>flutter</platform><version_sdk>1.0.0</version_sdk></extraParams></message>
[log] ---Xmpp Receiving:---
[log] <message id="ORSVTRPRE" type="headline" to="2926194-3869@chat.connectycube.com" xmlns="jabber:client" from="2926197-3869@chat.connectycube.com/flutter_80d190e08fb2cdc3"><extraParams xmlns="jabber:client"><opponentsIDs><opponentID>2926194</opponentID></opponentsIDs><moduleIdentifier>WebRTCVideoChat</moduleIdentifier><callerID>2926197</callerID><callType>2</callType><sessionID>57517ddf-5e94-4eb5-aadd-645efcb40d79</sessionID><signalType>call</signalType><platform>flutter</platform><version_sdk>1.0.0</version_sdk><sdp>v=0
o=- 2640520795539531559 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio
a=msid-semantic: WMS d9f35937-edbf-40f5-b611-253d1688eb65
m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 110 112 113 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:4HyY
a=ice-pwd:rfTOQjskua8IAYK1WTbDOGlW
a=ice-options:trickle renomination
a=fingerprint:sha-256 0E:CF:92:8B:65:E3:51:CF:0F:95:A7:6D:1C:6C:74:5A:93:32:E1:AD:28:DC:5D:CD:0E:EC:F4:39:19:CD:26:27
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:102 ILBC/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:1638831366 cname:EstpqznyDM4LZQMH
a=ssrc:1638831366 msid:d9f35937-edbf-40f5-b611-253d1688eb65 f1d9d103-7cc7-4b1a-b573-820931127f58
a=ssrc:1638831366 mslabel:d9f35937-edbf-40f5-b611-253d1688eb65
a=ssrc:1638831366 label:f1d9d103-7cc7-4b1a-b573-820931127f58
</sdp></extraParams></message>
[log] ---Xmpp Receiving:---
[log] <r xmlns='urn:xmpp:sm:3' />
[log] ---Xmpp Sending:---
[log] <a xmlns="urn:xmpp:sm:3" h="84"/>
[log] ---Xmpp Sending:---
[log] <a xmlns="urn:xmpp:sm:3" h="84"/>
[log] ---Xmpp Sending:---
[log] <r xmlns="urn:xmpp:sm:3"/>
[log] ---Xmpp Receiving:---
[log] <a xmlns='urn:xmpp:sm:3' h='7'/>
[log] D/[StreamManagementModule]: Delivered stanza without id presence
[log] ---Xmpp Sending:---
[log] <r xmlns="urn:xmpp:sm:3"/>
[log] ---Xmpp Receiving:---
[log] <a xmlns='urn:xmpp:sm:3' h='7'/>
I/flutter (13018): CB-SDK: BaseSession: closeCurrentSession
I/flutter (13018): CB-SDK: BaseSession: _notifySessionClosed
[log] ---Xmpp Sending:---
I/flutter (13018): CB-SDK: IncomingCallScreen: _onSessionClosed
[log] <message id="IQFMDEDAM" type="headline" to="2926197-3869@chat.connectycube.com"><extraParams xmlns="jabber:client"><opponentsIDs><opponentID>2926194</opponentID></opponentsIDs><moduleIdentifier>WebRTCVideoChat</moduleIdentifier><callerID>2926197</callerID><callType>2</callType><sessionID>57517ddf-5e94-4eb5-aadd-645efcb40d79</sessionID><signalType>reject</signalType><platform>flutter</platform><version_sdk>1.0.0</version_sdk></extraParams></message>

**Comment by TatankaConCube** [comment]
we will try to improve our internal manager in the next release, thank you for reporting this issue

**Comment by himanshukh** [comment]
@TatankaConCube Thanks for your response. I also want to share one more random issue:

Many times when i started video calling first time after application install, User not able to see video of another user.

**Steps to Reproduce:**

1. Logged in with any user and connect video call with other (Example User1 call to User2)
2. User1 not able to see video of User2 (This is a random issue).
3. When any user cancel the call and reconnect to user, it'll works fine.

Please check this also.

Thanks.

**Comment by TatankaConCube** [comment]
>  first time after application install, 

the possible reason for this issue can be permission for camera and microphone, did you provide them before starting the call?

**Comment by TatankaConCube** [comment]
@himanshukh today we released the [new version](https://pub.dev/packages/connectycube_sdk/changelog), which contains the fix for your issue, please try it.

If the issue was resolved, please close this ticket.

**Comment by himanshukh** [comment]
@TatankaConCube Thanks for the update.. Have you changed your source code or it'll work after package update?

**Comment by TatankaConCube** [comment]
Just update version of our SDK in your project to **^1.1.0**

**Comment by himanshukh** [comment]
> Just update version of our SDK in your project to **^1.1.0**

Thanks for this.. Working fine for me.
