### ISSUE TITLE
how to implement call busy logic?

### ISSUE THREAD

**Issue by ShyamKrishna122** [ConnectyCube/connectycube-flutter-samples#48]

**Comment by wrteam-priyansh** [comment]
@ShyamKrishna122 you can store call details in database when call is in process and when call finish  delete the call related data.so before making call you check for call details for other user and if you find call details in database that means user is busy in call..
hope i am making sense

**Comment by TatankaConCube** [comment]
additionally to @wrteam-priyansh  solution you can use additional parameters when you reject the call, it can looks like `callSession.reject({"reason": "BUSY"});` and on the caller side in the callback `onCallRejectedByUser` you can check this parameter like:
```dart
_callSession.onCallRejectedByUser = _onCallRejectedByUser;

void _onCallRejectedByUser(P2PSession session, int userId, Map<String, String> userInfo) {
    if (userInfo.isNotEmpty && userInfo.containsKey("reason")) {
        String reason = userInfo["reason"];

        if (reason == "BUSY") {
            // user is busy, do needed actions
        }
    }
}
```

**Comment by ShyamKrishna122** [comment]
Thank you guys but what will userInfo contains?

**Comment by TatankaConCube** [comment]
it will cantains data which you send in `callSession.reject({"reason": "BUSY"});` when busy user does reject

**Comment by ShyamKrishna122** [comment]
Thank you I will try implementing it
