### ISSUE TITLE
CB-SDK: PeerConnection: IceConnectionState change to RTCIceConnectionState.RTCIceConnectionState Failed for opponent in 

### ISSUE THREAD

**Issue by wrteam-priyansh** [ConnectyCube/connectycube-flutter-samples#49]
What is the reason behind this.. This is happens when user open app through notification and attend call and after some seconds i get above mention error or message and call ended for caller....

**Comment by ShyamKrishna122** [comment]
How to implement push notifications for video call?

**Comment by wrteam-priyansh** [comment]
@ShyamKrishna122 i am sending notification(call) to the receiver person using fcm and receiver get notification to attend the call.
i know this is not best approach but i have achieved this.

**Comment by TatankaConCube** [comment]
[here](https://developers.connectycube.com/flutter/videocalling?id=receive-a-call-in-background) short guide, how to implement background call in Flutter using our SDK

**Comment by ShyamKrishna122** [comment]
I want a sample code for implementing push notification for video call

**Comment by wrteam-priyansh** [comment]
@TatankaConCube CB-SDK: PeerConnection: IceConnectionState change to RTCIceConnectionState.RTCIceConnectionState Failed for opponent...what is the reason behind this error. is it because of poor internet?

**Comment by TatankaConCube** [comment]
it means you have some problems with establishing a connection between peers, it can happen when peers didn't exchange with icecandidates, or something happen with internet connection after/during an exchange with icecandodates

**Comment by TatankaConCube** [comment]
On which step do you get this error?

**Comment by wrteam-priyansh** [comment]
@TatankaConCube after attending the call opposition's screen(camera view) becomes white screen for sometime and i get this error and call cuts automatically(For caller). This usually happens when attending the call first time in application then work as expected

**Comment by TatankaConCube** [comment]
Should be fixed in the latest (1.1.1) release. Closing. If the issue still reproduces, please create a new ticket with details.
