### ISSUE TITLE
Can not convert cubeSession into jsonString using json.encode()..

### ISSUE THREAD

**Issue by wrteam-priyansh** [ConnectyCube/connectycube-flutter-samples#50]
In order to save cubeSession into local storage i need to convert it into jsonString..
Here is my code :

Map<String,dynamic> jsonSession = cubeSession.toJson();
String jsonString = json.encode(jsonSession)
------------
getting following error
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Converting object to an encodable object failed: Instance of 'CubeUser'

**Comment by TatankaConCube** [comment]
@wrteam-priyansh thank you for reporting this issue, we will fix it in the next version of our SDK

**Comment by wrteam-priyansh** [comment]
@TatankaConCube i have solved this issue by converting DateTime into toIso8601String

**Comment by TatankaConCube** [comment]
it does not completely resolve your issue, in this case, the field `tokenExpirationDate` will not be saved to json. Just wait new release, we plan to do this today or tomorrow.

**Comment by wrteam-priyansh** [comment]
Ok

**Comment by TatankaConCube** [comment]
Or you can add it manually to your `jsonSession`, and set it after decoding the json

**Comment by wrteam-priyansh** [comment]
Yes I have added manually

**Comment by TatankaConCube** [comment]
today we released a [new version](https://pub.dev/packages/connectycube_sdk/changelog), which contains the fix for your issue, please try it.

If your issue was resolved, please close this ticket.
