### ISSUE TITLE
How to integrate ringtone at calling time?

### ISSUE THREAD

**Issue by himanshukh** [ConnectyCube/connectycube-flutter-samples#53]
How to user know call is coming? So i need to add a ringtone whenever call coming and off ring when user finish the call. If there is any method to implement it please share.

Thanks.

**Comment by TatankaConCube** [comment]
Sorry, but this feature not related to Connectycube API or SDK. For the implementation of this feature, you need a plugin for playing audio files and suitable audio files. You can start playing when the Incoming screen opens and stop playing when the Incoming screen stops.

**Comment by himanshukh** [comment]
> Sorry, but this feature not related to Connectycube API or SDK. For the implementation of this feature, you need a plugin for playing audio files and suitable audio files. You can start playing when the Incoming screen opens and stop playing when the Incoming screen stops.

Okay thanks.. Actually i was thinking if there is any method created from your side.
