### ISSUE TITLE
How to get userInfo on callClient.onReceiveNewSession = (incomingCallSession) {  };   

### ISSUE THREAD

**Issue by sunishrai** [ConnectyCube/connectycube-flutter-samples#54]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by TatankaConCube** [comment]
you can get it via `Map<String, String> userInfo = incomingCallSession.cubeSdp.userInfo;`

**Comment by sunishrai** [comment]
Thanx it's  working fine.
