### ISSUE TITLE
Issue in ios push notification subscription

### ISSUE THREAD

**Issue by sunishrai** [ConnectyCube/connectycube-flutter-samples#56]
CB-SDK: : [subscribe] subscription ERROR: ResponseException: 422: {"errors":{"client_identification_sequence":["is invalid"]}}

**Specify the sample to which the issue belongs (use [x]):**
[ ] Chat sample
[ ] P2P Call sample
[ ] Conference Call sample

**Platform (use [x])**
[ ] Android
[ ] iOS

**Device info**
Manufacture: 
Model: 
OS version:

**Describe the bug:**

**Steps to Reproduce:**
1. 
2.
3.
4.

**Logs:**
```
log here
```
or
[Gist log](https://gist.github.com/)

**Actual result:**

**Expected behavior:**

**Additional info**

**Comment by TatankaConCube** [comment]
This error means you set a not valid token for the subscription.

Please provide logs with the creation subscription request and response. It will help us to understand your issue.

**Comment by sunishrai** [comment]
requset :

{"notification_channel":"apns","device":{"udid":"787E56E1-1AE7-41D3-83A1-5556028E7449","platform":"ios"},"push_token":{"environment":"development","client_identification_sequence":"f6QVAvlWUU4Gorp8G3n5D3:APA91bECli8gjaU5nlTZ1UDrwvh3AaBGK5ig1CtByd3L35ZmOm2k-n1bWHsFk5bMkHxNvAwbQZYzMeLPLSgKAFI8t9DG3zFEnB9mMP2_UqNxxjH8Xdgef4K9jsIHT9aU9KQJL81kh8Hk","bundle_identifier":"com.packagename"}}

response:
 {"errors":{"client_identification_sequence":["is invalid"]}}
flutter:
flutter: CB-SDK: : [subscribe] subscription ERROR: ResponseException: 422: {"errors":{"client_identification_sequence":["is invalid"]}}

**Comment by sunishrai** [comment]
resolve using apns token
