### ISSUE TITLE
Does the SDK support background call on iOS and  Android?

### ISSUE THREAD

**Issue by rafekun** [ConnectyCube/connectycube-flutter-samples#57]
I looked around the document, but could not find any articles about background call.

**Comment by TatankaConCube** [comment]
@rafekun there [short guide](https://developers.connectycube.com/flutter/videocalling?id=receive-a-call-in-background), how to implement background calls using ConnectyCube Flutter SDK

**Comment by rafekun** [comment]
@TatankaConCube Thanks for your quick reply!
What I really want to know is whether the calling can be running when the app is background.

**Comment by TatankaConCube** [comment]
Support chat connection in the background all time is a bad solution for app performance and battery lifetime. A better solution for this is to close the chat connection when the app in the background and use push notifications for notifying opponents about new calls.

**Comment by rafekun** [comment]
So, connectycube does not support background calls?


2021年1月4日(月) 19:22 TatankaConCube <notifications@github.com>:

**Comment by TatankaConCube** [comment]
Supports via push notifications. It is common practice, iOS has a special type of push notifications for it (APNS_VOIP).

**Comment by rafekun** [comment]
Ok, Thanks 😊


2021年1月4日(月) 20:10 TatankaConCube <notifications@github.com>:
