### ISSUE TITLE
The method 'startCall' isn't defined

### ISSUE THREAD

**Issue by oussamaelhajoui** [ConnectyCube/connectycube-flutter-samples#58]
**Specify the sample to which the issue belongs (use [x]):**
[ ] Chat sample
[ ] P2P Call sample
[x] Conference Call sample

**Platform (use [x])**
[ ] Android
[x] iOS

**Device info**
Manufacture: Apple
Model: Iphone SE
OS version: 13.3.1

**Describe the bug:**
The library does not export the method/class startCall

**Steps to Reproduce:**
1. import 'package:connectycube_sdk/connectycube_sdk.dart'; 
2. create a call session with your user id and calltype audio
3. join a dialog with a room number
4. use the following method  inside the `then` block of `joinDialog`:  `startCall('1', publishers,
              _callSession.currentUserId);`
              

**Logs:**
```
The method 'startCall' isn't defined for the type '_BodyLayoutState'.
Try correcting the name to the name of an existing method, or defining a method named 'startCall'
```

**Actual result:**
Can't start a call

**Expected behavior:**
Should know the method as i am following documentation.

**Comment by TatankaConCube** [comment]
@oussamaelhajoui please look to our [Conference Calls sample](https://github.com/ConnectyCube/connectycube-flutter-samples/tree/master/conf_call_sample) for getting an example of work with our SDK.
