### ISSUE TITLE
Showing START CALL NULL in IOS

### ISSUE THREAD

**Issue by sathvikrijo** [ConnectyCube/connectycube-flutter-samples#6]
throwing the error as "start call null" in the console after accepting the call or trying to start the call in IOS. Help me

**Comment by TatankaConCube** [comment]
hello @sathvikrijo, please provide us full log from flutter console from app start to getting this issue (from caller and receiver side).

**Comment by ydiev** [comment]
Hi @TatankaConCube, I receive the same issue on iOS. However, to be sure that it works on Android I tested it on 2 simulators Pixel 2 (Linux Mint) it worked well. 
Here is my console log from iOS code (Mac):

Performing hot restart...
Syncing files to device iPhone 8...
Restarted application in 1,485ms.
flutter: CB-SDK: : =========================================================
flutter: === REQUEST ==== c9174e18-abaa-476b-8f62-f81ce6ff3aa2 ===
flutter: REQUEST
flutter:   POST https://api.connectycube.com/session
flutter: HEADERS
flutter:   {Content-type: application/json, ConnectyCube-REST-API-Version: 0.1.1, CB-SDK: Flutter 0.2.0-beta3, CB-Token: }
flutter: BODY
flutter:   {"application_id":"xxxx","auth_key":"xxx","nonce":"xxxx","timestamp":"1592313266","signature":"7d21cd4c8ec67836bcba4dfd4867f27000d4f057","user":{"login":"ralitsagmail","password":"xxxx"}}
flutter:
flutter: CB-SDK: : *********************************************************
flutter: *** RESPONSE *** 201 *** c9174e18-abaa-476b-8f62-f81ce6ff3aa2 ***
flutter: HEADERS
flutter:   {connection: keep-alive, cache-control: max-age=0, private, must-revalidate, set-cookie: _mkra_ctxt=158af090916e8bde4125d4ceee1bbc86--201; path=/; max-age=5; HttpOnly; secure, status: 201 Created, transfer-encoding: chunked, date: Tue, 16 Jun 2020 13:14:26 GMT, access-control-allow-origin: *, strict-transport-security: max-age=31536000,max-age=15768000;, content-type: application/json; charset=utf-8, x-xss-protection: 1; mode=block, server: nginx/1.16.1, x-request-id: cb61b20f-c7fa-4348-9c51-5e85269b6faa, cb-token-expirationdate: 2020-06-16 15:14:25 UTC, connectycube-rest-api-version: 0.1.1, x-runtime: 0.048613, etag: W/"e1044e03a0137b39c5950433a7556fac", x-frame-options: SAMEORIGIN, x-content-type-options: nosniff}
flutter: BODY
flutter:   {"session":{"id":14334260,"user_id":1437351,"application_id":xxxx,"nonce":xxxx,"token":"62dac0f22694e95ccbaef23eeb98798e74000a13","ts":1592313266,"created_at":"2020-06-16T13:14:26Z","updated_at":"2020-06-16T13:14:26Z","user":{"id":1437351,"full_name":"User 1","email":"email@example.com","login":"ralitsagmail","phone":"","website":null,"created_at":"2020-05-28T13:00:24Z","updated_at":"2020-06-16T13:14:26Z","last_request_at":"2020-06-16T13:14:26Z","external_user_id":null,"facebook_id":null,"twitter_id":null,"blob_id":null,"custom_data":"","avatar":"","user_tags":null}}}
flutter:
flutter: sending: <?xml version='1.0'?>
<stream:stream xmlns='jabber:client' version='1.0' xmlns:stream='http://etherx.jabber.org/streams'
to='chat.connectycube.com'
xml:lang='en'
>
flutter: State: XmppConnectionState.ReceivingFeatures
flutter: CB-SDK: : Chat connection ReceivingFeatures
flutter: response: <xmpp_stone><?xml version='1.0'?><stream:stream xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' from='chat.connectycube.com' id='8dc3fb4d-01ea-4d03-a646-76d9f2969c41' version='1.0' xml:lang='en'></stream></xmpp_stone>
flutter: <xmpp_stone><?xml version='1.0'?><stream:stream xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' from='chat.connectycube.com' id='8dc3fb4d-01ea-4d03-a646-76d9f2969c41' version='1.0' xml:lang='en'></stream></xmpp_stone>
flutter: response: <xmpp_stone><stream:features><sm xmlns="urn:xmpp:sm:3"/><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism><mechanism>ANONYMOUS</mechanism><mechanism>PLAIN_FAST</mechanism></mechanisms><ver xmlns="urn:xmpp:features:rosterver"/><starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"/><compression xmlns="http://jabber.org/features/compress"><method>zlib</method></compression></stream:features></xmpp_stone>
flutter: <xmpp_stone><stream:features><sm xmlns="urn:xmpp:sm:3"/><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism><mechanism>ANONYMOUS</mechanism><mechanism>PLAIN_FAST</mechanism></mechanisms><ver xmlns="urn:xmpp:features:rosterver"/><starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"/><compression xmlns="http://jabber.org/features/compress"><method>zlib</method></compression></stream:features></xmpp_stone>
flutter: Negotating features
flutter: negotiating starttls
flutter: sending: <starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"/>
flutter: Feature Started Parsing
flutter: response: <xmpp_stone><proceed xmlns="urn:ietf:params:xml:ns:xmpp-tls"/></xmpp_stone>
flutter: <xmpp_stone><proceed xmlns="urn:ietf:params:xml:ns:xmpp-tls"/></xmpp_stone>
flutter: startSecureSocket
flutter: XmppConnectionState.ReceivingFeatures
flutter: sending: <?xml version='1.0'?>
<stream:stream xmlns='jabber:client' version='1.0' xmlns:stream='http://etherx.jabber.org/streams'
to='chat.connectycube.com'
xml:lang='en'
>
flutter: response: <xmpp_stone><?xml version='1.0'?><stream:stream xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' from='chat.connectycube.com' id='8dc3fb4d-01ea-4d03-a646-76d9f2969c41' version='1.0' xml:lang='en'></stream></xmpp_stone>
flutter: <xmpp_stone><?xml version='1.0'?><stream:stream xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' from='chat.connectycube.com' id='8dc3fb4d-01ea-4d03-a646-76d9f2969c41' version='1.0' xml:lang='en'></stream></xmpp_stone>
flutter: response: <xmpp_stone><stream:features><sm xmlns="urn:xmpp:sm:3"/><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism><mechanism>ANONYMOUS</mechanism><mechanism>PLAIN_FAST</mechanism></mechanisms><ver xmlns="urn:xmpp:features:rosterver"/><compression xmlns="http://jabber.org/features/compress"><method>zlib</method></compression></stream:features></xmpp_stone>
flutter: <xmpp_stone><stream:features><sm xmlns="urn:xmpp:sm:3"/><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism><mechanism>ANONYMOUS</mechanism><mechanism>PLAIN_FAST</mechanism></mechanisms><ver xmlns="urn:xmpp:features:rosterver"/><compression xmlns="http://jabber.org/features/compress"><method>zlib</method></compression></stream:features></xmpp_stone>
flutter: Negotating features
flutter: sending: <auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="PLAIN">ADE0MzczNTEtMjU3OQAxcTJ3M2U0cjV0Nnk=</auth>
flutter: Feature Started Parsing
flutter: response: <xmpp_stone><success xmlns="urn:ietf:params:xml:ns:xmpp-sasl"/></xmpp_stone>
flutter: <xmpp_stone><success xmlns="urn:ietf:params:xml:ns:xmpp-sasl"/></xmpp_stone>
flutter: sending: <?xml version='1.0'?>
<stream:stream xmlns='jabber:client' version='1.0' xmlns:stream='http://etherx.jabber.org/streams'
to='chat.connectycube.com'
xml:lang='en'
>
flutter: State: XmppConnectionState.Authenticated
flutter: CB-SDK: : Chat connection Authenticated
flutter: DONE PARSING FATURES
flutter: State: XmppConnectionState.DoneParsingFeatures
flutter: CB-SDK: : Chat connection DoneParsingFeatures
flutter: response: <xmpp_stone><?xml version='1.0'?><stream:stream xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' from='chat.connectycube.com' id='8dc3fb4d-01ea-4d03-a646-76d9f2969c41' version='1.0' xml:lang='en'></stream></xmpp_stone>
flutter: <xmpp_stone><?xml version='1.0'?><stream:stream xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' from='chat.connectycube.com' id='8dc3fb4d-01ea-4d03-a646-76d9f2969c41' version='1.0' xml:lang='en'></stream></xmpp_stone>
flutter: response: <xmpp_stone><stream:features><sm xmlns="urn:xmpp:sm:3"/><mobile xmlns="http://tigase.org/protocol/mobile#v2"/><ver xmlns="urn:xmpp:features:rosterver"/><compression xmlns="http://jabber.org/features/compress"><method>zlib</method></compression><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"/><session xmlns="urn:ietf:params:xml:ns:xmpp-session"/></stream:features></xmpp_stone>
flutter: <xmpp_stone><stream:features><sm xmlns="urn:xmpp:sm:3"/><mobile xmlns="http://tigase.org/protocol/mobile#v2"/><ver xmlns="urn:xmpp:features:rosterver"/><compression xmlns="http://jabber.org/features/compress"><method>zlib</method></compression><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"/><session xmlns="urn:ietf:params:xml:ns:xmpp-session"/></stream:features></xmpp_stone>
flutter: Negotating features
flutter: sending: <iq id="UGCPYVXVO" type="set">
<bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"/>
</iq>
flutter: Feature Started Parsing
flutter: response: <xmpp_stone><iq id="UGCPYVXVO" xmlns="jabber:client" type="result" to="1437351-xxxx@chat.connectycube.com/1204607085-chat-12004"><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"><jid>1437351-xxxx@chat.connectycube.com/1204607085-chat-12004</jid></bind></iq></xmpp_stone>
flutter: <xmpp_stone><iq id="UGCPYVXVO" xmlns="jabber:client" type="result" to="1437351-xxxx@chat.connectycube.com/1204607085-chat-12004"><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"><jid>1437351-xxxx@chat.connectycube.com/1204607085-chat-12004</jid></bind></iq></xmpp_stone>
flutter: sending: <iq id="OQKNMAPNR" type="set" to="chat.connectycube.com">
<session xmlns="urn:ietf:params:xml:ns:xmpp-session"/>
</iq>
flutter: Feature Started Parsing
flutter: response: <xmpp_stone><iq id="OQKNMAPNR" xmlns="jabber:client" type="result" from="chat.connectycube.com" to="1437351-xxxx@chat.connectycube.com/1204607085-chat-12004"/></xmpp_stone>
flutter: <xmpp_stone><iq id="OQKNMAPNR" xmlns="jabber:client" type="result" from="chat.connectycube.com" to="1437351-xxxx@chat.connectycube.com/1204607085-chat-12004"/></xmpp_stone>
flutter: State: XmppConnectionState.SessionInitialized
flutter: CB-SDK: : Chat connection SessionInitialized
flutter: sending: <iq id="LNSMRVXXF" type="get" from="1437351-xxxx@chat.connectycube.com/1204607085-chat-12004" to="chat.connectycube.com">
<query xmlns="http://jabber.org/protocol/disco#info"/>
</iq>
flutter: DONE PARSING FATURES
flutter: State: XmppConnectionState.DoneParsingFeatures
flutter: CB-SDK: : Chat connection DoneParsingFeatures
flutter: response: <xmpp_stone><iq id="LNSMRVXXF" xmlns="jabber:client" type="result" from="chat.connectycube.com" to="1437351-xxxx@chat.connectycube.com/1204607085-chat-12004"><query xmlns="http://jabber.org/protocol/disco#info"><identity type="im" category="component" name="App Chat ver. 2.1.0-0"/><identity type="im" category="server" name="App Chat ver. 2.1.0-0"/><feature var="http://jabber.org/protocol/commands"/><feature var="urn:xmpp:carbons:2"/><feature var="http://jabber.org/protocol/stats"/><feature var="http://jabber.org/protocol/amp"/><feature var="msgoffline"/><feature var="http://jabber.org/protocol/disco#info"/><feature var="http://jabber.org/protocol/disco#items"/><feature var="urn:xmpp:ping"/><feature var="urn:ietf:params:xml:ns:xmpp-sasl"/><feature var="jabber:iq:roster"/><feature var="jabber:iq:roster-dynamic"/><feature var="jabber:iq:privacy"/><feature var="urn:ietf:params:xml:ns:xmpp-bind"/><feature var="http://jabber.org/protocol/commands"/><feature var="jabber:iq:last"/><f<…>
flutter: <xmpp_stone><iq id="LNSMRVXXF" xmlns="jabber:client" type="result" from="chat.connectycube.com" to="1437351-xxxx@chat.connectycube.com/1204607085-chat-12004"><query xmlns="http://jabber.org/protocol/disco#info"><identity type="im" category="component" name="App Chat ver. 2.1.0-0"/><identity type="im" category="server" name="App Chat ver. 2.1.0-0"/><feature var="http://jabber.org/protocol/commands"/><feature var="urn:xmpp:carbons:2"/><feature var="http://jabber.org/protocol/stats"/><feature var="http://jabber.org/protocol/amp"/><feature var="msgoffline"/><feature var="http://jabber.org/protocol/disco#info"/><feature var="http://jabber.org/protocol/disco#items"/><feature var="urn:xmpp:ping"/><feature var="urn:ietf:params:xml:ns:xmpp-sasl"/><feature var="jabber:iq:roster"/><feature var="jabber:iq:roster-dynamic"/><feature var="jabber:iq:privacy"/><feature var="urn:ietf:params:xml:ns:xmpp-bind"/><feature var="http://jabber.org/protocol/commands"/><feature var="jabber:iq:last"/><feature var<…>
flutter: State: XmppConnectionState.DoneServiceDiscovery
flutter: sending: <iq id="HXTTODYAJ" type="get">
<query xmlns="jabber:iq:roster"/>
</iq>
flutter: sending: <presence/>
flutter: CB-SDK: : Chat connection DoneServiceDiscovery
flutter: response: <xmpp_stone><iq id="HXTTODYAJ" xmlns="jabber:client" type="result" to="1437351-xxxx@chat.connectycube.com/1204607085-chat-12004"><query xmlns="jabber:iq:roster"/></iq></xmpp_stone>
flutter: <xmpp_stone><iq id="HXTTODYAJ" xmlns="jabber:client" type="result" to="1437351-xxxx@chat.connectycube.com/1204607085-chat-12004"><query xmlns="jabber:iq:roster"/></iq></xmpp_stone>
flutter: RosterListChanged: []
flutter: response: <xmpp_stone><presence xmlns="jabber:client" from="1437351-xxxx@chat.connectycube.com/1204607085-chat-12004" to="1437351-xxxx@chat.connectycube.com"/></xmpp_stone>
flutter: <xmpp_stone><presence xmlns="jabber:client" from="1437351-xxxx@chat.connectycube.com/1204607085-chat-12004" to="1437351-xxxx@chat.connectycube.com"/></xmpp_stone>
flutter: No id found for stanza
flutter: CB-SDK: : start call null

**Comment by TatankaConCube** [comment]
hello guys, thank you for reported issue. Please don't filter logs. Instead of it collect full logs from both sides (caller and receiver) and send them to support@connectycube.com if you don't want show private data on github. In subject of letter please set title from this issue.

**Comment by ydiev** [comment]
Hi, I just want to mention that I tested it on a physical iOS device and it worked well. However, it didn't work on iOS simulators. iPhone 8 and iPhone SE.

**Comment by TatankaConCube** [comment]
Did you test another apps with WebRTC calls on iOS emulators? 
"flutter: CB-SDK: : start call null" just means you start call without `userInfo` parameter. Then SDK tries get local media stream and as it appears unsuccessfully.

**Comment by TatankaConCube** [comment]
Seems there is no much activity out there. Closing the issue as stale. If it’s still actual - please raise a new one.
