### ISSUE TITLE
Please update your example project to support incoming call in background and killed mode. 

### ISSUE THREAD

**Issue by KashishVerma** [ConnectyCube/connectycube-flutter-samples#61]

**Comment by DaveLomber** [comment]
@KashishVerma thank you for your feedback 

The CallKit integration is going to happen on Feb 1st part of the month 

Will keep you posted

**Comment by TatankaConCube** [comment]
In our roadmap, this feature planned after implementing push notifications in the Chat sample.

**Comment by KashishVerma** [comment]
> @KashishVerma thank you for your feedback
> 
> The CallKit integration is going to happen on Feb 1st part of the month
> 
> Will keep you posted

thank you 😃

**Comment by TatankaConCube** [comment]
Implemented in the latest version. Closing...
