### ISSUE TITLE
getDialog return item list only at 1970.1.19 microsecond time stamp.

### ISSUE THREAD

**Issue by xspire** [ConnectyCube/connectycube-flutter-samples#62]
**Specify the sample to which the issue belongs (use [x]):**
[x] Chat sample
[ ] P2P Call sample
[ ] Conference Call sample

**Platform (use [x])**
[x] Android
[x] iOS

**Device info**
Manufacture: apple, lg
Model: iphone 11, lg g7
OS version: ios 14.1, android 10

**Describe the bug:**
For flutter chat sample.
I try to getting dialog list with created time parameter before or after. But with DateTime.now().microsecondsSinceEpoch, no item is returned.
I also try with DateTime.fromMicrosecondsSinceEpoch(1583402980), it return all items with 100 item unit.
1583402980 is parsed to time 1970.1.19 xx xxx
I want to get chat room list created within 10 minute lately.

**Steps to Reproduce:**
1. Make new dialog chat room.
1. DateTime nowt = DateTime.now();
2. nowt = nowt.subtract(Duration(minute: 10));
3. Map<String, dynamic> additionalParams = {
        "created_at[gt]": nowt.millisecondsSinceEpoch
      };
4. getDialogs(additionalParams).then((dialogs){ ... });

**Actual result:**
no list 

**Expected behavior:**
Dialog list within the last 10 minutes

**Comment by TatankaConCube** [comment]
@xspire thank you for your question, we will check and answer you soon.

**Comment by TatankaConCube** [comment]
@xspire  for fixing your issue use timestamp in seconds instead of milliseconds:
```dart
Map<String, dynamic> additionalParams = {
        "created_at[gt]": nowt.millisecondsSinceEpoch/1000
};
```

**Comment by xspire** [comment]
> @xspire for fixing your issue use timestamp in seconds instead of milliseconds:
> 
> ```dart
> Map<String, dynamic> additionalParams = {
>         "created_at[gt]": nowt.millisecondsSinceEpoch/1000
> };
> ```

@TatankaConCube
Thank you very much. 
I fix this bug with your reply.

**Comment by TatankaConCube** [comment]
Fixed. Closing...
