### ISSUE TITLE
[Question] Using push notifications with conference calls

### ISSUE THREAD

**Issue by Max-Might** [ConnectyCube/connectycube-flutter-samples#66]
Hello. I see that the P2P example is updated to support push notifications.

But is it possible to use push notifications with conference calls?
If yes, then are push notifications sent all participants or only to those who are offline?

**Comment by TatankaConCube** [comment]
hello @Max-Might. You can use the Push notifications feature according to your needs. Sure, you can use it for Conference calls too. You can send push notifications for all users, but online users will just ignore them.

**Comment by Max-Might** [comment]
Ok, Cool!

From the push notification callback, how can you tell if the current user is online or not?

**Comment by TatankaConCube** [comment]
Do you want to know the user's status before the call? for it, you can use  
```dart
    CubeChatConnection.instance.getLasUserActivity(userId).then((seconds) {
      if(seconds == 0){
        // user online
      } else {
        // user offline
      }
    }).catchError((onError) {
      // user never log in to the chat or another error
    });
```

**Comment by TatankaConCube** [comment]
For identification conference call you can use own UUID instead of `joinRoomId = currentUser.id.toString()`  [this code](https://github.com/ConnectyCube/connectycube-flutter-samples/blob/master/conf_call_sample/lib/src/select_opponents_screen.dart#L186):
```dart
  void _startCall(Set<int> opponents) async {
    if (opponents.isEmpty) return;
    _currentCall = await _callClient.createCallSession(currentUser.id);

    String roomId = Uuid().v4();
    Navigator.push(
      context,
      MaterialPageRoute(
        builder: (context) => ConversationCallScreen(_currentCall, roomId, opponents.toList(), false),
      ),
    );
  }
```
And next in code use this field as identification for the call session.

**Comment by Max-Might** [comment]
@TatankaConCube thanks, that worked.

I have one more question regarding conference calls.
It is about the case when the app is in the killed state and it receives a new call and the user accepts the call.

Now, in this case the call state is persisted as 'accepted' and the app is started.
But when the app is started it does not know about the incoming call, I guess that the information was already sent on the system channel when the app was killed so it did not receive it. Do you know what we can do in this case?

**Comment by TatankaConCube** [comment]
If you are using our [connectycube-flutter-call-kit](https://github.com/ConnectyCube/connectycube-flutter-call-kit), you can get a call state like in our [P2P calls sample](https://github.com/ConnectyCube/connectycube-flutter-samples/blob/master/p2p_call_sample/lib/src/managers/call_manager.dart#L241). But in the current realization of this plugin we don't save call data and for receiving the same call few times, you can add periodical sending the call requests from the [CallManager](https://github.com/ConnectyCube/connectycube-flutter-samples/blob/master/conf_call_sample/lib/src/utils/call_manager.dart).

**Comment by Max-Might** [comment]
I made it so that when the app gets the `accept` callback from `connectycube-flutter-call-kit` it saves the call data in SharedPreferences and when it is automatically started it checks if there is a pending call and if yes it accepts it and deletes the data from SharedPreferences.

Do you think this is a viable solution?

**Comment by TatankaConCube** [comment]
@Max-Might I found the mistake in the naming of callbacks in the `connectycube-flutter-call-kit`  and callback `onCallAcceptedWhenTerminated` will be called when call was rejected when the app was in a terminated state (will fix it in the next release). I'm not sure, that you will get an event to the `accept` callback when the app was killed, but you can try it.

**Comment by Max-Might** [comment]
Yeah, I noticed it the naming discrepancy for the `onCallAcceptedWhenTerminated` method.
Also, looking at the code it seems to be called every time and not (as the name suggests) only when the app is terminated (headless mode).

I also found another small problem but I am not sure if the problem is in my code or in the library.
On Android the first time the app receives a call everything works fine. You can accept or reject the call.
But the second (or every time after the first) time it receives a call the notification is displayed but there is no ringing sound.
