### ISSUE TITLE
Activation link is never sent when account created

### ISSUE THREAD

**Issue by trey-rosius** [ConnectyCube/connectycube-flutter-samples#67]
Hi, 
i apologize for submitting this issue here, but i've tried registering for an account on the connectycube website for about a week now to no avail. I never receive any activation link. What should i do ?
Can you please help me ?

**Comment by DaveLomber** [comment]
@trey-rosius could you please check the SPAM folder of your email box, there should be an email, and then mark as not a spam.

Recently ConnectyCube got some SCAM attack, which resulted in some emails from ConnectyCube go to SPAM.

The proper remedies were already applied, and the overall situation should be improved over the upcoming week 

Appologize for this inconvenience

**Comment by trey-rosius** [comment]
Thanks. You are correct. All the mails went straight to SPAM.
Got it now
