### ISSUE TITLE
Cant receive new session after turn off and turn on again mobile data

### ISSUE THREAD

**Issue by caspereus** [ConnectyCube/connectycube-flutter-samples#7]
In my case , when user reconnect internet user will not get incoming call and cant call user again

**Comment by TatankaConCube** [comment]
hello @caspereus, this issue related with Connectycube Flutter SDK features, possible solution you can found [here](https://github.com/ConnectyCube/connectycube-flutter-sdk-releases/issues/3#issuecomment-646499998).

**Comment by TatankaConCube** [comment]
today we released a new version, please find out our [documentation](https://developers.connectycube.com/flutter/messaging?id=reconnection) to organize reconnection logic in your app

**Comment by TatankaConCube** [comment]
@caspereus any updates here?

**Comment by TatankaConCube** [comment]
Seems there is no much activity out there. Closing the issue as stale. If it’s still actual - please raise a new one.
