### ISSUE TITLE
No action is taken when we try to answer call.

### ISSUE THREAD

**Issue by vipulbansal** [ConnectyCube/connectycube-flutter-samples#71]
[ ] P2P Call sample

[ ] Android

**Device info**
Manufacture: Samsung
Model: f41
OS version: 11

We are trying to use your flutter sdk in our mobile app but we are encountering some issues like no action is being taken when we try to answer call on receiver end. I think the main issue we are encountering is with call manager. So, I initialised it with global context as but its still not working:
GlobalKey<NavigatorState> globalKey=GlobalKey();
MaterialApp(
        debugShowCheckedModeBanner: false,
        title: 'Flutter Demo',
        navigatorKey: globalKey,
)
DashboardScreen.routeName: (ctx) => Builder(
    builder: (context) {
      CallManager.instance.init(globalKey.currentState.context);
      return DashboardScreen();}),

What am I doing wrong? Please suggest.

**Comment by TatankaConCube** [comment]
which actions do you run for accepting the call? Do you start `ConversationCallScreen` and make `_callSession.acceptCall();` as in our example?

**Comment by trey-rosius** [comment]
Hi, i'm facing this same issue. Conversation screen doesn't open, when i click on accept in push notification or when i accept call in incoming screen.The app just opens, but it doesn't navigate to conversation screen

**Comment by TatankaConCube** [comment]
@trey-rosius which device are you using for tests? which steps to reproduce this issue on your side?

**Comment by trey-rosius** [comment]
I'm using an emulated pixel 4(api 30) and a physical device(REDMi note 8 pro). Here's what i've noticed
`  void acceptCall(String sessionId) {

    print("accepted");

    ConnectycubeFlutterCallKit.setOnLockScreenVisibility(isVisible: true);
    if (_currentCall != null) {
      print("We in here ");
      if (context != null) {
        print("context isn't null ");
        Navigator.pushReplacement(
          context,
          MaterialPageRoute(
            builder: (context) => ConversationCallScreen(_currentCall, true),
          ),
        );
      }
    } else {

     
      _callsMap[sessionId] = CallState.ACCEPTED;
    }

  }`
All the print statements get printed, when i click on accept call on push notification
`I/flutter (23823): accepted
I/flutter (23823): We in here 
I/flutter (23823): context isn't null `

But the navigation doesn't open. And if i change Navigator.pushReplacement to Navigator.push, i get this error
` [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Navigator operation requested with a context that does not include a Navigator.
E/flutter (23823): The context used to push or pop routes from the Navigator must be that of a widget that is a descendant of a Navigator widget.`
so i think the issue is with the context

**Comment by TatankaConCube** [comment]
> i think the issue is with the context

yes, you are right. Do you reproduce it in our sample without any changes (except your own configuration)?

**Comment by TatankaConCube** [comment]
can you please share here output on the command `flutter doctor`?

**Comment by trey-rosius** [comment]
Your sample works perfectly.And i just copied all the code from it. Here's the output of flutter docotor
`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 2.0.0, on macOS 11.1 20C69 darwin-x64, locale en-CM)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Connected device (3 available)

! Doctor found issues in 1 category.
`

**Comment by trey-rosius** [comment]
I forgot to wrap my main screen around a builder . Sorry for bothering you . It works well now
```
Builder(
               builder: (ctx){
                 CallManager.instance.init(ctx);
                 return SplashScreen();
               },
 ),
```

**Comment by TatankaConCube** [comment]
guys, If your issue was resolved, please close this ticket. If you have other issues/questions, create a new one with details.

**Comment by vipulbansal** [comment]
I will close the ticket

**Comment by vipulbansal** [comment]
Hi, thanks. The issue was related to context of CallManager.instance.init. Its been solved. Thanks to you. Great work, connecty cube, clearly best video call sdk in flutter at present.
