### ISSUE TITLE
Flutter Connnectycube SDK doesn't store description or name field of new dialogs

### ISSUE THREAD

**Issue by GRyabkin** [ConnectyCube/connectycube-flutter-samples#75]
I create dialog using api method `createDialog(newDialog)`. I fill the description or name field for the new CubeDialog. But when I fetch dialogs using api method `getDialogs()` returned items don't have the description or name I have set for them.

Is it a bug or feature?

-----------------------
```
var newDialogParams = UpdateDialogParams();
newDialogParams.newName = dialogName;
updateDialog(createdDialog.dialogId, newDialogParams.getUpdateDialogParams())
```

Doesn't work as well, but according to logs everything is fine:

> I/flutter (25991): === REQUEST ==== eb69f978-413c-4b76-a319-5990f9ae1b38 ===
> I/flutter (25991): REQUEST
> I/flutter (25991):   PUT https://api.connectycube.com/chat/Dialog/60789b7dca8bf42af4f6abf2 
> I/flutter (25991): HEADERS
> I/flutter (25991):   {Content-type: application/json, ConnectyCube-REST-API-Version: 0.1.1, CB-SDK: Flutter 1.1.3, CB-Token: ---masked---}
> I/flutter (25991): BODY
> I/flutter (25991):   {"name":"3968471-714-3968471"}
> I/flutter (25991): *** RESPONSE *** 200 *** eb69f978-413c-4b76-a319-5990f9ae1b38 ***

**Comment by TatankaConCube** [comment]
> Is it a bug or feature?

no, it is not a feature))) All dialog data should be saved during dialog creation. Please provide us a full log with dialog creation/fetching without any filter

**Comment by GRyabkin** [comment]
> I/flutter (11966): CB-SDK: : =========================================================
> I/flutter (11966): === REQUEST ==== 7cfd8aba-f188-4699-8e08-5bf61382bb72 ===
> I/flutter (11966): REQUEST
> I/flutter (11966):   POST https://api.connectycube.com/chat/Dialog 
> I/flutter (11966): HEADERS
> I/flutter (11966):   {Content-type: application/json, ConnectyCube-REST-API-Version: 0.1.1, CB-SDK: Flutter 1.1.3, CB-Token: --masked--}
> I/flutter (11966): BODY
> I/flutter (11966):   {"name":"3968471-714-3968471","type":3,"occupants_ids":[3991697,3968471]}
> I/flutter (11966): 
> [log] ---Xmpp Sending:---
> [log] <r xmlns="urn:xmpp:sm:3"/>
> [log] ---Xmpp Receiving:---
> [log] <a xmlns='urn:xmpp:sm:3' h='6'/>
> I/flutter (11966): CB-SDK: : *********************************************************
> I/flutter (11966): *** RESPONSE *** 201 *** 7cfd8aba-f188-4699-8e08-5bf61382bb72 ***
> I/flutter (11966): HEADERS
> I/flutter (11966):   {connection: keep-alive, cache-control: max-age=0, private, must-revalidate, set-cookie: _mkra_ctxt=3453dd8f26aefce6488ebd6b7938323b--201; path=/; max-age=5; HttpOnly; secure, status: 201 Created, transfer-encoding: chunked, date: Fri, 16 Apr 2021 12:13:02 GMT, access-control-allow-origin: *, strict-transport-security: max-age=31536000,max-age=15768000;, content-type: application/json; charset=utf-8, x-xss-protection: 1; mode=block, server: nginx/1.16.1, x-request-id: 574559f8-93c4-44b4-95e5-49ef4088136c, cb-token-expirationdate: 2021-04-16 14:12:48 UTC, connectycube-rest-api-version: 0.1.1, x-runtime: 0.086415, etag: W/"8fd771cd642ee324b668d1ab8884aae8", x-frame-options: SAMEORIGIN, x-content-type-options: nosniff}
> I/flutter (11966): BODY
> I/flutter (11966):   {"_id":"60797f4eca8bf40b91f69c0d","admins_ids":[],"created_at":"2021-04-16T12:13:02Z","description":null,"last_message":null,"last_message_date_sent":null,"last_message_id":null,"last_message_user_id":null,"name":"gena@test.by","occupants_ids":[3968471,3991697],"photo":null,"pinned_messages_ids":[],"type":3,"updated_at":"2021-04-16T12:13:02Z","user_id":3991697,"unread_messages_count":0,"xmpp_room_jid":null}
> 
> I/flutter (11966): CB-SDK: : =========================================================
> I/flutter (11966): === REQUEST ==== 7a4306c2-9f07-448f-a8d6-db7b2b0c1124 ===
> I/flutter (11966): REQUEST
> I/flutter (11966):   GET https://api.connectycube.com/chat/Dialog 
> I/flutter (11966): HEADERS
> I/flutter (11966):   {Content-type: application/json, ConnectyCube-REST-API-Version: 0.1.1, CB-SDK: Flutter 1.1.3, CB-Token: --masked--}
> I/flutter (11966): BODY
> I/flutter (11966):   
> I/flutter (11966): 
> [log] ---Xmpp Receiving:---
> [log] <a xmlns='urn:xmpp:sm:3' h='52'/>
> I/flutter (11966): CB-SDK: : *********************************************************
> I/flutter (11966): *** RESPONSE *** 200 *** 7a4306c2-9f07-448f-a8d6-db7b2b0c1124 ***
> I/flutter (11966): HEADERS
> I/flutter (11966):   {connection: keep-alive, cache-control: max-age=0, private, must-revalidate, set-cookie: _mkra_ctxt=0a962ba23f1f59cd09444a73b159a316--200; path=/; max-age=5; HttpOnly; secure, status: 200 OK, transfer-encoding: chunked, date: Fri, 16 Apr 2021 12:15:03 GMT, access-control-allow-origin: *, strict-transport-security: max-age=31536000,max-age=15768000;, content-type: application/json; charset=utf-8, x-xss-protection: 1; mode=block, server: nginx/1.16.1, x-request-id: ac203bd0-147a-4a7a-b715-06ef17af4817, cb-token-expirationdate: 2021-04-16 14:12:49 UTC, connectycube-rest-api-version: 0.1.1, x-runtime: 0.028003, etag: W/"dabc1e352e03930a56fbe7c7e6e2f954", x-frame-options: SAMEORIGIN, x-content-type-options: nosniff}
> I/flutter (11966): BODY
> I/flutter (11966):   {"total_entries":2,"skip":0,"limit":100,"items":[{"_id":"607852aaca8bf43fb8f7b679","admins_ids":[],"created_at":"2021-04-15T14:50:18Z","description":null,"last_message":"asdasdka;sldk ;asdk a;sdk a;skda;skda;sdka;sd","last_message_date_sent":1618575291,"last_message_id":"60797fbbaee160c297e35552","last_message_user_id":3991697,"name":"gena@test.by","occupants_ids":[3968471,3991697],"photo":"","pinned_messages_ids":[],"type":3,"updated_at":"2021-04-16T12:14:52Z","user_id":3991697,"unread_messages_count":0,"xmpp_room_jid":null},{"_id":"60797f4eca8bf40b91f69c0d","admins_ids":[],"created_at":"2021-04-16T12:13:02Z","description":null,"last_message":null,"last_message_date_sent":null,"last_message_id":null,"last_message_user_id":null,"name":"gena@test.by","occupants_ids":[3968471,3991697],"photo":"","pinned_messages_ids":[],"type":3,"updated_at":"2021-04-16T12:13:02Z","user_id":3991697,"unread_messages_count":0,"xmpp_room_jid":null}]}

**Comment by TatankaConCube** [comment]
> {"name":"3968471-714-3968471","type":3,"occupants_ids":[3991697,3968471]}

according to your logs, you create private dialog without a description and your result is expected in this case

**Comment by GRyabkin** [comment]
Yes. Because this time I tried to change dialogs name, maybe you see this in logs as well? Why new name didn't apply?

**Comment by TatankaConCube** [comment]
for private chats server calculates it dynamically, it puts opponent name as dialog's name for private dialogs

**Comment by GRyabkin** [comment]
> for private chats server calculates it dynamically, it puts opponent name as dialog's name for private dialogs

ok. I see. Here are the logs of an attempt to set a description. Is it also automatically reset by the server?

I/flutter (28391): CB-SDK: : =========================================================
I/flutter (28391): === REQUEST ==== 19e7f8aa-5e07-486f-b11b-0925b0543c9f ===
I/flutter (28391): REQUEST
I/flutter (28391):   GET https://api.connectycube.com/chat/Dialog 
I/flutter (28391): HEADERS
I/flutter (28391):   {Content-type: application/json, ConnectyCube-REST-API-Version: 0.1.1, CB-SDK: Flutter 1.1.3, CB-Token: ---masked---}
I/flutter (28391): BODY
I/flutter (28391):   
I/flutter (28391): 
I/flutter (28391): CB-SDK: : *********************************************************
I/flutter (28391): *** RESPONSE *** 200 *** 19e7f8aa-5e07-486f-b11b-0925b0543c9f ***
I/flutter (28391): HEADERS
I/flutter (28391):   {connection: keep-alive, cache-control: max-age=0, private, must-revalidate, set-cookie: _mkra_ctxt=780d612667519c38a65baae79cdccfc2--200; path=/; max-age=5; HttpOnly; secure, status: 200 OK, transfer-encoding: chunked, date: Fri, 16 Apr 2021 13:23:58 GMT, access-control-allow-origin: *, strict-transport-security: max-age=31536000,max-age=15768000;, content-type: application/json; charset=utf-8, x-xss-protection: 1; mode=block, server: nginx/1.16.1, x-request-id: e03c08a8-041f-48b2-b0d3-57fe7491592c, cb-token-expirationdate: 2021-04-16 15:23:46 UTC, connectycube-rest-api-version: 0.1.1, x-runtime: 0.042139, etag: W/"c3a79492b9f886253c6649a913be479e", x-frame-options: SAMEORIGIN, x-content-type-options: nosniff}
I/flutter (28391): BODY
I/flutter (28391):   {"total_entries":8,"skip":0,"limit":100,"items":[{"_id":"607852aaca8bf43fb8f7b679","admins_ids":[],"created_at":"2021-04-15T14:50:18Z","description":null,"last_message":"😀😃","last_message_date_sent":1618577814,"last_message_id":"607989968fd0da22b484194d","last_message_user_id":3991697,"name":"gena@test.by","occupants_ids":[3968471,3991697],"photo":"","pinned_messages_ids":[],"type":3,"updated_at":"2021-04-16T12:56:55Z","user_id":3991697,"unread_messages_count":0,"xmpp_room_jid":null},{"_id":"60797f4eca8bf40b91f69c0d","admins_ids":[],"created_at":"2021-04-16T12:13:02Z","description":null,"last_message":null,"last_message_date_sent":null,"last_message_id":null,"last_message_user_id":null,"name":"gena@test.by","occupants_ids":[3968471,3991697],"photo":"","pinned_messages_ids":[],"type":3,"updated_at":"2021-04-16T12:13:02Z","user_id":3991697,"unread_messages_count":0,"xmpp_room_jid":null},{"_id":"6079842eca8bf42af4f78b4a","admins_ids":[],"created_at":"2021-04-16T12:33:50Z","description":null,"last_messag
I/flutter (28391): 
I/flutter (28391): CB-SDK: : =========================================================
I/flutter (28391): === REQUEST ==== 9f1fde8d-cc37-4436-9f53-764633b78284 ===

> I/flutter (28391): REQUEST
> I/flutter (28391):   POST https://api.connectycube.com/chat/Dialog 
> I/flutter (28391): HEADERS
> I/flutter (28391):   {Content-type: application/json, ConnectyCube-REST-API-Version: 0.1.1, CB-SDK: Flutter 1.1.3, CB-Token: ---masked---}
> I/flutter (28391): BODY
> I/flutter (28391):   {"type":3,"description":"3968471-714-3968471","occupants_ids":[3991697,3968471]}
> I/flutter (28391): 
> [log] ---Xmpp Sending:---
> [log] <r xmlns="urn:xmpp:sm:3"/>
> [log] ---Xmpp Receiving:---
> [log] <a xmlns='urn:xmpp:sm:3' h='6'/>
> I/flutter (28391): CB-SDK: : *********************************************************
> I/flutter (28391): *** RESPONSE *** 201 *** 9f1fde8d-cc37-4436-9f53-764633b78284 ***
> I/flutter (28391): HEADERS
> I/flutter (28391):   {connection: keep-alive, cache-control: max-age=0, private, must-revalidate, set-cookie: _mkra_ctxt=b3129be9eab264c8959daed022b705ad--201; path=/; max-age=5; HttpOnly; secure, status: 201 Created, transfer-encoding: chunked, date: Fri, 16 Apr 2021 13:23:59 GMT, access-control-allow-origin: *, strict-transport-security: max-age=31536000,max-age=15768000;, content-type: application/json; charset=utf-8, x-xss-protection: 1; mode=block, server: nginx/1.16.1, x-request-id: a669adf3-9bea-4c46-b82d-ddcd2c74ecae, cb-token-expirationdate: 2021-04-16 15:23:46 UTC, connectycube-rest-api-version: 0.1.1, x-runtime: 0.062016, etag: W/"7bb9d4ad3b7ebc9de75e34d5bda50594", x-frame-options: SAMEORIGIN, x-content-type-options: nosniff}
> I/flutter (28391): BODY
> I/flutter (28391):   {"_id":"60798fefca8bf475e4f6addc","admins_ids":[],"created_at":"2021-04-16T13:23:59Z","description":null,"last_message":null,"last_message_date_sent":null,"last_message_id":null,"last_message_user_id":null,"name":"gena@test.by","occupants_ids":[3968471,3991697],"photo":null,"pinned_messages_ids":[],"type":3,"updated_at":"2021-04-16T13:23:59Z","user_id":3991697,"unread_messages_count":0,"xmpp_room_jid":null}

**Comment by GRyabkin** [comment]
My main problem is that I want to store meta-string composed from occupants id's and some id of my application item as an indicator of unique dialog, yes I have a way of storing it on my own server, fetch it, use it in a filter, etc. I saw those params, as name/description/customData and thought that maybe I could utilise them but there's no code-docs that I am not allowed to use them in private 1-to-1 dialogs

**Comment by TatankaConCube** [comment]
'customData' is the better way for storing metadata for dialogs, it doesn't depend on dialog type. In the current realization of Dialogs API, you can't save the description for private dialogs, but we plan to update it next week and the new Dialogs API supports 'description' field for private dialogs.

**Comment by GRyabkin** [comment]
I just have checked that name/description works great with GROUP type. I will try with custom data, anyway I have the solution to convert it to the group type temporarily anyway my app doesn't provide an option to edit chats for users. 

Nice. I will keep my eye on the updates. 

Thanks for your quick responses.
