### ISSUE TITLE
Rejoin same conference call stoped the video stream of rejoined user to other users. 

### ISSUE THREAD

**Issue by RehanAshraf786** [ConnectyCube/connectycube-flutter-samples#78]
P2P Call sample
Conference Call sample

-Android
-iOS

 User exit from conference call and then he rejoin the same conference call. Other users which are in same conference call not able to see the video of rejoined user. "void _addRemoteMediaStream(session, int userId, MediaStream stream) {}" function is  not called for other members when user rejoined conference call. Due to which rejoined user stream  is not updated to other member of that call. However all users videos are fine for rejoined user end

1. start a conference call  with 2 or more users
2. leave one user from the conference call 
3. rejoin the same conference call  by same user which leaved the call.
4. Rejoined  user can see the live videos of all users but other users not able see the video of rejoined user.

**Actual result:**
Other users in the video conference  call not able to see the video of user who rejoin the video conference call.

This function is not called for others user when a user exit and rejoin the same conference call.
 void _addRemoteMediaStream(session, int userId, MediaStream stream) {
    log("_addLocalMediaStream for user $userId", TAG);
    _onStreamAdd(userId, stream);
  }

**Comment by usama333** [comment]
how to connect two mobile i'm facing this issue

**Comment by TatankaConCube** [comment]
we found the issue on the SDK side, we will publish the fix today later, thank you for reporting this problem

**Comment by RehanAshraf786** [comment]
Its working now, Thanks for the latest fixed
