### ISSUE TITLE
The default Firebase app already exists. This means you called initializeApp() more than once without providing an app name as the second argument.

### ISSUE THREAD

**Issue by trey-rosius** [ConnectyCube/connectycube-flutter-samples#79]
**Specify the sample to which the issue belongs (use [x]):**
[ ] Chat sample
[x ] P2P Call sample
[ ] Conference Call sample

**Platform (use [x])**
[ x] Android
[ x] iOS

**Device info**
Manufacture: 
Model: 
OS version:

**Describe the bug:**
After signing in with phone number on firebase, calling this line of code signInUsingFirebase(Config.projectID, token) ,
throws the following error
`
errors":{"base":["The default Firebase app already exists. This means you called initializeApp() more than once without providing an app name as the second argument. In most cases you only need to call initializeApp() once. But if you do want to initialize multiple apps, pass a second argument to initializeApp() to give each app a unique name."
`

`
 firebaseAuth.signInWithCredential(phoneAuthCredential).whenComplete(() {
       print("accounts have been linked");
       ScaffoldMessenger.of(context).removeCurrentSnackBar();

       User user = firebaseAuth.currentUser;
       if(user != null){

         print(user.displayName);

         return firebaseAuth.idTokenChanges().listen((firebaseUser) async {
           if(firebaseUser != null){
             // Get JWT from Firebase
             String token = await firebaseUser.getIdToken();
             print("token is "+ token);

             if(!isEmpty(token)){

              return createSession()
                   .then((cubeSession){
                print("cube user id we are here");
                return signInUsingFirebase(Config.projectID, token).then((cubeUser) {

`

**Comment by DaveLomber** [comment]
Thank you for reporting the issue

We are investigating the root cause 

Will update here with more info

**Comment by DaveLomber** [comment]
@trey-rosius  we have deployed the patch 
Could you please check at your side and let us know whether the issue is resolved

**Comment by trey-rosius** [comment]
thanks a lot, the issue has been resolved.
