### ISSUE TITLE
Question? is there any way to know if receiver's phone is ringing

### ISSUE THREAD

**Issue by raj457036** [ConnectyCube/connectycube-flutter-samples#80]
Just like WhatsApp is there any way to know if the receiver's phone is ringing?

**Comment by TatankaConCube** [comment]
@raj457036 we don't have feature ready for using you for this feature, but you can use the [System messages](https://developers.connectycube.com/flutter/messaging?id=system-messages) feature if the receiver is logged in to the chat at the moment of receiving the call. Or use the [Push notifications](https://developers.connectycube.com/flutter/push-notifications) feature if the receiver not logged in to the chat. For implementation, this feature receiver just should send a notification to the caller after receiving the call event.

**Comment by raj457036** [comment]
Humm okay!
