### ISSUE TITLE
Response code 422 was occurred, when use  uploadAddressBook() function

### ISSUE THREAD

**Issue by xspire** [ConnectyCube/connectycube-flutter-samples#81]
**Specify the sample to which the issue belongs (use [x]):**
[X] Chat sample
[X] P2P Call sample
[ ] Conference Call sample

**Platform (use [x])**
[X] Android
[X] iOS

**Describe the bug:**
After call to uploadAddressBook() function,  Exception was occured with " RESPONSE *** 422 *** " as below.

Well done before. I tried the address book synchronization again and find exception yesterday.
I don't know why the error occurred.

Captured log messages is as below.
I replace name and phone number with xxxx, 01012341234 for this question.

**Steps to Reproduce:**
1. call uploadAddressBook().then ...

**Logs:**
```
I/flutter (14471): CB-SDK: : =========================================================
I/flutter (14471): === REQUEST ==== 7d34b51d-54f2-4ba5-877d-1641fc28155c ===
I/flutter (14471): REQUEST
I/flutter (14471):   POST https://api.connectycube.com/address_book 
I/flutter (14471): HEADERS
I/flutter (14471):   {Content-type: application/json, ConnectyCube-REST-API-Version: 0.1.1, CB-SDK: Flutter 1.1.4-dev.1, CB-Token: xxxxxxxxxxxxxxxxxxxxxxxxxxxx}
I/flutter (14471): BODY
I/flutter (14471):   {"contacts":[{"name":"xxxx","phone":"01012341234"},{"name":"xxxx","phone":"01012341234"},{"name":"xxxx","phone":"01012341234"},{"name":"xxxx","phone":"01012341234"},{"name":"xxxx","phone":"01012341234"},{"name":"xxxx","phone":"01012341234"},{"name":"Kbs1921x","phone":"8201044445556"},{"name":"정수강","phone":"01064020546 ...

I/flutter (14471): 
I/flutter (14471): CB-SDK: : *********************************************************
I/flutter (14471): *** RESPONSE *** 422 *** 7d34b51d-54f2-4ba5-877d-1641fc28155c ***
I/flutter (14471): HEADERS
I/flutter (14471):   {connection: keep-alive, content-type: application/json; charset=utf-8, date: Tue, 11 May 2021 06:54:25 GMT, strict-transport-security: max-age=15768000; includeSubDomains, content-length: 65, server: nginx/1.16.1}
I/flutter (14471): BODY
I/flutter (14471):   {"errors":{"base":["Update document requires atomic operators"]}}
I/flutter (14471): 
I/flutter (14471): CB-SDK: : Error at uploadAddressBook() : ResponseException: 422: {"errors":{"base":["Update document requires atomic operators"]}}
```

**Comment by TatankaConCube** [comment]
notified backend team about it, will back to you with updates later

**Comment by TatankaConCube** [comment]
@xspire please check now

**Comment by xspire** [comment]
@TatankaConCube 

One more issue.

When call getDialogs() function, Response error code 200 is occurred as log below.

I/flutter (29847): CB-SDK: : getDialogs after 2021-05-10T23:27:49.000
I/flutter (29847): CB-SDK: : =========================================================
I/flutter (29847): === REQUEST ==== 5ab105f6-948f-4eae-95d9-2e2687889513 ===
I/flutter (29847): REQUEST
I/flutter (29847):   GET https://api.connectycube.com/chat/Dialog?created_at[gt]=1620656869.0&sort_asc=created_at 
I/flutter (29847): HEADERS
I/flutter (29847):   {Content-type: application/json, ConnectyCube-REST-API-Version: 0.1.1, CB-SDK: Flutter 1.1.4-dev.1, CB-Token: 85DBD2935CF7A3A2C95E16107B08DAD09838}
I/flutter (29847): BODY
I/flutter (29847):   
I/flutter (29847): 
[log] ---Xmpp Sending:---
[log] <r xmlns="urn:xmpp:sm:3"/>
[log] ---Xmpp Receiving:---
[log] <a xmlns='urn:xmpp:sm:3' h='5'/>
[log] ---Xmpp Sending:---
[log] <r xmlns="urn:xmpp:sm:3"/>
[log] ---Xmpp Receiving:---
[log] <a xmlns='urn:xmpp:sm:3' h='5'/>
I/flutter (29847): CB-SDK: : *********************************************************
I/flutter (29847): *** RESPONSE *** 200 *** 5ab105f6-948f-4eae-95d9-2e2687889513 ***
I/flutter (29847): HEADERS
I/flutter (29847):   {cb-token-expirationdate: 2021-05-11 18:29:18 UTC, connection: keep-alive, date: Tue, 11 May 2021 16:29:18 GMT, content-length: 1120, strict-transport-security: max-age=15768000; includeSubDomains, content-type: application/json; charset=utf-8, server: nginx/1.16.1}
I/flutter (29847): BODY
I/flutter (29847):   {"total_entries":2,"skip":0,"limit":100,"items":[{"_id":"xxxxxxxx","user_id":12341234,"created_at":"2021-05-07T15:07:05Z","updated_at":"2021-05-07T15:07:41Z","name":"xxxx","description":"xxxx","type":2,"occupants_ids":[12341234,23452345],"occupants_count":2,"xmpp_room_jid":"xxxxx","is_e2ee":false,"admins_ids":[],"last_message":"{msgtype: ...
