### ISSUE TITLE
Difficulty in following Messaging api documentation for flutter

### ISSUE THREAD

**Issue by Vrihas123** [ConnectyCube/connectycube-flutter-samples#9]
Please provide a flutter code sample having messaging api integrated so that it is easy for developers to understand the code and can implement in their projects. The current documentation does not contain any flutter code sample for messaging api. Thank you

**Comment by TatankaConCube** [comment]
hello @Vrihas123, we tried to make api in Flutter the same as for other platforms. With which API in Flutter do you have problems?

**Comment by Vrihas123** [comment]
Messaging API. The codes are present in the documentation but it's not clear where I have to write that code in my project.

**Comment by Vrihas123** [comment]
Please provide a flutter code sample project having messaging API integrated so that it is easy to understand and implement. Thank you.

**Comment by TatankaConCube** [comment]
We added Chat sample app in our roadmap. We will present it as soon as possible.

**Comment by TatankaConCube** [comment]
happy to inform you guys, today we released our realization of a simple example of a [Chatting app](https://github.com/ConnectyCube/connectycube-flutter-samples/tree/master/chat_sample) which demonstrates, how to use ConnectyCube Flutter SDK for the implementation chat functionality in your app.
