### ISSUE TITLE
P2P call sample does not work when build iOS ipa (release mode)

### ISSUE THREAD

**Issue by soleilpqd** [ConnectyCube/connectycube-flutter-samples#91]
**Specify the sample to which the issue belongs (use [x]):**
[ ] Chat sample
[x] P2P Call sample
[ ] Conference Call sample

**Platform (use [x])**
[ ] Android
[x] iOS

**Env**
Flutter 1.22.6

**Device info**
Manufacture: Apple
Model: iPhone 11 + iPad
OS version: 13.3.1

**Describe the bug:**

Admin side:
- I uploaded APNS Production certificate (p12).
- Add 2 users.

App (iOS):
- Change our profiles ... to build app.
- Change configs.dart with our app info + users.

When I execute the sample project in debug mode (from flutter or hit run in XCode), app works well (I can make audio/video call between 2 devices).

Now I use XCode to export app to ipa file, remove debug app in devices, install the new ipa, login, make call, the other device does not receive the call.

I remove app on 1 device, run app in debug mode on it (device A). I keep app in relese mode on other device (device B). When i make call from device A, device B does not receive. But when I make call from device B, device A still receive the call.

I tried to upload all type of certificates to Admin panel (APNS Sandbox certificate, VOiP certificate) but nothing's solved.

So what's differences between debug & release mode? Did I missing something?

Thanh you.

**Comment by TatankaConCube** [comment]
First of all, check the subscription type [there](https://github.com/ConnectyCube/connectycube-flutter-samples/blob/master/p2p_call_sample/lib/src/managers/push_notifications_manager.dart#L93), then check the environment for event [there](https://github.com/ConnectyCube/connectycube-flutter-samples/blob/master/p2p_call_sample/lib/src/managers/push_notifications_manager.dart#L234). Try to uncomment commented code it should resolve your issue. The main thing on debug build you have to use the DEVELOPMENT environment and on release build - PRODUCTION. On Android you can use any environment for both types of build.

**Comment by soleilpqd** [comment]
I got it.

Thank you!
