### ISSUE TITLE
Google Services Dependency Of ConnectyCube

### ISSUE THREAD

**Issue by blackkara** [ConnectyCube/connectycube-flutter-samples#94]
This is not an actual bug or feature, but a big question for me. It's about Google Services(firebase) In China

Which parts of connectycube depend on google services ? As far as i know,  push notifications directly depend on firebase, so notifications won't be working in China.

This forces me to implement other notification services. But what about other parts of connectycube ? Is the notfications only part that uses firebase ?

**Comment by TatankaConCube** [comment]
Our SDK doesn't have dependencies on Firebase services. You can use Firebase for few features:
- push notifications;
- phone auth;
But on the SDK side, we don't have any transitive dependencies to Firebase.

**Comment by blackkara** [comment]
Useful answer for awareness of google services
