### ISSUE TITLE
IllegalArgumentException: 'content_type' and 'name' are required

### ISSUE THREAD

**Issue by zhukeev** [ConnectyCube/connectycube-flutter-samples#95]
**Specify the sample to which the issue belongs (use [x]):**
[Х] Chat sample
[ ] P2P Call sample
[ ] Conference Call sample

**Platform (use [x])**
[ ] Android
[ ] iOS
[X]Flutter
**Device info**
Manufacture: Xiaomi
Model: Redmi Note 5
OS version: Android 9

**Describe the bug:**
Cannot upload file if it doesn't have an extension.

I see it's because [lookupMimeType](https://pub.dev/documentation/mime/latest/mime/lookupMimeType.html) cannot recognize it

**Steps to Reproduce:**
1. Open file picker with [file_picker](https://pub.dev/packages/file_picker) (it sometimes gives without an extension)
2. Try to upload with ` await uploadFile(file, onProgress: (progress) {
        log('progress= $progress');
      }, isPublic: true)` function
3.
4.

**Logs:**
```
IllegalArgumentException: 'content_type' and 'name' are required

```

**Actual result:**
Having an error

**Expected behavior:**
Has to upload

**Comment by TatankaConCube** [comment]
in the next release, we will provide the possibility to set the mimeType manually, before it you can rename the file by adding an extension (as a temporary workaround).

**Comment by mahmoudsalah37** [comment]
i have same issue when send voice 
but it is work fine with images?????

**Comment by TatankaConCube** [comment]
@mahmoudsalah37 could you please provide logs from the flutter console during upload image and audio? Have you try to specify `mimeType` manually when calling the method `uploadFile`?

**Comment by TatankaConCube** [comment]
I researched Dart SDK and haven't found the [mime type](https://github.com/dart-lang/mime/blob/master/lib/src/default_extension_map.dart) for file extension 'm4a'. What tool do you use for recording voice in this format?

**Comment by mahmoudsalah37** [comment]
> I researched Dart SDK and haven't found the [mime type](https://github.com/dart-lang/mime/blob/master/lib/src/default_extension_map.dart) for file extension 'm4a'. What tool do you use for recording voice in this format?

https://pub.dev/packages/record

**Comment by TatankaConCube** [comment]
have you tried to use a different `AudioEncoder` for your records AudioEncoder

**Comment by mahmoudsalah37** [comment]
> have you tried to use a different `AudioEncoder` for your records
I will try with another one now but why not support  m4a?

**Comment by mahmoudsalah37** [comment]
> > have you tried to use a different `AudioEncoder` for your records

 I will try with another one now but why not support  m4a?

**Comment by TatankaConCube** [comment]
in our SDK we use native dart instruments for getting the mime type from the file extension, but as you can [see](https://github.com/dart-lang/mime/blob/master/lib/src/default_extension_map.dart) dart doesn't know about `m4a` files. Try to specify mime type manually in the method `uploadFile`.

**Comment by TatankaConCube** [comment]
try to use mime type 'audio/mpeg' for audio files

**Comment by mahmoudsalah37** [comment]
> mpeg

mp4 only worked

**Comment by mahmoudsalah37** [comment]
![Capture](https://user-images.githubusercontent.com/31797198/130461478-2f1bb606-bef3-4764-b3a2-e0ce8530484f.PNG)
`  flutterSoundRecorder.startRecorder(
        codec: Codec.aacMP4,
        audioSource: AudioSource.microphone,
        toFile: 'to_file.mp4');`
