### ISSUE TITLE
How to add other opponent in between an active P2P call. 

### ISSUE THREAD

**Issue by raj457036** [ConnectyCube/connectycube-flutter-samples#97]
**Specify the sample to which the issue belongs (use [x]):**
[x] P2P Call sample

**Platform (use [x])**
[x] Android
[x] iOS

**Describe the bug:**
How to add/join another opponent in between an active call like WhatsApp or Telegram. 

**Steps to Reproduce:**
1. call from user 1 to user 2
2. now call from user 3 to user 2 or 1.
3. the call disconnects. even if I accept the new request

another way would be 
when **user 1** calls **user 2** and after some time **user 2** wants to join **user 3** to the same call! 

**How to achieve this behaviour?**

**Comment by TatankaConCube** [comment]
We didn't implement this functionality in our sample. For your case, user3 should know the 'roomId' for join to the call. Use [our doc](https://developers.connectycube.com/flutter/videocalling-conference) for implementing conference calls according to your needs. For simple checking (but not completely right) of joining an existing call, you can hardcode 'roomId' in the app, and in this case, all your users will join the same call. But this case usable only for tests, not for a production app, please study our documentation on how to implement the required features in the right way.

**Comment by raj457036** [comment]
I am asking about the **P2P** calls, not the conference call. 🙂

**Comment by TatankaConCube** [comment]
sorry, I didn't note that you asked about P2P calls and thought that mean the conferences. Yes, it is not possible for P2P calls.
