### ISSUE TITLE
how to control flash during call?

### ISSUE THREAD

**Issue by moyeenhaider** [ConnectyCube/connectycube-flutter-samples#98]
**Specify the sample to which the issue belongs (use [x]):**
[ ] Chat sample
[x ] P2P Call sample
[ ] Conference Call sample

**Platform (use [x])**
[ x] Android
[x ] iOS

**Device info**
Manufacture: 
Model: 
OS version:

**Describe the bug:**
how to control flashlight during call?

**Comment by TatankaConCube** [comment]
@moyeenhaider unfortunately we don't provide this feature in our SDK, but this feature not so hard for implementation and I think we can implement it in the few next releases.

**Comment by moyeenhaider** [comment]
i hope this feature add to SDK soon!
do you think is there any way to implement this in current sdk?

**Comment by TatankaConCube** [comment]
you can try to do this by yourself using this [code](https://github.com/flutter-webrtc/flutter-webrtc/blob/51e46216973e0da0872b77d02534c572e9d0655f/example/lib/src/get_user_media_sample.dart#L120) as an example. `_localStream` you can get in callback `onLocalStreamReceived`

**Comment by moyeenhaider** [comment]
@TatankaConCube  thanks👍
